### ISSUE TITLE
[Protocol] ETag not available for entity with OptimisticConcurrency value

### ISSUE THREAD

**Issue by karataliu** [OData/RESTier#114]
The OptimisticConcurrency annotation is available, but no Etag header is returned.

**Comment by karataliu** [comment]
If-Match, If-NonMatch also do not work.

**Comment by karataliu** [comment]
Should be able to return 304 for GET with If-NonMatch

**Comment by karataliu** [comment]
Related issue:
https://github.com/OData/WebApi/issues/459 

pending on next steps on the statue of that issue.

**Comment by chinadragon0515** [comment]
In Web Api OData, user can specify the message handler in config,like configuration.MessageHandlers.Add(new ETagMessageHandler());

If this configuration is added, then every single entity result will calculate based on the properties which are marked with attributes ConcurrencyCheck. And EATG will be set in the header.

**Comment by chinadragon0515** [comment]
related issue https://github.com/OData/RESTier/issues/22 and https://github.com/OData/RESTier/issues/38

For the support,

1. When an entity type whose has some properties with ConcurrencyCheck attribute, during get request, either single result or collection result, each return result will have "@odata.etag" annotation.

2. When request return a single entity and this setting is added "configuration.MessageHandlers.Add(new ETagMessageHandler());", the response Header will have Etag Header beside the "@odata.etag" annotation in response body.

3. During CRUD, If-Match and If-None-Match are checked.

Items not covered by above issue and need to be covered by this issue,
1. If an item required etag, but during update/delete request, there is no If-Match or If-None-Match tag, should return 428 (precondition required).
2. For action bounded to single entity, and Etag is provided in header, it should be checked.

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
