### ISSUE TITLE
[Protocol] Support Entity Type inheritance

### ISSUE THREAD

**Issue by karataliu** [OData/RESTier#117]

**Comment by lewischeng-ms** [comment]
Also verify type inheritance in URL works after this feature is completed.

**Comment by chinadragon0515** [comment]
The issues will fix in several steps,
0. Model build derived type (PR #402 
1. Query with derived type (PR #410 )
2. Query options work with derived type
3. Patch with derived type
4. Post with derived type
5. Delete with derived type

And note derived type is only for entity type, EF does not support complex type inheritance now, and it is not supported by RESTier now.

**Comment by chinadragon0515** [comment]
All supports is added, close the issue.
