### ISSUE TITLE
$count on OnFilterEntities is not consistent

### ISSUE THREAD

**Issue by liqian19891011** [OData/RESTier#12]
Suppose there is code below in NorthwindDomain.cs
```
        private IQueryable<Customer> OnFilterCustomers(IQueryable<Customer> customers)
        {
            return customers.Where(c => c.CountryRegion == "France");
        }
```
Then in NorthwindController.cs 
```
        [ODataRoute("Customers/$count")]
        public IHttpActionResult GetCustomersCount()
        {
            return Ok(DbContext.Customers.Count());
        }
```
still returns the count of customers from all CountryRegion and this cause the inconsistency problem. And user cannot directly using ``` return Ok(OnFilterCustomers(DbContext.Customers).Count());``` since the OnFilterCustomers is a private method.

**Comment by lewischeng-ms** [comment]
Fixed in #242
