### ISSUE TITLE
[URL] Operations should be supported gracefully

### ISSUE THREAD

**Issue by lewischeng-ms** [OData/RESTier#120]
Currently, if we want to define a function or an action, we need to put two copies of definition in both domain class and controller class. The implementation in domain class is *useless* while only its declaration is used to generate the operation definition in the EDM model. The implementation in the controller class will get called actually. We should let user write *only one* copy of operation code and generate model according to that.

**Comment by lewischeng-ms** [comment]
Model building of functions and actions is supported. 
Related commits:
https://github.com/OData/RESTier/commit/1460432091636372afe0e5cd49846839d82e4909
https://github.com/OData/RESTier/commit/b97531f45a75a680ee4c480111f04186bd2efdb5

**Comment by chinadragon0515** [comment]
Support operation without additional controller is tracked with issue #378, and will be added in the release after 0.5 release.
