### ISSUE TITLE
[Protocol] Batch Transaction Support

### ISSUE THREAD

**Issue by karataliu** [OData/RESTier#122]
Take some comments from a previous discussion thread:

As a service framework, RESTier is responsible for executing the batch request according to request payload order, while it is the client who sends the request that should ensure the right order of each batch operations. Also, both implementations should follow the following statements in OData spec:
http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#_Toc406398364 

**The order of change sets and individual requests in a Batch request is significant. A service MUST process the components of the Batch in the order received. The order of requests within a change set is not significant; a service may process the requests within a change set in any order.**

**All operations in a change set represent a single change unit so a service MUST successfully process and apply all the requests in the change set or else apply none of them. It is up to the service implementation to define rollback semantics to undo any requests within a change set that may have been applied before another request in that same change set failed and thereby apply this all-or-nothing requirement. The service MAY execute the requests within a change set in any order and MAY return the responses to the individual requests in any order. The service MUST include the Content-ID header in each response with the same value that the client specified in the corresponding request, so clients can correlate requests and responses.**

For now, RESTier would follow that rule at least for the basic CRUD operations(which is implemented by Restier), but there could be an issue[#83] when one batch operation targets some user implemented code.

**Comment by lewischeng-ms** [comment]
Dup as #82
