### ISSUE TITLE
[URL] RESTier does not support the following V4 functions

### ISSUE THREAD

**Issue by lewischeng-ms** [OData/RESTier#127]
`maxdatetime`, `mindatetime`, `now`, `totaloffsetminutes`, `totalseconds` and `isof`.

**Comment by lewischeng-ms** [comment]
And spatial functions:

    $filter=geo.distance(geography'SRID=0;Point(12.3 45.6)',geography'SRID=0;Point(142.1 64.1)') lt 1.0

**Comment by cilerler** [comment]
`substringof`

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
