### ISSUE TITLE
Model should be loaded later on demand

### ISSUE THREAD

**Issue by congysu** [OData/RESTier#13]
For now, in MapODataDomainRoute, controller.Domain.GetModelAsync is called.  This is due to webapi.odata's ODataPathRouteConstraint requires an immutable Edm model, instead of Func<> or a model provider.  Therefore, need to create an Edm model when create an OData route.

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
