### ISSUE TITLE
[URL] $ref after navigation property not supported in $expand

### ISSUE THREAD

**Issue by lewischeng-ms** [OData/RESTier#132]
~People/$expand=Trips/$ref

**Comment by chinadragon0515** [comment]
I did some investigation, this is depending on https://github.com/OData/WebApi/issues/167

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
