### ISSUE TITLE
[URL] Property path in $select not supported

### ISSUE THREAD

**Issue by lewischeng-ms** [OData/RESTier#134]
Events?$select=Id,OccursAt/Address

**Comment by lewischeng-ms** [comment]
Depends on ODataLib.

**Comment by chinadragon0515** [comment]
More investigation and confirm with WebApi owner, WebApi has not supported this yet, and tracked with https://github.com/OData/WebApi/issues/673

**Comment by robertmclaws** [comment]
Just leaving a note that this is being tracked by https://github.com/OData/WebApi/issues/196. Hopefully the issues will get re-triaged and we can get this back on the docket.

**Comment by robertmclaws** [comment]
Still not resolved in WebAPI proper, so I'm going to close this for now.
