### ISSUE TITLE
[Design] Make DomainData class non-public

### ISSUE THREAD

**Issue by karataliu** [OData/RESTier#135]
This class is only used to be a placeholder for query source, so no need to be made public:

https://github.com/OData/RESTier/blob/d8dba8914bf58148e6c79dccb4266953f55a938f/src/Microsoft.Restier.Core/DomainData.cs 
https://github.com/OData/RESTier/blob/d8dba8914bf58148e6c79dccb4266953f55a938f/src/Microsoft.Restier.Core/Query/QueryExpressionContext.cs#L178

**Comment by karataliu** [comment]
https://github.com/OData/RESTier/commit/67a0b2b70522b430b141a7f393fde3961578d56a

**Comment by karataliu** [comment]
pending

**Comment by lewischeng-ms** [comment]
If user want to implement his own QueryExpressionSourcer, the `ApiData` class needs to be visible to him.
