### ISSUE TITLE
DateTime columns dropped from api view

### ISSUE THREAD

**Issue by DarekDan** [OData/RESTier#14]
I have a few DateTime? propeties in my EF CodeFirst model, but they are all missing from the OData view. Is there a way to bring them in?

**Comment by liqian19891011** [comment]
@DarekDan The reason DateTime missing is that Web Api OData (RESTier is based upon Web API OData)currently only support DateTimeOffsite. Web API OData will ship the feature supporting in the coming release. Before that, there are several work-around for you to try with the Web API side http://stackoverflow.com/questions/25189557/how-to-get-web-api-odata-v4-to-use-datetime.

**Comment by lewischeng-ms** [comment]
RESTier now supports DateTime as Edm.Date. https://github.com/OData/RESTier/pull/194
