### ISSUE TITLE
Support OData key other than primary key in DB

### ISSUE THREAD

**Issue by congysu** [OData/RESTier#142]
`id` is the primary key in DB:
`~/Customers(id)`

`name` has a unique constraint in `Customers`, use name as the key in EDM:
`~/Customers(name=@name)`

This may relate to alternate keys:
https://github.com/OData/vocabularies/blob/master/OData.Community.AlternateKeys.V1.md
-or-
Enable a different column or property as key during model producing.

**Comment by karataliu** [comment]
Consider new design for ModelProducer and ModelExtender.

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
