### ISSUE TITLE
Verifiy parallel test run

### ISSUE THREAD

**Issue by karataliu** [OData/RESTier#145]
Currently we've got the following in test projects to disable parallel run in xunit 2.0
```
[assembly: Xunit.CollectionBehavior(DisableTestParallelization = true)]
```

Should verify whether we should enable it for non-E2E projects.

**Comment by karataliu** [comment]
Affected projects:

Microsoft.Restier.EntityFramework.Tests
Microsoft.Restier.Samples.Northwind.Tests
Microsoft.Restier.Webapi.Test.Scenario

**Comment by lewischeng-ms** [comment]
Now test run is all OK.
