### ISSUE TITLE
Official User Support Tag e.g. RESTier on Stackoverflow

### ISSUE THREAD

**Issue by jeeshenlee** [OData/RESTier#154]
Create a channel for community users to ask and track the questions using Tag on StackOverflow.

**Comment by congysu** [comment]
@markdstafford might be able to help on this - with ~3k reputation :)

**Comment by lewischeng-ms** [comment]
Thanks @markdstafford for creating the tag (http://stackoverflow.com/questions/tagged/restier).

**Comment by jeeshenlee** [comment]
Thanks.
