### ISSUE TITLE
Wiki: Invalid File Names

### ISSUE THREAD

**Issue by JeremyCaney** [OData/RESTier#16]
Some of the wiki file names have colons (`:`) in them, such as `Samples 1: Getting started   basic.md`. Colons are illegal characters on NTFS file systems. As a result, the Wiki is unable to be cloned to a Windows machine. 

```
error: Invalid path 'Samples 1: Getting started   basic.md'
error: Invalid path 'Samples 2: Getting started - advanced.md'
error: Invalid path 'Samples 3: How to enable multiple controllers.md'
error: Invalid path 'Samples 4: How to add OData operations.md'
```

**Comment by liqian19891011** [comment]
Thanks for your advice, fixed.

**Comment by JeremyCaney** [comment]
Awesome, thank you for the quick fix! This will make it easier to update the documentation.
