### ISSUE TITLE
Support key as segment

### ISSUE THREAD

**Issue by congysu** [OData/RESTier#160]
Add 'key-as-segment' support to RESTier, such as `~/Customers/{id}`.

**Comment by lewischeng-ms** [comment]
Rely on https://github.com/OData/WebApi/issues/105

**Comment by chinadragon0515** [comment]
This is supported, can be enabled via 

config.SetUrlConventions(ODataUrlConventions.ODataSimplified);

**Comment by chinadragon0515** [comment]
Will add some test cases to support.

**Comment by chinadragon0515** [comment]
Code is merged,add docs now.

**Comment by chinadragon0515** [comment]
Doc is added. close the issue.
