### ISSUE TITLE
Multiple controller should work more wisely 

### ISSUE THREAD

**Issue by liqian19891011** [OData/RESTier#17]
### Problems
For example, we have a the default controller 
```
public class AdventureWorksController : ODataDomainController<AdventureWorksDomain>
    {
        private AdventureWorks DbContext
        {
            get { return Domain.Context; }
        }
    }
```
And one special controller 
```
public class CustomersController : ODataController
{
        private readonly AdventureWorks _context = new AdventureWorks();

        [ODataRoute("Customers({key})/EmailAddress")]
        public string GetEmailAddress([FromODataUri] int key)
        {
            return _context.Customers.Single(c => c.CustomerID == key).EmailAddress;
        }
}
```
When try to request `~/Customers(1)/EmailAddress`, it can work correctly but when try to request `~/Customers`, it gets 404 error.User has to add the basic `Get` method in the `CustomersController` to make it work. 

### Suggested behavior
The default controller can automatically handle the basic CRUD operations, these should be "inherited" to the specific controllers. In other word, user don't have to write the logic already implemented in the default controller. In the code above, for example
`~/Customers`  -- should work directly by `AdventureWorksController` 
`~/Customers(1)/EmailAddress` -- should work directly by `CustomersController`

**Comment by lewischeng-ms** [comment]
Done in #198
