### ISSUE TITLE
Add support to Ignore "Unsupported EdmObject" on POST and PUT.

### ISSUE THREAD

**Issue by jeeshenlee** [OData/RESTier#172]
In production apps, there's different clients and updates on the cloud server that might have remove certain entity while the client side (e.g. mobile app) has yet to be updated. I think we need support to Ignore "Unsupported EdmObject" on POST and PUt.

Example below, I'm getting an error when my javascript client added "Amenities" on the client side and use it as like ViewModel to support the UI, but when push the object back to OData server, here's what I got.

{
  "error":{
    "code":"","message":"The request is invalid.","innererror":{
      "message":"edmEntityObject : The property 'Amenities' does not exist on type 'PointLoc.Data.Content'
. Make sure to only use property names that are defined by the type.\r\n","type":"","stacktrace":""

```
}
```

  }
}

**Comment by congysu** [comment]
RESTier is yet to support Open type; therefore client can over posting.

**Comment by jwobbe** [comment]
Please consider this a high priority from my perspective.  Keeping all clients in sync with the server is not always feasible.  Some of our client entities intentionally have extra (calculated) fields and this is causing a lot of problems for us.

**Comment by chinadragon0515** [comment]
Investigate the issue,
1. For the ODL lib part, it does not allow ignore undeclared properties for request now. This will be addressed in ODL 7.0, tracked with issue https://github.com/OData/odata.net/issues/103

2. For WebApi part, either uses configurations to get all formats, and override the ODataMessageReaderSettings's UndeclaredPropertyBehaviorKinds  or define a new formatter classes and added to configurations.

**Comment by jwobbe** [comment]
Chinadragon0515, I'm having a hard time understanding your comment.  Are you suggesting that I can work around this issue?  If so, could you please provide an example of how?  Thanks.

**Comment by chinadragon0515** [comment]
@jwobbe we donot have a workaround here as the exception is from lowest lib (OData .NET lib https://github.com/OData/odata.net/) which is used by RESTier, it has an issue to tracked, after that issue is resolved, then the next level of lib WebApi integrated by RESTier need to make changes to support, and RESTier should be free to get the support.

There is one alternative we to solve this is make the entity type as open type, then all undeclared properties will be read and save to a dictionary. As to how to use open type, refer to this sample https://github.com/OData/ODataSamples/tree/master/WebApi/v4/ODataOpenTypeSample

**Comment by robward-ms** [comment]
Fixed in ODL, change will be available in the ODL nightly build dated 2017/10/27.

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
