### ISSUE TITLE
Allow connectionstring name to be picked from the URL so a single instance of the service may be reused for different tenants

### ISSUE THREAD

**Issue by albertosilva** [OData/RESTier#18]
I've posted the following message on OData.org blog:
*"We need to allow a single OData Service instance to address multiple connection strings configured in the web config file depending on a key to be included on the URI, like
http://mywebsite.com/myODataService/ConnectionStringA/Products
 where ConnectionStringA is the connection name. Does Restier address this need?"*
I appreciate Quian Li's reply, and I've tried miself to find how to achieve it.
I'm not familiar with ASP.NET MVC, but I've tried to change the WebApiConfig.cs as follows:
```csharp
public static class WebApiConfig
{
    public static void Register(HttpConfiguration config)
    {
        config.MapHttpAttributeRoutes();
        RegisterM2uSalesV4(config, GlobalConfiguration.DefaultServer);
        config.Routes.MapHttpRoute(
            name: "DefaultApi",
            routeTemplate: "api/{controller}/{id}",
            defaults: new { id = RouteParameter.Optional }
        );
    }

    public static async void RegisterM2uSalesV4(HttpConfiguration config, HttpServer server)
    {
        await config.MapODataDomainRoute<M2uSalesV4Controller>(
           "M2uSalesV4Api", "api/m2uSalesV4/{company}/",
            new ODataDomainBatchHandler(server));
    }
}
```
Then on my controller:
```csharp
    public class M2uSalesV4Controller : ODataDomainController<M2uSalesV4Domain>
    {
        //private m2uSalesV4OData.Models.m2uSalesv4Entities DbContext
        //{
        //    get { return Domain.Context; }
        //}
        public  Task<System.Net.Http.HttpResponseMessage> Get([FromUri]string company, CancellationToken cancellationToken)
        {
            return  this.Get(cancellationToken);
        }
    }
```
and I've checked that the value I've included in the URL I'm using on fiddler for the company gets to this method, but can't find a way to use it to create a DbContext using the company name as the connection string key.

The only way I found, which I'm not proud of was to set a static string property:
```csharp
public class M2uSalesV4Controller : ODataDomainController<M2uSalesV4Domain>
{
    //private m2uSalesV4OData.Models.m2uSalesv4Entities DbContext
    //{
    //    get { return Domain.Context; }
    //}
    public static string CompanyName = "m2uSalesv4Entities";
    public Task<System.Net.Http.HttpResponseMessage> Get([FromUri]string company, CancellationToken cancellationToken)
    {
        CompanyName = company;
        return this.Get(cancellationToken);
    }
}
```
and change the DbContext initializer:
```csharp
    public partial class m2uSalesv4Entities : DbContext
    {
        }
            public m2uSalesv4Entities()
            : base("name=" + M2uSalesV4Controller.CompanyName) //  "m2uSalesv4Entities"
        {
        }
```
and it worked! I can now use:
http://localhost:64068//api/m2uSalesV4/companyA/myTable
http://localhost:64068//api/m2uSalesV4/companyB/myTable
to get values from two databases with the same structure, each with its own connectionstring:
```xml
  <connectionStrings>
    <add name="m2uSalesv4Entities" connectionString="metadata=re ..."/>
    <add name="companyA" connectionString="metadata=res://*/Models.m ..."/>
    <add name="companyB" connectionString="metadata=res://*/Mode ..."/>
  </connectionStrings>
```
So, I'm looking forward to better alternatives to pick the appropriate connection string .

**Comment by challenh** [comment]
if there aren't many connection strings, hard coded mapping of endpoint-DB should work. for example, ~/api/m2uSalesV4/companyA --> M2uSalesV4CompanyAController : 
```
    public static async void RegisterM2uSalesV4(HttpConfiguration config, HttpServer server)
    {
        await config.MapODataDomainRoute<M2uSalesV4CompanyAController>(
           "M2uSalesV4ApiCompanyA", "api/m2uSalesV4/companyA/",
            new ODataDomainBatchHandler(server));
    }
```
M2uSalesV4CompanyAController can connect to its own DB. similarly for companyB.

but if the goal is to build different endponts on top of many identical DB like companyA,B,C.... and hope to re-use one controller and one domain class for all of them, it becomes a different story. let's talk about it

**Comment by JeremyCaney** [comment]
To me, this seems like a highly-specialized need beyond the typical use cases of a library like this. I would think it should be possible to write a custom route handler to deal handle this type of scenario. In terms of building it into the product, however, I'd expect basic features (such as attribute routing and relationships) to take priority.

**Comment by albertosilva** [comment]
To me, on LOB solutions it's quite common to have a single instance of a service serving more than one database, instead of having to create and maintain one instance of the service per database. Either way, it's working, if someone has the same need feel free to use this, and if someone finds a better way to achieve it, please share :)

**Comment by challenh** [comment]
@albertosilva, I would suggest doing more tests on your solution, there should be 2 problems: 
(1) threading issue with the static variable : M2uSalesV4Controller.CompanyName
(2) $batch request needs to  handled carefully.
