### ISSUE TITLE
Update TripPin sample to include Edm.Date support

### ISSUE THREAD

**Issue by congysu** [OData/RESTier#180]
Update a sample, such as RESTier [TripPin](https://github.com/OData/RESTier/tree/master/test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin) to include Edm.Date support.

**Comment by lewischeng-ms** [comment]
Checked in as https://github.com/OData/RESTier/commit/3ba1201ed9ba57b4e047c9f63e139b14f9a3efda
