### ISSUE TITLE
Use more up-to-date database for RESTier samples

### ISSUE THREAD

**Issue by liqian19891011** [OData/RESTier#19]
Customer complains 
> Why are you using Northwind and not a database compatible with VS 2013? It’s a PITA to have to get Northwind converted to VS 2013 and will stop many people at step one if they try the tutorial.

One better option is to use AdventureWorks or AdventureWorksLT (light version of AdventureWorks). They have better support for higher version of SQL server and can easily download the data files (.md) easily at [codeplex](http://msftdbprodsamples.codeplex.com/releases/view/93587) and [codeplex](http://msftdbprodsamples.codeplex.com/releases/view/125550)

**Comment by cwoodruff** [comment]
I suggest using Chinook database also. http://chinookdatabase.codeplex.com/

**Comment by lewischeng-ms** [comment]
Done in https://github.com/OData/ODataSamples/commit/d78a8c9b99453b19b8249867f38d5ba4be5d18d2
