### ISSUE TITLE
[Design] Support projection in RESTier

### ISSUE THREAD

**Issue by lewischeng-ms** [OData/RESTier#192]
Consider using AutoMapper, etc.

**Comment by lewischeng-ms** [comment]
Related issue #72

**Comment by xandervdm** [comment]
I assume this will provide functionality to allow "custom entities" over and above the actual database entities. Please add full support for CRUD on these custom entities / projections.

**Comment by joshbooker** [comment]
+1 Highly needed to get RESTier on par with WCS DS feature set. Please make this a priority!

**Comment by xandervdm** [comment]
The use case for this is where you want to create custom entities (or projections) to make the UI development easier. You then want to write the server side code to implement the CRUD methods, "translating" between the custom entities and the actual underlying entities in those methods. Relationships between custom entities should also be supported. 

We did a lot of this with the old RIA Domain Services...so trying to get the same level of functionality with RESTier.

**Comment by chinadragon0515** [comment]
related to issue https://github.com/OData/RESTier/issues/182

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
