### ISSUE TITLE
ConventionalEntitySetProvider doesn't work for parsed model.

### ISSUE THREAD

**Issue by karataliu** [OData/RESTier#196]
https://github.com/OData/RESTier/blob/d8dba8914bf58148e6c79dccb4266953f55a938f/src/Microsoft.Restier.Conventions/Conventions/ConventionalEntitySetProvider.cs#L71-L83

**Comment by lewischeng-ms** [comment]
Fixed in https://github.com/OData/RESTier/commit/edcea34f441742d35687e1b227d0380800b0b4ec#diff-8c4312170b060f738686ab2ad2e91ad0R100
