### ISSUE TITLE
Leverage re-linq for query transformation

### ISSUE THREAD

**Issue by congysu** [OData/RESTier#199]
Related issue: https://github.com/OData/WebApi/issues/245

**Comment by lewischeng-ms** [comment]
Now RESTier won't block the usage of re-linq. After fully moved to EF7, we can consider use re-linq's `QueryableBase<T>` as the base query type.

**Comment by lewischeng-ms** [comment]
Do with EF7 support.

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
