### ISSUE TITLE
EF7 support in RESTier

### ISSUE THREAD

**Issue by liqian19891011** [OData/RESTier#20]
Customer comments on RESTier blog

> I see that you are currently using Entity Framework 6.1.1. Do you have plans for EF7 and how you are ready for its core changes (according to http://blogs.msdn.com/b/adonet/archive/2014/10/27/ef7-v1-or-v7.aspx)?For now I briefly inspected the Microsoft.Restier.EntityFramework assembly, and it seems there is not much to change there. Thanks.

**Comment by JeremyCaney** [comment]
I am also interested in the answer to this, especially given how WCF Data Services lagged behind Entity Framework. Adoption for larger projects will certainly be dependent on having confidence in its timely upkeep.

**Comment by congysu** [comment]
Related issues #57, #58.

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
