### ISSUE TITLE
Role-based security Not working

### ISSUE THREAD

**Issue by Skylertodd** [OData/RESTier#205]
When attempting to implement API Security using EnableRoleBasedSecurity it doesnt seem to respect the Grants and Denys set.

From my testing it feels as though DomainPermissionType.Inspect is behaving just as DomainPermissionType.All.

**Comment by Skylertodd** [comment]
From your Northwind sample 
I changed the security on Products to the following

    [EnableConventions]
    [EnableRoleBasedSecurity]
    [Grant(DomainPermissionType.All, On = "Customers")]
    [Grant(DomainPermissionType.Inspect, On = "Products")]
    [Grant(DomainPermissionType.Read, On = "Products")]
    [Grant(DomainPermissionType.All, On = "CurrentOrders")]
    [Grant(DomainPermissionType.All, On = "ExpensiveProducts")]
    [Grant(DomainPermissionType.All, On = "Orders")]
    [Grant(DomainPermissionType.All, On = "Employees")]
    [Grant(DomainPermissionType.All, On = "Regions")]
    [Grant(DomainPermissionType.Inspect, On = "Suppliers")]
    [Grant(DomainPermissionType.Read, On = "Suppliers")]
    [Grant(DomainPermissionType.All, On = "ResetDataSource")]
    public class NorthwindDomain : DbDomain<NorthwindContext>

After doing so Products still accepted Updates and Delete is still returning the Ef Error describing that there is a dependency preventing the delete... both of these signs are telling me that the security isn't preventing the commands attempt at Updating or Deleting.

**Comment by congysu** [comment]
@Skylertodd We may not ship the role-based security dll in a next minor release.

**Comment by biaol-odata** [comment]
Related issue #190 is closed.
