### ISSUE TITLE
Consider allow disable conventions

### ISSUE THREAD

**Issue by karataliu** [OData/RESTier#219]
DomainBase::DomainConfiguration

 configuration = this.CreateDomainConfiguration();
configuration.EnableConventions(this.GetType());

Currently, user hook point would be set up before enable conventions, if we move EnableConventions to DomainBase's CreateDomainConfiguration, user may be able to disable various conventions by adding non-delegating hooks.

**Comment by chinadragon0515** [comment]
With PR #368 , user can override configureApi method, and decide whether to call AddConversionBasedServices method to enable Conversion based services, close this issue.
