### ISSUE TITLE
Fix cache expander, sourcer in DefaultQueryHandler

### ISSUE THREAD

**Issue by karataliu** [OData/RESTier#226]
In Expand, Source methods.

**Comment by biaol-odata** [comment]
Hi Dong, we are starting to clean up the bug backlogs now. Can you please provide further details, such as whether it is a bug or feature request, and expected behavior etc?
Thanks.

**Comment by biaol-odata** [comment]
@karataliu

**Comment by karataliu** [comment]
It should mean whether we could have better way to deal with expander/sourcer fields of QueryExpressionVisitor class. Currently they serve as _cache_ only.

As per:
https://github.com/OData/RESTier/blob/68e14c40bd26bdcea4ae402ffce9f113aca43450/src/Microsoft.Restier.Core/Query/DefaultQueryHandler.cs#L345-L354
```
if (this.expander == null)
{
    this.expander = this.context.QueryContext
        .GetApiService<IQueryExpressionExpander>();
}

if (expander == null)
{
    return visited;
}
```
We'll still call GetApiService every time even if no service is registered. The questions here could be:

- Is there a need for dynamic registering services?
- Can we consider other Lazy loading methods?
- If the cost for GetApiService is low, we could consider just call the api every time needed?

It's been long time but hope can catch up. I recorded it here as there could be some potential code refinements. Since the codebase has changed a lot, please feel free to close the issue based on new evaluations.

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
