### ISSUE TITLE
Fix EF7 project related issues

### ISSUE THREAD

**Issue by karataliu** [OData/RESTier#245]
1. Model builder:
src/Microsoft.Restier.EntityFramework7/Model/ModelProducer.cs::CreteEntityType
2. StyleCop warnings
3. Test cases failure.

**Comment by karataliu** [comment]
#1 done with https://github.com/OData/RESTier/commit/55d573454cc109fa57b18cf45c962f19ac4c3135

**Comment by chinadragon0515** [comment]
Close the issue as Ray has helped fixed EF7 projects related issue.
