### ISSUE TITLE
0.4.0-rc release referenced in documentation is not available through NuGet

### ISSUE THREAD

**Issue by ivanko2000** [OData/RESTier#248]
The documentation contains release notes for version 0.4.0-rc [http://odata.github.io/RESTier/#03-14-0-4-0-rc], as well as bootstrap instructions with screenshots indicating NuGet availability [http://odata.github.io/RESTier/images/nuget.PNG], yet this release is not (currently?) available on Nuget - the latest version is 0.3.0-beta2 [https://www.nuget.org/packages/Microsoft.Restier].

What am I missing? Is this expected?

**Comment by lewischeng-ms** [comment]
@ivanko2000 Sorry for the inconvenience. The documentation was written for the coming release. Now we have published nuget packages for 0.4.0-beta. The documentation marked with 0.4.0-rc here should apply to 0.4.0-beta. Please checkout again. Thanks.

**Comment by lewischeng-ms** [comment]
@ivanko2000 Documentation fixed in https://github.com/OData/RESTier/commit/b630cabf8927cc3fb4187204853dfd82319bae66

**Comment by ivanko2000** [comment]
Thank you for the update - everything is available as expected now.
