### ISSUE TITLE
Will RESTier support  $expand=*  ?

### ISSUE THREAD

**Issue by ivanko2000** [OData/RESTier#252]
To expand all available navigation properties of an entity type, as per:

http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part2-url-conventions/odata-v4.0-errata02-os-part2-url-conventions-complete.html#_Toc406398162

As far as I can tell, it does not support it at the moment.

**Comment by lewischeng-ms** [comment]
@ivanko2000 Sorry for the inconvenience. We already have the issue #133 opened for this. This is a limitation in `ODataLib.UriParser`, one of the core dependencies of RESTier. So currently `$expand=*` cannot be supported.

**Comment by ivanko2000** [comment]
Thank you for clarification. Closing as duplicate of #133. Hopefully can be addressed soon.

**Comment by chinadragon0515** [comment]
This is supported now, check with newest Restier code.

**Comment by ivanko2000** [comment]
Confirmed - it works. Thank you!
