### ISSUE TITLE
EntityFramework7 project has a build error

### ISSUE THREAD

**Issue by MichaelSimons** [OData/RESTier#253]
If you pull the tip, open the RESTier.EF7.sln and build you will get the following build error:

Severity	Code	Description	Project	File	Line
Error	CS0122	'ExpressionHelpers' is inaccessible due to its protection level	Microsoft.Restier.EntityFramework7	C:\Repos\RESTier\src\Microsoft.Restier.EntityFramework\Query\QueryExecutor.cs	67

This appears to be caused by change https://github.com/OData/RESTier/commit/68df01533cbfe0118005527a0b9ddb211d858824#diff-26ae561cd37d4d54127e10f52a39a85b

The fix is to add ExpressionHelpers.cs and ExpressionHelperMethods.cs as Shared files to the EntityFramework7 project.

**Comment by lewischeng-ms** [comment]
@MichaelSimons Thanks very much for reporting this issue. Fixed in https://github.com/lewischeng-ms/RESTier/commit/e635a044f3f2328fa5248081fc373b2c1e275b53
