### ISSUE TITLE
Query $count=true will throw exception

### ISSUE THREAD

**Issue by kinosong** [OData/RESTier#255]
Version: 0.4.0-beta
In Northwind sample, when I browse http://localhost:31181/api/Northwind/Orders?$count=true, it will return following result:

{
  "error":{
    "code":"","message":"An error has occurred.","innererror":{
      "message":"Exception has been thrown by the target of an invocation.","type":"System.Reflection.TargetInvocationException","stacktrace":"   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\r\n   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)\r\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)\r\n   at System.Web.OData.ExpressionHelpers.Count(IQueryable query, Type type)\r\n   at System.Web.OData.Query.CountQueryOption.GetEntityCount(IQueryable query)\r\n   at System.Web.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)\r\n   at Microsoft.Restier.WebApi.RestierController.GetQuery() in e:\\sdk\\RESTier-0.4.0-beta\\src\\Microsoft.Restier.WebApi\\RestierController.cs:line 418\r\n   at Microsoft.Restier.WebApi.RestierController.<Get>d__1.MoveNext() in e:\\sdk\\RESTier-0.4.0-beta\\src\\Microsoft.Restier.WebApi\\RestierController.cs:line 77\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()","internalexception":{
        "message":"Calling the methods in 'QueryableSource' or 'QueryableSource<T>' is not supported.","type":"System.NotSupportedException","stacktrace":"   at Microsoft.Restier.Core.QueryableSource.System.Linq.IQueryProvider.Execute[TResult](Expression expression) in e:\\sdk\\RESTier-0.4.0-beta\\src\\Microsoft.Restier.Core\\QueryableSource.cs:line 71\r\n   at System.Linq.Queryable.LongCount[TSource](IQueryable`1 source)"
      }
    }
  }
}

**Comment by lewischeng-ms** [comment]
@kinosong Sorry for the inconvenience. It's a known issue tracked by #136. We will consider adding this feature in the next major release. Thanks.

**Comment by kinosong** [comment]
Thanks for your response. Any plan for next major release? Is there any way i can extend the feature on my side (by hook or something) before next release?

**Comment by lewischeng-ms** [comment]
@kinosong Since there is a customer need for $count query option, I am currently working on it:P The feature should be available in 0.4.0-rc which will be released soon. Please help test at that time.

**Comment by lewischeng-ms** [comment]
PR #257

**Comment by kinosong** [comment]
That's very kind of you! I will definitely test it when it is available.

**Comment by lewischeng-ms** [comment]
Hi @kinosong , we have released `0.4.0-rc`. Please upgrade to it and have a try! Thanks.

**Comment by kinosong** [comment]
it works now, thank you very much!
