### ISSUE TITLE
Function support for string return type or string arguments

### ISSUE THREAD

**Issue by marianc** [OData/RESTier#258]
Hi,

I am trying to use an unbound function which returns a string or which takes string as arguments but in both cases I get an error: 'Not supported type: System.Char.'

Please find below the code to illustrate the problem:

```
public class DataSourceController : ODataController
{
	...
    
    [ODataRoute("GetPersonAge(name={name})")]
    public IHttpActionResult GetPersonAge(string name)
    {
        return Ok(Api.GetPersonAge(name));
    }

    [ODataRoute("GetSamplePerson(n={n})")]
    public IHttpActionResult GetSamplePerson(int n)
    {
        return Ok(Api.GetSamplePerson(n));
    }
    
	...
    
}


public class DataSourceApi : DbApi<DataSourceContext>
{

    [Function]
    public int GetPersonAge(string name)
    {
        return 35;
    }

    [Function]
    public string GetSamplePerson(int n)
    {
        return "Person Name";
    }

}

```

Thank you for your help.

**Comment by lewischeng-ms** [comment]
@marianc Thank you very much for reporting this issue. This is a bug in a helper method which is to get the element type from a given type. Since `string` implements `IEnumerable<char>`, the method mistakenly thinks the element type is `Char` and returns it. I will fix this issue soon.

**Comment by lewischeng-ms** [comment]
Fixed in https://github.com/OData/RESTier/commit/3f659ea80d9af593201ac5fc154d0359927378aa

**Comment by marianc** [comment]
Thank you for the very quick response and solution.
It took me some time to check it into my application but it works fine.
