### ISSUE TITLE
Expose calculated / dynamically generated EF properties

### ISSUE THREAD

**Issue by ivanko2000** [OData/RESTier#261]
I apologize if I am missing something obvious (or if this is not possible due to technical limitations - I am not well versed in EF & OData), but it seems this is currently not supported in RESTier, even though one would think surfacing such dynamically generated / calculated properties not backed by DB tables would be a frequent use case...

Calculated EF column - e.g. marked with [NotMapped] attribute or Ignore()'d using fluent API. This excludes them from DB mapping (but should not remove them from EF altogether?)

As far as I can tell, RESTier ignores those properties and does not expose them; there is a reported issue https://github.com/OData/RESTier/issues/5 that might be related to this question, but no resolution or clarification for it either.

Found an article http://daveaglick.com/posts/computed-properties-and-entity-framework that might be relevant as a possible solution, but not sure how exactly to apply it in RESTier context...

To ground this question in a concrete example: I have a legacy database that I cannot change for backwards compatibility reasons (therefore - EF code-first with existing DB); it has a field (table column) with a representation that is not optimal; I could convert it on the fly and present it in a better, user-friendly format; even a read-only [getter-only] solution is good enough; even better (if possible) - if new entry is created or existing entry is updated (in this modified format), to convert it [in setter] back to sub-optimal format in the DB. How do I handle this in RESTier? [NotMapped]/Ignore()'d property seemed like a natural way to address it, but no luck.

**Comment by lewischeng-ms** [comment]
@ivanko2000 That's a good suggestion. And yes, your understanding is right. Currently `Restier.EF` builds the EDM model directly based on the "model" (i.e., the `MetadataWorkspace`) which EF builds from the `DbContext`. So what ignored by EF will be invisible to RESTier's model builder as well. This is a problem. We will try to improve this with in-memory provider in the next major release. Thanks!

**Comment by chinadragon0515** [comment]
@ivanko2000 In RESTier 0.5.0, we adopted Web API OData model build, any property which has NotMapped attribute will not been built as part of the model.

**Comment by chinadragon0515** [comment]
@ivanko2000 When you said RESTier to support these computed properties, you means some property which was added from the CLR class generated from code first from EF model? Then you want to be able to select these properties? 


Like original CLR class from Model is 

public class Person
{
	public string FirstName{get;set;}
	public string LastName{get; set;}
}

Then the class will be changed to 
public class Person
{
	public FullName{
		get
		{
			return FirstName+" " + LastName;
		}
		set{
			FirstName = firstpart of FullName;
			LastName = second part of FullName
		}
	}
	
	[NotMapped]
	public string FirstName{get;set;}
	[NotMapped]
	public string LastName{get; set;}
}

The expectation is RESTier will expose FullName but in backend, it will be converted to FirstName and LastName, am I correct? 

If this is the case, and only need for query now, will imperative views work for you? Refer to issue https://github.com/OData/RESTier/issues/72 for more detail.

We also have issue https://github.com/OData/RESTier/issues/192 to track projection support.

**Comment by ivanko2000** [comment]
If I correctly understand the problems covered by the issues mentioned, #192 might be describing a similar/same goal, although it's not clear enough from the issue description if the general projection / object-to-object mapping approach applies exactly to my specific concern. I'll rephrase the problem in terms of your example above - please tell me if it matches #192:

"Code-first with existing database" use case. FirstName and LastName are actual fields in the backing database and store the relevant data elements; there is no FullName field in the DB - it's a calculated field, a more convenient representation of the data - the "logical model" - it has to be Ignored()/NotMapped for EF, otherwise it will fail on this non-existent "DB field".
```
public class Person
{
    [NotMapped]
    public FullName {
        get { return FirstName+" " + LastName; }
        set { FirstName = [firstpart of FullName]; LastName = [second part of FullName]; }
    }

    public string FirstName {get;set;}
    public string LastName {get; set;}
}
```
The result is that FullName is ignored by RESTier as well, so only the "physical model" is exposed this way, not the "logical" one. Yes, one can access this calculated property programmatically as part of the CLR class, but it's not very useful in the RESTier use case - the value would be in allowing the automatic RESTier exposure of the logical model already expressed in the code shown above.

**Comment by chinadragon0515** [comment]
For #192 , its purpose we will have two class, one for persistent and one for view, and odata will be exposed data based on view class, in other word,

We have view class 

```
public class Person1
{
    public FullName{get;set;}
}

```
And persistent class
```
public class Person2
{
    public string FirstName{get;set;}
    public string LastName{get; set;}
}
```

Then there is some map logic between these two class. End user and OData will operate with Person1, then request will be mapped to Person2 and retrieve/update data in data store.

My comment above is trying to interpret what you need.

**Comment by ivanko2000** [comment]
Based on your description, I think the motivation for this issue and #192 is similar/same, but the implementations differ. Returning to the example I provided above:
```
public class Person
{
    [NotMapped]
    public FullName {
        get { return FirstName+" " + LastName; }
        set { FirstName = [firstpart of FullName]; LastName = [second part of FullName]; }
    }

    public string FirstName {get;set;}
    public string LastName {get; set;}
}
```
FirstName / LastName represent the physical model - what's stored in the DB. FullName is [part of] the logical model; it's necessarily marked as [NotMapped] so that EF does not fail on it (no such field) but it's still part of the Person POCO, it's available to RESTier for inspection and interpretation as the logical data model to be handled as part of the "view class" (in your terminology).

So this would allow to avoid explicit separation of persistent/view (physical/logical) representations and object to object mappings (at least as far as developer is concerned - internally RESTier might still need to split those representations and map them?).

Note that in this case First/LastName fields are also part of the logical model. It might be useful to introduce some kind of RESTier attribute [Hidden?] to allow removal of those fields from the logical model presented by RESTier if necessary.

**Comment by chinadragon0515** [comment]
With #192, we plan to use some library to help us cover the mapper for the expression which has clear separation between logic and physical part and odata model is based on logic part and this meets most of our consumers scenario who does not make any changes to the generated code from EF.

For model builder, odata reuse attributes from EF, if you prefer some attribute special for Odata like odata does not use NotMapped but introduce something new like Hidden, then open an issue in this URL https://github.com/OData/WebApi, as RESTier model builder uses Web Api OData conversion model builder.  Web Api OData team will discuss and prioritize the item.

For now, I will suggest you use something like PR #461 if you only want query.
Or you can implement a class implements IQueryExpressionProcessor, and modify the query expression as you want before it is submit to database, you can refer some existing implement like this one https://github.com/OData/RESTier/blob/master/src/Microsoft.Restier.Core/Conventions/ConventionBasedQueryExpressionProcessor.cs, which will add additional where into existing LINQ expression.

**Comment by chinadragon0515** [comment]
@ivanko2000 can I know your comments? will something like PR #461 works for your? thanks

**Comment by ivanko2000** [comment]
I see that there have been quite a few updates added in 0.6 - thank you; I'll need to review some of those to see if they address all my use cases. Imperative views will cover some of them, but not all. #192 "projections" might cover the rest - will have to wait and see how it will actually be implemented. 

For reference, here is another example that demonstrates the "impedance" between the physical (working with pre-existing database/schema) and logical model and various [non-ideal] ways of solving it: http://stackoverflow.com/questions/27781607/exclude-property-from-webapi-odata-ef-response-in-c-sharp; one of my use cases is a similar problem where I have the password-like field in the DB; I want to be able to operate on it programmatically (EF) but not expose it to OData / end users.

Go ahead and close the issue for now - if necessary, I'll reopen it later.

**Comment by chinadragon0515** [comment]
@ivanko2000  thanks

I read through the whole thread in stackoverflow, seems the request is the password field should be exposed in model, so the query in server side can still see the password and operate with it, also user can update the password, but the password should be removed from response (as it is in the model, it means value is set to null).

If this is what you need, now we allow user to customize the output for update/insert/delete while implementing something like http://odata.github.io/RESTier/#02-03-Submit-Logic or http://odata.github.io/RESTier/#02-09-Customize-Submit,  but for query, we only allow user to customize the query expression before query is executed, do you think we expose some interface for user to customize the query output will work for you?

In other word, we expose an interface with method like "IQueryable OnQueryedResult(IQueryable originaresult)", and user can customize the result in this method before the result is final show to end user.

I will open a new issue to track this, you can comments on issue https://github.com/OData/RESTier/issues/467

BTW, do you have any other request/suggests/comments for restier?  If you have any, feel free to let us know, we have not GAed yet, it is much easier to change now.

**Comment by chinadragon0515** [comment]
@ivanko2000 I figure out a way to support your request, I create a sample in link https://github.com/OData/ODataSamples/tree/master/RESTier/SpatialSample, just refer to property FullName,FirstName,LastName.

From end user view, user will only need FullName in the model and only query or update FullName, FirstName and LastName is hiddne from user view.

From database view, it will have two properties which is FirstName and LastName, and no property named FullName.

The thing need some effort is for model build, I am working with Web Api team to see how we can simplify this part. Then I will add to existing restier trippin sample.

Let me know whether this what you need.

**Comment by ivanko2000** [comment]
@chinadragon0515, that is _exactly_ what I had in mind.

Glad to see this can be done now with some effort, but if it could be simplified to avoid custom ModelBuilder altogether (e.g. with extra attributes? and/or still exposing public get/set EF-NotMapped fields through RESTier?), that would be marvelous.

**Comment by chinadragon0515** [comment]
For model part, I am working with Web Api OData now, they are busy on the next big release now, I will work close with them to simplify this.

**Comment by ericgrover** [comment]
So what if we wanted to filter on the computed property (i.e. FullName)?  Would we have to write our own custom logic to read the Query Options in the controller and convert them into a database query?

**Comment by chinadragon0515** [comment]
@ericgrover Yes, you will have to now, I also work with issue https://github.com/OData/RESTier/issues/468 to see whether we have some better way to support these kinds of properties in query options, and first on one-one mapping property now (GeographyPoint mapping to DbGeography).
