### ISSUE TITLE
0.4.0-rc2 with fix for Issue #258

### ISSUE THREAD

**Issue by ivanko2000** [OData/RESTier#263]
Would it be possible to make the version with the fix for Issue https://github.com/OData/RESTier/issues/258 available through NuGet? I also ran into this problem with inability to return a string from an action/function; glad that it was fixed recently but doing a full local build is not as flexible for deployment as the NuGet route...
That is - only assuming this is a simple/quick matter, otherwise please ignore and just keep doing the great job with RESTier. :-)

**Comment by lewischeng-ms** [comment]
Hi @ivanko2000 we have released 0.4.0-rc2 containing the fix for your issue. Please find the NuGet packages from: https://www.nuget.org/packages/Microsoft.Restier/0.4.0-rc2
