### ISSUE TITLE
Output swagger.json

### ISSUE THREAD

**Issue by congysu** [OData/RESTier#265]
RESTier to output swagger.json besides $metadata.

**Comment by joshbooker** [comment]
@congysu if ODataSwaggerProvider is added to System.Web.OData then it will work for RESTier.  No additional change is needed for RESTier as swagger will be available at Swashbuckle default URL (/swagger/docs/v1).  
See https://github.com/OData/WebApi/issues/520 and https://github.com/rbeauchamp/Swashbuckle.OData/blob/master/Swashbuckle.OData/ODataSwaggerProvider.cs

**Comment by congysu** [comment]
@joshbooker That is a different approach that also works. Warmly welcome your contributions such as a pull request.

**Comment by mikepizzo** [comment]
Popular request; developers should be able to support Swagger V2, although now that OpenAPI (aka Swagger) V3 is out we should think about supporting that...

**Comment by robertmclaws** [comment]
Swashbuckle already supports RESTier, so I'm closing this for now. If you experience an issue getting it working in the latest bits, please open a new issue and we will address it. Thanks!
