### ISSUE TITLE
Handling custom routes inside RestierController

### ISSUE THREAD

**Issue by rendmath** [OData/RESTier#267]
In the current version (0.4.0-rc2), implementing custom OData routes seems to be an all-or-nothing choice. Either your entity is managed by the RestierController, or you have to implement your own classic ODataController and reimplement everything that RestierController provided out-of-the-box for your entity.

In my scenario, I need to add support for manipulating a one-to-many relationship through the $ref route. I wish I could do it without losing all of the built-in behaviour brought by the RestierController.

Is it a limitation in the current version of RESTier, or only a limitation in my current understanding? The documentation mentions the topic (http://odata.github.io/RESTier/#04-27-Controllers) but does not provide an example.

**Comment by chinadragon0515** [comment]
@rendmath You can define your own controller which have actions with [ODataRoute(path)] attribute, then when we select controller and action, we will try to match this first. And for any other logic, it will still be handled by RestierController, but note that the controller name should not be starting with EntitySet name or all logic related to this entity set will be routed to this controller.

If you want to know more detail about ODataRoute attribute, refer to http://odata.github.io/WebApi/#03-03-attrribute-routing

**Comment by chinadragon0515** [comment]
We did not get a response for a while and did not expect anything to be done in RESTier, close the issue.
