### ISSUE TITLE
composite key

### ISSUE THREAD

**Issue by Josephdias92** [OData/RESTier#268]
i have a composite key userid and questionid
i dont want to pass userid as param to the delete method. user id i will get from authentication service.

[ODataRoute("QuestionLikeDislikeBy(QuestionId={QuestionId})")]
public async Task<IHttpActionResult> Delete([FromODataUri] long QuestionId)
      
if i do it this way it doesnt work. odata asks for both key ie: userid and questionid

**Comment by lewischeng-ms** [comment]
Hi @Josephdias92 according to the OData spec, each key within a composite key must be explicitly provided with a value in the URL. In your scenario, you can hard-code a default value to `UserId` when you send a request. Then in the controller action, reset the value to the one you get from the authentication service.

```
// Send request like this: ~/QuestionLikeDislikeBy(UserId=-1,QuestionId=SomeValue)
[ODataRoute("QuestionLikeDislikeBy(UserId={UserId},QuestionId={QuestionId})")]
public async Task Delete([FromODataUri] long UserId, [FromODataUri] long QuestionId)
{
    UserId = <the value from the authentication service>;
}
```

But you raised a valuable design question to us as well: can we accept incomplete composite keys by assuming the service will get the remaining values from somewhere else? We will have some internal discussion about this. Thanks!

**Comment by lewischeng-ms** [comment]
As there is no work from RESTier side, we will close the issue first. In case you have further questions, please feel free to file new issues in https://github.com/OData/WebApi/issues (if related to routing) or https://github.com/OData/odata.net/issues (if related to URI parsing). Thanks.
