### ISSUE TITLE
$metadata URL does not provide metadata when called using ODataModel of OPENUI5

### ISSUE THREAD

**Issue by JFischerCN** [OData/RESTier#274]
Given a OData implemenation, I can browse the $metadata URL successfully, but when using OPENUI5's OdataModel which polls the metadata, I got a 404. The request differs in some headers, namely:
Accept: application/xml
MaxDataServiceVersion: 3.0
Referer: <URL of hosting HTML page> 
It seems the implementation of the $metadata URL does not correctly handle either header.

**Comment by lewischeng-ms** [comment]
@JFischerCN Sorry for the late response. This seems not to be a RESTier issue because RESTier only supports OData V4. Are you using ODataLib and OData Web API for OData v3? If so, I can reroute your question to the correct place. Thanks.

**Comment by chinadragon0515** [comment]
We did not get a response for a while and did not expect anything to be done in RESTier, close the issue.
