### ISSUE TITLE
Query options order of operations 

### ISSUE THREAD

**Issue by dpim** [OData/RESTier#275]
Currently, applying count and filter returns the item count before the filter is applied. 

The filter option should first be applied and count taken afterwards.
In OData's example:
http://services.odata.org/Northwind/Northwind.svc/Customers/$count/?$filter=substringof('London', City)
Count is 6 whereas
http://services.odata.org/Northwind/Northwind.svc/Customers/$count
is 91.

**Comment by chinadragon0515** [comment]
In RestierController, GetQuery method, query options like filter should be applied when count is requested.

**Comment by chinadragon0515** [comment]
From specification: 
On success, the response body MUST contain the count of items matching the request after applying any $filter or $search system query options, formatted as a simple scalar integer value with media type text/plain.

**Comment by chinadragon0515** [comment]
Will be fixed as part of #319

**Comment by chinadragon0515** [comment]
It is fixed with #319
