### ISSUE TITLE
The given model does not contain the type 'Model.Enums.Priority'

### ISSUE THREAD

**Issue by cinaradem** [OData/RESTier#276]
hi,
Model in all Enum type exception;

{
error: {
code: "",
message: "An error has occurred.",
innererror: {
message: "The 'ObjectContent`1' type failed to serialize the response body for content type 'application/json; odata.metadata=minimal'.",
type: "System.InvalidOperationException",
stacktrace: "",
internalexception: {
message: "The given model does not contain the type 'Model.Enums.Priority'.",
type: "System.InvalidOperationException",
stacktrace: " at System.Web.OData.Formatter.Serialization.ODataSerializerContext.GetEdmType(Object instance, Type type) at System.Web.OData.Formatter.Serialization.ODataEntityTypeSerializer.CreateStructuralProperty(IEdmStructuralProperty structuralProperty, EntityInstanceContext entityInstanceContext) at System.Web.OData.Formatter.Serialization.ODataEntityTypeSerializer.CreateStructuralPropertyBag(IEnumerable`1 structuralProperties, EntityInstanceContext entityInstanceContext) at System.Web.OData.Formatter.Serialization.ODataEntityTypeSerializer.CreateEntry(SelectExpandNode selectExpandNode, EntityInstanceContext entityInstanceContext) at System.Web.OData.Formatter.Serialization.ODataEntityTypeSerializer.WriteEntry(Object graph, ODataWriter writer, ODataSerializerContext writeContext) at System.Web.OData.Formatter.Serialization.ODataEntityTypeSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext) at System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteFeed(IEnumerable enumerable, IEdmTypeReference feedType, ODataWriter writer, ODataSerializerContext writeContext) at System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext) at System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteObject(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext) at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content, HttpContentHeaders contentHeaders) at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__1b.MoveNext()"
}
}
}
}

**Comment by lucaszacutti** [comment]
any workaround?

**Comment by lewischeng-ms** [comment]
Hi @lucaszacutti We have added Enum support into RESTier and it will be shipped with the next release. If you want to have a try, you can use the nightly packages from the repo https://www.myget.org/F/restier/api/v2. Though the version is still 0.4.0-rc2, they have included the latest features. Thanks.

**Comment by lucaszacutti** [comment]
many thanks for taking time to write me. great work! Lucas

**Comment by lewischeng-ms** [comment]
@lucaszacutti You are welcome. I will close this issue for now. If you have any question regarding RESTier, please fire new issues here. Thanks.
