### ISSUE TITLE
Update RESTier dependencies breaks Trippin bound function

### ISSUE THREAD

**Issue by rayao** [OData/RESTier#277]
Unbound function/action works correctly. And it works if revert the package update to original (GitHub latest) state.
Package config file (of Trippin service) after update is this:

id="Microsoft.AspNet.OData" version="5.8.0" targetFramework="n
id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="
id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFram
id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramew
id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFra
id="Microsoft.OData.Core" version="6.14.0" targetFramework="ne
id="Microsoft.OData.Edm" version="6.14.0" targetFramework="net
id="Microsoft.Spatial" version="6.14.0" targetFramework="net45
id="Newtonsoft.Json" version="8.0.2" targetFramework="net45" /

I think it's a problem from AspNet, since the error code is 404 not found, and detail:
Module
   IIS Web Core 
Notification
   MapRequestHandler 
Handler
   StaticFile 
Error Code
   0x80070002 

Another proof is that the Trippin service is not even hit with a url like:
http://localhost:18384/api/Trippin/People(1)/Microsoft.Restier.WebApi.Test.Services.Trippin.Models.GetNumberOfFriends
If I change web.config file to cause the service unload, and hit the url above, the service won't get reloaded.

**Comment by rayao** [comment]
Unbound function/action works correctly.

**Comment by chinadragon0515** [comment]
@rayao I did test, find the version of WebAPi is 5.9 now, and also test the bound method, there is no issues.
Do you see any issues now? Or the issue can be closed now? thanks

**Comment by rayao** [comment]
Thank you for looking into, just verified it's OK now.
