### ISSUE TITLE
Consider public all RESTier serializers in Microsoft.Restier.WebApi

### ISSUE THREAD

**Issue by lewischeng-ms** [OData/RESTier#284]
There are customer needs to override some of the serializers but currently they have no way to do that.

**Comment by Dargos69** [comment]
OData WebApi [v5.6: @odata.bind not supported](https://github.com/OData/WebApi/issues/158)
a solution for should be to override some methods of the serializers
should I rebuild restier with serializers modifications or should I forget Restier or another workaround ?

**Comment by lewischeng-ms** [comment]
@Dargos69 This change will be shipped with the next release of RESTier. Thanks for your support.

**Comment by lewischeng-ms** [comment]
Done with #292
