### ISSUE TITLE
$count value not correct when $expand is used with $top

### ISSUE THREAD

**Issue by michaelwermeester** [OData/RESTier#287]
When $expand is used in a query that contains a $count=true and $top query option, then the returned count value is incorrect: 

`http://host/odata/Products?$expand=ProductType&$top=10&$count=true`
=> count = 10

The same query without $expand returns the correct count value:

`http://host/odata/Products?$top=10&$count=true`
=> count = 9939
(The count equals the total count of products.)

The count query option should ignore any $top or $expand query options and return the total count of results. (See [11.2.5.5 System Query Option $count](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#_Toc406398308) of the specification.)

**Comment by chinadragon0515** [comment]
Fixed with 7d05297fc8f2f3e9675a6588e9b532357583a7af, close the issue.

**Comment by michaelwermeester** [comment]
Thanks.
