### ISSUE TITLE
Handle projection operators in query expression

### ISSUE THREAD

**Issue by karataliu** [OData/RESTier#29]
Handle other cases: projection operators etc.

**Comment by karataliu** [comment]
This is to support type projection, currently following two are supported:
// Source is a sequence of T and output is also a sequence of T
// Source is a sequence of T and output is a single T


Related to the imperative view issue

https://github.com/OData/RESTier/issues/72

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
