### ISSUE TITLE
Replace SomeHookHandler.Instance with singleton-lifetime services in DI

### ISSUE THREAD

**Issue by lewischeng-ms** [OData/RESTier#290]
such as `DefaultQueryExecutor.Instance`. Since now we have DI, there is no need to maintain so many static singleton instances in various hook handlers, consider replace them with singleton-lifetime services in DI.

**Comment by rayao** [comment]
In that way every ApiConfiguration will have its dedicated instance of the service type. Make the type not really singleton in an AppDomain. Although I don't think that's a problem, just to mark the difference.

**Comment by lewischeng-ms** [comment]
Oh, I see. So this means if we have multiple `Api` types in a service, we will have multiple "singleton" instances of a built-in hook handler?

**Comment by rayao** [comment]
Exactly.

**Comment by lewischeng-ms** [comment]
Great! Actually this is the expected behavior for RESTier because some hook handler MAY have an internal cache which stores the API-specific information. Sharing across APIs causes problems on the contrary.

**Comment by rayao** [comment]
I'll take this if nobody has already started.

**Comment by lewischeng-ms** [comment]
Sure. Much appreciate your help!
