### ISSUE TITLE
Should we enforce contextual service scope?mode

### ISSUE THREAD

**Issue by rayao** [OData/RESTier#298]
Currently an Api class could choose between shared and contextual service scope, that makes it impossible to unleash the power of DI, especially stateful service. Maybe we'd enforce the contextual service scope.
For example, if a contextual scope is assured, we can register DbContext as a service, in DbApi.

**Comment by rayao** [comment]
Another question is what the exact scope is.
We could create service scope at ApiContext level, or we could create it at InvocationContext level.
IMHO if we don't expect 2 or more invocations run simultaneously on a same ApiContext, we'd choose ApiContext level, otherwise invocation level is prefered.

**Comment by rayao** [comment]
If we enforce contextual service scope, role based security could be easily implemented as several scoped services, make all those states (now in PropertyBag) data members.

**Comment by lewischeng-ms** [comment]
I agree with you. It's too heavy to create the scope at InvocationContext...because during the lifetime of a single request, several InvocationContext of different derived types would be created. ApiContext level would be very proper.

**Comment by rayao** [comment]
Working on this.

**Comment by rayao** [comment]
Resolved with e88304b1eaefa353c292b68cbc3ea8666ab6eccb
