### ISSUE TITLE
Comparison to Breeze

### ISSUE THREAD

**Issue by pisees** [OData/RESTier#299]
Hi,

How would you compare RESTier to Breeze (http://www.getbreezenow.com/)?

Thanks,

**Comment by rayao** [comment]
Just had a look, it seems to me these 2 libs are very similar in basic functionality. Breeze has a powerful client library that is supposed to ease the invocation to any WebApi/OData services. Well for RESTier, to my knowledge a major design purpose is to provide an extension framework that could easily expose a data source as an OData service and could easily customize/enhance the service.with either predefined or user defined hook handlers.

**Comment by chinadragon0515** [comment]
I did some compare of this, and here is what I see now, 
1. Breeze is not a single project, it has several projects includes 2 client (JS and c#) and 4 servers (ASP .NET, Java, Node MongoDB,Node Sequelize). Compare will focus on the server side.

2. Both can accept query, build LINQ query and submit to database, this is similar.

3. Both build model (metadata from EF CLR class), this is similar.

4. Restier allow user to inject more besides EF has like new EntitySet based on existing EntitySet, Action/Functions and so on. Also auto build model for these actions/functions.

5. Restier allows user not using EF, and have own class for LINQ query submit to support more data sources.

6. Restier has its own serializer/deserialier, serialize data based on OData standards and supports all OData annotation.

**Comment by chinadragon0515** [comment]
As no additional code work for RESTier related to this issue now, close the issue.
