### ISSUE TITLE
Full test on null values for both structural and navigation properties

### ISSUE THREAD

**Issue by lewischeng-ms** [OData/RESTier#305]
~/.../entity [/complexProp] [/collectionProp]
~/.../prop
~/.../prop/$value
~/.../navigationProp

**Comment by chinadragon0515** [comment]
Issue founded: 
	1. Incorrect path  like collection/$valuewill return 404 but not 400 (badrequest), this is handled by WebApi
	2. Null single value will return 200 but not 204
	3. Null complex and request complex property will have 500 (NullReferenceException )
	4. Null single navigation request will return 500

Issues which are not fixed yet
	1. Incorrect path like collection/$value will return 404 but not 400 (badrequest), this is handled by WebApi. Tracked with https://github.com/OData/WebApi/issues/683
	2. Request single navigation property with null value return 404 now as cannot differentiate ~/People(nonexistkey)  (404) vs /People(5)/NullSingNav (204) now. Tracked with Issue #288
	3. Request with non-existing entity's prop will return 204 /200, should be 404. Tracked with Issue #328 
	4. Null collection is not handled yet, if collection is null, 500 will be returned (EF only allow navigation collection). Tracked with Issue #330

Issues fixed with this issue:
	1. For single value of primitive/complex/enum, will return 204 now (was 200)
	2. For request single navigation property or its property will return 404 (was 500)
For request of complex property and complex is null, will return based on prop (204 or 200), but not 500.

**Comment by chinadragon0515** [comment]
It is merged, close the issue
