### ISSUE TITLE
Discussion: Should be run count query independently?

### ISSUE THREAD

**Issue by rayao** [OData/RESTier#319]
IMHO the reason that current query pipeline includes a totalcount in result, is purely for corresponding to OData/WebApi query options. But the query pipeline should/could and actually is decoupled from OData, such correspondent is unnecessary and when present (as for now), brings about unnecessary complexity to RESTier core.
The core has to reverse engineering the expression to get a count query, this reverse engineering process actually assumes the query is from AspNet.WebApi. That hurts the cohesion of RESTier core.
By separating count query at publisher layer, the simplicity of core is ensured, and publisher still keeps the flexibility.

**Comment by rayao** [comment]
Of course, the price is a little perf hit for running 1 more query.

**Comment by rayao** [comment]
#320 is a proof implementation, not for checking in, just show the way to do.

**Comment by chinadragon0515** [comment]
@rayao I had a discussion with Lewis on this, consider provider is data source which just accept query and return result, protocol related logic is not part of provider but part of publisher which handles request for different protocol.
Also current logic already have two queries when there is a count query option. We think publisher is right place to handle this.
Will you help to merge this changes or you want me to merge this changes? 

The other question is whether we handle another issue #275  which related to $count segment here?

**Comment by rayao** [comment]
Thank you guys! Really glad to know you approved. :)
I'm happy to make further changes base on the proto PR and let you review. Of course if for any reason you want to take it I'm also completely ok with that.
If the change for #275 in this PR is OK for you, I'm also happy to fix it.
All up to you. :)

**Comment by chinadragon0515** [comment]
Thanks for your help, when I will mark #275 is fixed by this pull request. thanks.

**Comment by chinadragon0515** [comment]
This is merged, close the issue.
