### ISSUE TITLE
Could not load type 'Microsoft.OData.Core.UriParser.Extensions.Semantic.ApplyClause

### ISSUE THREAD

**Issue by kachalkov** [OData/RESTier#342]
Hi guys,

Trying adopt restier 0.4.0-rc2. After huge efforts of migrating we are facing issue with Patch throwing null reference exception. Tried update to 0.5.0-beta, but it does not seem to work at all as now we are getting error about:

'Could not load type 'Microsoft.OData.Core.UriParser.Extensions.Semantic.ApplyClause' from assembly 'Microsoft.OData.Core, Version=6.15.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content, HttpContentHeaders contentHeaders)

**Comment by VikingsFan** [comment]
@kachalkov because Restier 0.5.0-beta are reference WebAPI/OData 5.9.0-beta, which can't work with OData.net 6.15.0 refer to this issue: https://github.com/OData/WebApi/issues/687, WebAPI will release soon, the problem will go away, or you can use OData.net 6.15.0-beta to get Restier 0.5.0 work.

**Comment by kachalkov** [comment]
@VikingsFan thank you for quick response and workaround. great job.

**Comment by chinadragon0515** [comment]
As there is no code change in RESTier, and there is an WebApi issue opened to track this, so close this issue.
