### ISSUE TITLE
Any way to expose enum properties as strings and pluralisation setting

### ISSUE THREAD

**Issue by kachalkov** [OData/RESTier#343]
great library guys! love domain controller idea!

hi, we are having issues as odata connected service does not support re-use of existing enum types and this is causing casting or parsing db enum type to client proxy enum type.

are there any way to configure this?

another question about pluralisation and if that is also can be configured?

**Comment by lewischeng-ms** [comment]
Hi @kachalkov is your question based on the client side or the server side? From the server side, if you are using Entity Framework as the data proxy to access the database, enum types are currently not supported by it now. If this is a client side question, I can help reroute your question.

**Comment by kachalkov** [comment]
I was under impression that enum support was added in version 0.5.0-beta?

We had it almost working, but had issue with other 6.15 not having ApplyClause

**Comment by lewischeng-ms** [comment]
Oh sorry...my mistake. Enum is supported by both EF and RESTier. So could you please explain your problem with more details or examples? I don't quite understand about "does not support re-use of existing enum types and this is causing casting or parsing db enum type to client proxy enum type". Are those existing enum types different from those in db? By the way, ApplyClause is already in 6.15-beta, what problems are you encountering?

**Comment by kachalkov** [comment]
Well, when we generate proxy using OData Connected Services because Restier
exposes enum information it generates client side enum classes which are
different to the ones we use already in solution and this creates problem
as we have to cast one enum type to proxy ones, I already raised this
question for OData Lab team in regards to OData Connected Service, I guess
we can just check type of the property and replace type with string...

**Comment by lewischeng-ms** [comment]
I see. Then maybe you will have to modify the type resolver code in the client code generator text template (a .tt file) to correctly find the enum types in the service namespace. You can do this by choosing to add the text template to your project as well when using the OData Connected Service. Upon how to modify the type resolver code in that template, we can offer you more detail if you need that. Thanks.

**Comment by kachalkov** [comment]
Thx!

**Comment by lewischeng-ms** [comment]
Since there is no work from RESTier side, we will close this issue first. If you have further questions, please feel free to reopen it. Thanks.
