### ISSUE TITLE
Could not load type Microsoft.OData.Core.UriParser.Aggregation.AggregationMethod' from assembly 'Microsoft.OData.Core, Version=6.15.0.0,  Microsoft.OData.Core.UriParser.Aggregation.AggregationMethod

### ISSUE THREAD

**Issue by kachalkov** [OData/RESTier#344]
Everything is almost working except for this one, please help.

Using 6.15-beta as suggested in other issue

**Comment by VikingsFan** [comment]
Hi @kachalkov but error message show your are using odata.net 6.15 not 6.15-beta.

**Comment by kachalkov** [comment]
well, does not seem to have that in actuall version:

Dev\packages\Microsoft.OData.Edm.6.15.0-beta\lib\portable-net40+sl5+wp8+win8+wpa\Microsoft.OData.Edm.dll

**Comment by VikingsFan** [comment]
can you try uninstall OData and install 6.15.0-beta? or WebAPI/OData is releasing in these two days, update that to 5.9 rtm will fix this issue.

**Comment by kachalkov** [comment]
OData.Core?

**Comment by VikingsFan** [comment]
yes, the issue is there are some namespace changing in OData.Core from 6.15.0 beta to rtm, WebAPI/OData 5.9 beta are referencing OData.Core 6.15.0 beta, so after you update OData.Core, it breaks.

**Comment by kachalkov** [comment]
thanks it worked!
as a feedback would be nice to have dependency for Restier.Web on other required libraries.

any ATA to release version of Restier so we can sell it to management as a replacement.

strange that FirstOrDefault is still not supported?

**Comment by kachalkov** [comment]
Looks like that was actually related to EFCache extension method .NotCached()

**Comment by chinadragon0515** [comment]
There is no work for RESTier of this issue, close the issue.
