### ISSUE TITLE
Custom Formatter is being ignored

### ISSUE THREAD

**Issue by danroot** [OData/RESTier#346]
I have written a custom formatter, CsvFormatter, to use content negotiation to allow me to export query results as CSV and open in excel, etc.  

In CsvFormatter, I register the mime type and format:
     `      this.SupportedMediaTypes.Add(new MediaTypeHeaderValue("text/csv"));
            this.MediaTypeMappings.Add(new QueryStringMapping("$format", "csv", "text/csv"));`

And handle the response:
  `  public override bool CanWriteType(Type type)
        {
            return true;// serializer.CanSerialize(type);
        }
        public override void WriteToStream(Type type, object value, Stream writeStream, HttpContent content)
        {
            serializer.Serialize(type, value, writeStream);
        }
`

in WebApiConfig, I have: 
  `  config.Formatters.Add(new CsvFormatter()); `

This code works well in another Web API Odata application, but not in RESTier.  I have confirmed the client (Postman) is sending Accept:text/csv, and have tested with $format=csv, but breakpoints inside CsvFormatter show WriteToStream and CanWriteType are not being called.  I suspect RESTier is using it's own JSON formatters for all requests and not allowing for any others.  

I tried following the code to find exactly where this could be happening so I could submit a pull request, but wasn't sure.  

Can somebody either let me know where in the RESTier code I should be looking to fix this OR tell me where I'm going wrong in my approach to add custom formatters to handle the Accept header.

**Comment by chinadragon0515** [comment]
To handle the response, you need to override this method "public override Task WriteToStreamAsync(Type type, object value, Stream writeStream, HttpContent content,  TransportContext transportContext, CancellationToken cancellationToken)"

I verify in RESTier newest code base, and should be same for version 0.4. I also verify WebApi version 5.9, it needs to override this method too. 

Let us know if you have any more questions.

**Comment by danroot** [comment]
That got it.  The formatter I was using implemented WriteToStream on BufferedMediaTypeFormatter, but did not implement WriteToStreamAsync.  It must have been for a previous version of WebApi.  I've confirmed overriding the WriteToStreamAsync methods and registering the formatter works as expected.  Thanks!
