### ISSUE TITLE
Support override convention-based API services

### ISSUE THREAD

**Issue by lewischeng-ms** [OData/RESTier#352]
Linked to an old issue #219 .

Ray's PR #339 and issue #332 already proposed a solution for that: support adding your API service to outermost to have a full control of whether to apply the convention.

Other possible options are:
 - Change back conventions to `EnableConventionsAttribute` but that requires an additional API class.
 - Add an API like `DisableConvention<TService>()` to disable a certain convention-based API service.

**Comment by lewischeng-ms** [comment]
Related PR #353

**Comment by chinadragon0515** [comment]
With PR #368 , user can override configureApi method, and decide whether to call AddConversionBasedServices method to enable Conversion based services, close this issue.
