### ISSUE TITLE
Error with EF7 build

### ISSUE THREAD

**Issue by a2dude** [OData/RESTier#358]
I get the following error when building the latest EF7 sln / EF6 is fine

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'QueryExpressionFilter' could not be found (are you missing a using directive or an assembly reference?)	Microsoft.Restier.EntityFramework7	C:\WIP\Projects\OData\R2\Github\Restier\EF7\src\Microsoft.Restier.EntityFramework\DbApi.cs	67	Active

**Comment by rayao** [comment]
Wow you're so quick! I've fix local, thinking no one will need it so have not checked in yet.

**Comment by rayao** [comment]
Done. Beware that if you do a clean build Northwind UTs for EF7 will likely break.

**Comment by a2dude** [comment]
Ok.  Will focus on EF6 for now.  

Thanks for the speedy response.
