### ISSUE TITLE
Complete ModelProducer functionality

### ISSUE THREAD

**Issue by karataliu** [OData/RESTier#36]
1. Support complex and enumeration types
2. Support function imports
3. Support complex and entity inheritance

**Comment by rayao** [comment]
Also for EF7 provider

**Comment by karataliu** [comment]
When there's enum type in model currently, NRE would be reported:

ModelProducer.cs
ModelProducer::GetPrimitiveTypeReference
var efKind = efProperty.PrimitiveType.PrimitiveTypeKind;

since PrimitiveType is null for enum type.
