### ISSUE TITLE
Support $apply in RESTier

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#360]
Validate $apply support in RESTier, and add related test cases, if no support, then figure out detail cause and issues.

**Comment by danroot** [comment]
I'd like to see this also.  GroupBy and distinct would be nice to have.  http://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/csprd02/odata-data-aggregation-ext-v4.0-csprd02.html#_Toc378326329

**Comment by chinadragon0515** [comment]
@danroot  thanks. If you have other features request related to RESTier which are not supported in RESTier, you can open issue directly.

**Comment by VikingsFan** [comment]
Relative issue https://github.com/OData/WebApi/issues/726

**Comment by chinadragon0515** [comment]
@VikingsFan Can this be closed? thanks

**Comment by chinadragon0515** [comment]
document is updated, just add support of $apply, close the issue.
