### ISSUE TITLE
Support for additional path segments in function invocations?

### ISSUE THREAD

**Issue by ivanko2000** [OData/RESTier#365]
As far as I can tell the OData standard does not say anything about this, so likely a non-starter, but since I ran into this today, raising a question in case it's easy to implement...

There is support for raw value retrieval for entity properties, e.g. /Products(1)/Name/$value 

There is support for functions, e.g. /Products(1)/GetSomeStringDescribingThisThing

The function is represented in metadata with e.g. <ReturnType Type="Edm.String" Nullable="false" />
and returns content similar to this:
{ "@odata.context":"http://localhost/my/api/$metadata#Edm.String","value":"SomeString" }

However, there is no option to do:
/Products(1)/GetSomeStringDescribingThisThing/$value
to get the raw value.

To repeat, it does not appear to be part of the standard, and it's of'course easy to extract the value from JSON content.

But IF it is possible to tap into the same facilities in the code that handle entity property raw values and add automatic routes for such functions without much developer effort, why not?

Thank you for your time.

**Comment by chinadragon0515** [comment]
To  support this,
1. Need ODL lib to parse the URL
2. Need serializer in ODL/WebAPi to support.

Both ODL and WebAPi has critical items ongoing and this will not be considered for next several months, move to backlog.

In the meanwhile, working with specification team to see whether this can be considered as part of specification.

**Comment by chinadragon0515** [comment]
After more check, specification already support this, refer to http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/abnf/odata-abnf-construction-rules.txt

boundOperation = "/" ( boundActionCall
                     / boundEntityColFuncCall    [ collectionNavigation ] 
                     / boundEntityFuncCall       [ singleNavigation ] 
                     / boundComplexColFuncCall   [ "/" qualifiedComplexTypeName ] [ collectionPath ] 
                     / boundComplexFuncCall      [ complexPath ]
                     / boundPrimitiveColFuncCall [ collectionPath ] 
                     / boundPrimitiveFuncCall    [ singlePath ] 
                     )
singlePath     = value / boundOperation
value = '/$value'

Will do more check on this part.

**Comment by chinadragon0515** [comment]
ODL parser is not supported yet. refer to https://github.com/OData/odata.net/issues/539

**Comment by mikepizzo** [comment]
Yes; supporting additional path segments following a function invocation is supported in the protocol, but not (yet) in the libraries.

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
