### ISSUE TITLE
Authentication: "endpoint-wide" [Authorize], access to the current Principal ?

### ISSUE THREAD

**Issue by ivanko2000** [OData/RESTier#366]
This is a question; the answer might be obvious, but not to me, since I am a newbie...

I am experimenting with securing the RESTier endpoint with something as simple as Basic Authentication (e.g. using WebApi2 IAuthenticationFilter) and applying a simple filter to an entity set based on the authenticated user (Principal), with little success:

* It is not clear how to apply auth enforcement for the whole OData/RESTier endpoint; [Authorize] attribute on e.g. the ODataController-derived controller works, but obviously only on the 'features' / fallbacks defined there, e.g. Functions/Actions

* it's also not clear how to access the request context containing the Principal / Identity of the authenticated user, e.g. in the DbApi<...>::OnFilter[EntitySet]()...

I would appreciate any advice or clarification.

**Comment by rayao** [comment]
Does Thread.CurrentPrinciple work?

**Comment by ivanko2000** [comment]
Thread.CurrentPrincipal does indeed work. Thank you!

Found a solution for the second part of my question as well [WebApiConfig.Register: config.Filters.Add(new AuthorizeAttribute());]
