### ISSUE TITLE
Unable to expose an entity subset using post-db-query collection filtering

### ISSUE THREAD

**Issue by ivanko2000** [OData/RESTier#367]
I reviewed the available Help topics but could not find an explanation of whether this is possible.

I have the following "filter" defined in DbApi-derived class:

        public IQueryable<Entity> MySubset
        {
            get { [see below] }
        }

If (in place of "[see below]") I use:
`        return this.Source<Entity>("Entities").Where(...)
`
it works fine until I try to actually run the query, i.e. to post-process the DB query results with a "client-side" query (as the operations I need are not translatable to SQL), e.g.:
`        return this.Source<Entity>("Entities").Where(...).ToList().Where(...).AsQueryable()
`
Which the query processor does not understand.

If I skip the Source<>() wrapper, e.g. with something as simple as this:
`        return Context.Entities;
`
RESTier fails with:

> "message":"Object reference not set to an instance of an object.","type":"System.NullReferenceException","stacktrace":"   at Microsoft.Restier.Core.Query.DefaultQueryHandler.<QueryAsync>d__0.MoveNext()

so I am assuming this is not supported... although not sure why.

Is there a reasonable way to apply such post-DB-query collection processing in this use case?

**Comment by rayao** [comment]
Properties in DbApi classes are part of "data provider", you can't actually enumerate Source<T>, since it is only for expression building.
Client side query can only be applied out of RESTier pipeline, e.g. `myApiType.Context.Query(...).ToList()`

**Comment by chinadragon0515** [comment]
@ivanko2000  let us know whether Ray has answered your questions, if yes, help to close the issue, thanks.

**Comment by ivanko2000** [comment]
The explanation does answer my question, at least the way I formulated it. I still have a problem I am trying to resolve, but I will reformulate it and file as a separate issue, if necessary.

Thank you for the explanation, closing the issue.
