### ISSUE TITLE
Support tracking entities

### ISSUE THREAD

**Issue by karataliu** [OData/RESTier#37]
1. QueryExpressionSourcer::Source
   When there is a real domain entity manager, the underlying DbContext shouldn't track the entities.
2. ChangeSet::AnEntityHasChanged
   make the ChangeSet 'dynamic' so it gets added to as things change during the flow

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
