### ISSUE TITLE
DateTime broken? now unconditionally maps to Edm.Date

### ISSUE THREAD

**Issue by ivanko2000** [OData/RESTier#375]
I've reviewed all the issue reports on the datetime and temporal types in general.
My understanding is that a property defined as
```
        [Column(TypeName = "DateTime")] // or with .HasColumnType("DateTime")
        public DateTime? Modified { get; set; }
```
should be mapped to Edm.DateTime (or maybe Edm.DateTimeOffset, #281)

However, in my case, whatever I do, I get
`<Property Name="Modified" Type="Edm.Date"/>
`
and hence values are returned as date only...
Am I doing it wrong? Seems like a bug.
RESTier and all other libraries/packages are up to date in my project.

**Comment by chinadragon0515** [comment]
@ivanko2000 When you said up to date, do you mean newest nuget package? Do you build package by yourself with newest code?
The newest package in nuget (0.4.0-rc2) has no included this feature yet, we are working to release a newer version to nuget now.

I test with newest code ( you can download the source code and running project Microsoft.Restier.WebApi.Test.Services.Trippin, then check Person metadata), there is no issue.
I also check our code, https://github.com/OData/RESTier/blob/master/src/Microsoft.Restier.EntityFramework/Model/ModelProducer.cs, the logic has no issue.

**Comment by ivanko2000** [comment]
You are right - I meant the NuGet package, not the latest code base. I'll test that one later today, but it sounds like it should work there. Thank you.

**Comment by peder** [comment]
@chinadragon0515 what is the timeline for the next NuGet package update?

**Comment by chinadragon0515** [comment]
@peder I hope I can get it published second or third week of May, but note this is not a commitment.

**Comment by peder** [comment]
@chinadragon0515 of course, not expecting a firm commitment--I was just hoping for something directional. In the meantime, I might look at pulling the latest version of the source and building manually. Thanks for the update.

**Comment by chinadragon0515** [comment]
@ivanko2000 I close the issue as it is already fixed in newest code. If you have any issues, let me know. thanks.
