### ISSUE TITLE
[IgnoreDataMember] not honored?

### ISSUE THREAD

**Issue by ivanko2000** [OData/RESTier#382]
I might be missing something obvious, but shouldn't the [IgnoreDataMember] attribute be honored through RESTier (for OData payload serialization), similarly to how it applies for Web Api OData?
I tried to apply it to an entity property, yet it's still returned when the entities are queried...

For details, see:

http://www.asp.net/web-api/overview/odata-support-in-aspnet-web-api/odata-security-guidance

http://stackoverflow.com/questions/27781607/exclude-property-from-webapi-odata-ef-response-in-c-sharp

**Comment by chinadragon0515** [comment]
RESTier and WebApi uses different methods to build model now, so attribute like [IgnoreDataMember]  (legacy) or [NotMapped] (new) defined by WebApi is not used by RESTier now.

We do have a plan to make the model building methodology same later this year.

For now, there is a workaround for you to use WebApi model builder for entity set and entity type, but use RESTier model builder for operation, you can refer to http://odata.github.io/RESTier/#04-03-Api-Service for more detail.

And here are general steps,

1. Create your own ModelBuilder, and does not define a property "public IModelBuilder InnerBuilder { get; set; }"
2. Use WebApi to builder model which recognize the attribute you need.
refer to http://odata.github.io/WebApi/#02-04-convention-model-builder for more detail on how to use it.
3. Register your customized model builder into RESTier like "services.CutoffPrevious<IModelBuilder, MyModelBuilder>();", and note here use Cutoff but not chain to ignore the RESTier entity type and entityset model builder.

Then you should get everything you need.

If you want to use WebAPi model builder for all model includes operations, then you can refer to section 2.4 of document, register after call base.ConfigureApi, and use Cutoff too.

And note these functions are for release 0.5.0 which we plan to release in coming weeks, but no guarantee.

**Comment by chinadragon0515** [comment]
@ivanko2000 can I know whether you need more help or have other issues, if not, help to close the issue.

**Comment by ivanko2000** [comment]
@chinadragon0515, thank you for the clarification.

Since this workaround requires pre-release code base, I was hesitant to depend on it (close to our team's release of a component using RESTier), so I worked around with inferior and ad hoc'ky but predictable approach (removing the property from the model entirely and querying the corresponding DB field directly). 

The resolution of #383 appears to be the preferred solution here, providing out-of-the-box support for this and other such attributes, so I am looking forward to its resolution.

Please close this issue report as you see fit [although it would be a good test case to confirm completion of #383].

**Comment by chinadragon0515** [comment]
I added comments for #383 , and close this issue now, thanks.
