### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by lgadola** [OData/RESTier#387]
I get an Exception when calling a simple API function which should return an EntitySet

### Assemblies affected
RESTier 0.4.0-rc2.*  

### Reproduce steps
create simple api function:
`        public IQueryable<Staff> AllStaff
        {
            get { return DbContext.Staffs; }
        }`

### Expected result
return same result as when qerying Staff

### Actual result
Object reference not set to an instance of an object.","type":"System.NullReferenceException","stacktrace":"   at Microsoft.Restier.Core.Query.DefaultQueryHandler.<QueryAsync>d__0.MoveNext()

**Comment by chinadragon0515** [comment]
@lgadola  this is fixed in version 0.5 which we plan to release in coming weeks, can you wait and then try version 0.5? 

If you have no more issues, I will close this issue as we only have fix for new release.

**Comment by lgadola** [comment]
ok I will try version 0.5
thanks
