### ISSUE TITLE
Make permission filter method (Start with Can) to have parameter of ChangeSetItem

### ISSUE THREAD

**Issue by johnlittle2000** [OData/RESTier#389]
OnUpdatingEntitySetName gives me access to the entity to apply custom validation logic, based on the values in the entity, but it gives no way to cancel the update or return a custom error.

In the common case where the business rule is, I can update my data but not your data CanUpdateEntitySetName does not give me sufficient granularity, because I can not access the entity data.    

So a malicious user with CanUpdateEntitySetName permission can modify an entity, I can see the modification with custom validation logic, but not cancel the update. 

I understand that I can drop back to an OData controller, but that defeats the purpose of RESTier. Having written controller per entity code, RESTier could reduce the code I have to write by an order of magnitude, but the inability to cancel an update means I have to stay with WebApi OData.

**Comment by chinadragon0515** [comment]
@johnlittle2000 there are two ways a update will be stopped based on what you need,

1. If you want to do something like authorization, then you can write a class which implements IChangeSetEntryAuthorizer interface,  and then register it as the out most service like

base.ConfigureApi(services);
services.ChainPrevious<IChangeSetEntryAuthorizer, CustomizedAuthorizer>();

In class CustomizedAuthorizer, you can implement your own logic for authorization, and if you want to call RESTier defined authorization logic, you can define a property whose type is IChangeSetEntryAuthorizer like "private IChangeSetEntryAuthorizer Inner { get; set; }", then call Inner method for RESTier logic.

Also we do think to make method like CanUpdateEntitySet to have entity instance as parameter.

In this way, you will get 403 (forbidden) if user can not update the entity.

2. If you want some customized logic for update, you can implement a class implements interface IChangeSetEntryValidator,  validate in any logic you want, and then add logic like 

            DataModificationEntry dataModificationEntry = entry as DataModificationEntry;
            var entity = dataModificationEntry.Entity;

             // Customized validate logic and if error, add a error validation result.
            validationResults.Add(new ChangeSetValidationResult()
            {
                Id = dataModificationEntry.EntitySetName+ dataModificationEntry.EntityKey,
                Message = "Customized error",
                Severity = ChangeSetValidationSeverity.Error,
                Target = entity
            });

Also you can decide to call inner or not in the same way as above, in this way, if validation fails, user will get error 400 (bad request).

Let me know if this works for you.

If this works for you, I will use this issue to make CanUpdateEntitySet to have parameters and add documents for these logic.

**Comment by johnlittle2000** [comment]
Yes, this works for me, thanks.

But it would need to be consistent, 
inserts require authorization and validation,
updates require authorization and validation,
deletes only require authorization.

CanInsertEntitySetName(Model model) 
CanUpdateEntitySetName(Model model)
CanDeleteEntitySetName(Model model)

Also to make it simple for me consider changing the return type from boolean to HttpResponseMessage.

```
public HttpResponseMessage CanUpdateEntitySetName(Model model)
{
   // custom validation logic
    if (!valid)
    {
        return request.CreateResponse(HttpStatusCode.BadRequest, "Customized error");
    }
    return request.CreateResponse(HttpStatusCode.OK, "");
}
```

**Comment by chinadragon0515** [comment]
@johnlittle2000 
1. we will validate this to make logic been consistent.
2. for update put and patch, we adopt same logic.
3. For return value, canUpdateEntitySet and so on is related to permission check as user defined in APi class, we only how 403 been returned, and if permission allowed, rest processing is continuing.
If we return value here, then user will need to write lots of logic if he really wants to update the entity.

**Comment by johnlittle2000** [comment]
That's good.

BTW I made a mistake in the example CanDeleteEntitySetName(int Id) the parameter type could be any type like long or string.

**Comment by chinadragon0515** [comment]
A preview of document can be accessed via http://chinadragon0515.github.io/RESTier/#02-09-Customize-Submit. Let us know if there is any comments.

**Comment by cilerler** [comment]
Hi,

I just want to make sure you received my comment

REF:  https://github.com/OData/RESTier/issues/392#event-653987607

I couldn't be able to find anything related to IChangeSetItem*
https://github.com/OData/RESTier/search?utf8=%E2%9C%93&q=+IChangeSetItem

I believe you meant

   - IChangeSetEntryAuthorizer <= IChangeSetItemAuthorizer
   - IChangeSetEntryFilter
   - IChangeSetEntryValidator <= IChangeSetItemValidator
   - IChangeSetPreparer <= IChangeSetItemProcessor
   - ISubmitExecutor.cs

If that's the case you may want to update documents

**Comment by johnlittle2000** [comment]
I can not find IChangeSetItemValidator in the repository, do you mean IChangeSetEntryValidator?

**Comment by chinadragon0515** [comment]
IChangeSetEntryValidator is changed to IChangeSetItemValidator  with pull request #391  which I plan to merge these two days, but note our public API review is not completed yet, more changes will be merged especially the namespace will be changed.

After these changed, we will release 0.5-beta (no 0.5 release, we must include beta in release name as one depended package we used is rc version, we can not just release without beta).

**Comment by johnlittle2000** [comment]
Understood, this works for me.

Are tests available?

First sentence in doco the word conversion should be convention.

**Comment by cilerler** [comment]
@johnlittle2000 you may find sample in here https://github.com/OData/RESTier/issues/394

**Comment by chinadragon0515** [comment]
@johnlittle2000 thanks for the typo, I just fix it, and we also accept pull request for fix of code and documents.

For the test part, you can refer to @cilerler 's one first, I focus on 0.5 release now, and after 0.5 is release, I plan to add some examples into our end to end examples. We also accept pull request to add examples.

**Comment by lostmsu** [comment]
@chinadragon0515 Is there a sample for this? I am looking for a way to only allow user (having his ID from auth layer) modify his own notes (which has ownerId field).

**Comment by chinadragon0515** [comment]
@lostmsu we do not have an end to end sample for this now, for now, you can customize the authorize logic and document is in link http://odata.github.io/RESTier/#02-09-Customize-Submit

For getting user information from context, we have not tested end to end yet and we assume it is same as what Web Api does.  We do plan to add an end to end sample with issue https://github.com/OData/RESTier/issues/403

Is this does not meeting your requirements, can you open new issue to track your detail requirements? thanks.
