### ISSUE TITLE
Complete ModelMapper Functionality

### ISSUE THREAD

**Issue by karataliu** [OData/RESTier#39]
Support composable function imports, etc. for Model Mapper.

**Comment by lewischeng-ms** [comment]
Do with #120

**Comment by mfergusonPM9** [comment]
Any update here? :) This feature would be a big help esp. re: automatic function imports.

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
