### ISSUE TITLE
Global method for "Plug-in user logic"

### ISSUE THREAD

**Issue by cilerler** [OData/RESTier#392]
If application needs to log every single **Insert|Update|Delete|Execute** action for all the **Entities|Actions**, it requires us to setup each one of them separately which causes excessive usage of the feature and unnecessary code repeats.

It would be beneficial to have `On<Insert|Updat|Delet|Execut><ed|ing>Global` where **ing** for before submit and **ed** for after submit which should provide us name of the `<EntitySetName|ActionName>` has been triggered.

> According to [here](http://odata.github.io/RESTier/#plug-in-user-logic) RESTier supports `On<Insert|Updat|Delet|Execut><ed|ing><EntitySetName|ActionName>` where **ing** for before submit and **ed** for after submit.

**Comment by chinadragon0515** [comment]
This is already supported with 0.5, docs will be added,  and the steps is,

1. Create a customized class which implements IChangeSetItemProcessor (previously was IChangeSetItemFilter), and implement two methods one for before submit and the other for after submit for all change set item.

2. Registered it as Dependency Injection service in RESTIer, 

register it as the out most service like
base.ConfigureApi(services);
services.AddService<IChangeSetItemProcessor ,CustomizedProcessor>();

If you want to call RESTier logic, defined a property in your class with type IChangeSetItemProcessor , like "private IChangeSetItemProcessor  Inner {get; set}"

Then call Inner method to call RESTier logic.

**Comment by chinadragon0515** [comment]
A preview of document can be accessed via http://chinadragon0515.github.io/RESTier/#02-09-Customize-Submit. Let us know if there is any comments.

**Comment by chinadragon0515** [comment]
Doc added, close the issue.

And note 0.5 is not released yet, we are reviewing public API, after that part is closed, we will release 0.5.

**Comment by cilerler** [comment]
I couldn't be able to find anything related to **IChangeSetItem*** https://github.com/OData/RESTier/search?utf8=%E2%9C%93&q=+IChangeSetItem Are you sure that those are in RESTier?
