### ISSUE TITLE
Microsoft.Restier.WebApi.Post returned message contains null instead of an empty collection.

### ISSUE THREAD

**Issue by CzPete** [OData/RESTier#393]
In RESTier 0.4.0, when calling public Task<IHttpActionResult> Post(EdmEntityObject edmEntityObject, CancellationToken cancellationToken) with an empty body, returned message.Content.Value contains a dictionary of empty/default values. Collections (many-to-many or many-to-one navigation properties) should have an empty-collection value. They have a value of <null> instead.

### Assemblies affected
RESTier 0.4.0

### Reproduce steps
1. Create an EDM model with many-to-many (or one-to-many) navigation property, say "Color" of type "List<MyNamespace.ColorChoice>".
2. Create an empty record; i.e. call Post with an empty payload
3. Check (message.Content as aliasedNetHttp.ObjectContent).Value

### Expected result
Property "Color" is of type System.Collections.Generic.ICollection<MyNamespace.ColorChoice> and the value is [].

### Actual result
Property "Color" is of type System.Collections.Generic.ICollection<MyNamespace.ColorChoice> and the value is null.

**Comment by chinadragon0515** [comment]
I did some testing,

I have person who has collection of Friends and Trips, I made collection has default null value, and have a post, the return result does not contain Friends and Trips, this is as expected as navigation properties is not returned by default.
Then I use get method with expand, I can get Friends and Trips with empty value.

So my questions for your,
1. I see you use color as example, it is navigation property but not enum type or other collection type (EF only supports collection of navigation now), is it right?
2. During creation, when you see collection value is null, is it before response is serialized or after response is serialized? Do you check the output of post request from tools like fidder?
3. We do not write response with navigation properties, can I know whether you overwrite some code to achieve this? If yes, can I know you have overwrite? thanks

**Comment by CzPete** [comment]
Hi Vincent,

I talked to Daniel a bit and it seems that the real issue is the serializer that we use. Before serialization, I get the whole object with nulls for collection of nav properties. After the serialization, the OData serializer does the right thing, i.e. replaces the null with empty collections. However, our RealTime serializer does not do the right thing and that is the cause of trouble.

I will look into it some more sometime later, right now, there is no action on your side needed.

Thanks.
                                Petr

**Comment by chinadragon0515** [comment]
thanks Petr, I will close the issue now, if there is any issue on our side, help to let me know, and if it is the same issue, reopen the issue.
