### ISSUE TITLE
Dependency Injection in DbApi<T>

### ISSUE THREAD

**Issue by cilerler** [OData/RESTier#395]
Using RESTier 0.5.0 and trying to pass a dependency into an API that derived from [**RESTier**](https://github.com/OData/RESTier)'s `DbApi<T>`.  Obviously it asks for parameter-less constructor but I need to set `_notificationProvider`.  How it can be achieve?  Thanks in advance..

_Using OWIN based self-hosted Web API._

> You may find the code of MapRestierRoute<T> at [here](https://github.com/OData/RESTier/blob/master/src/Microsoft.Restier.WebApi/Routing/HttpConfigurationExtensions.cs#L23-L77)

# Startup

    [assembly: OwinStartup(typeof(Startup))]
    
    namespace ProjectName.Host
    {
        public class Startup
        {
            public void Configuration(IAppBuilder appBuilder)
            {
                // ...
    
                using (var httpConfiguration = new HttpConfiguration())
                {
                    RegisterDependencies(httpConfiguration);
    
                    httpConfiguration.EnableSystemDiagnosticsTracing();
    
                    httpConfiguration.MapHttpAttributeRoutes();
                    
                    httpConfiguration.EnableUnqualifiedNameCall(true);
                    httpConfiguration.SetUrlConventions(Microsoft.OData.Core.UriParser.ODataUrlConventions.ODataSimplified);
    
                    RegisterRestier(httpConfiguration, GlobalConfiguration.DefaultServer);
    
                    httpConfiguration.Routes.MapHttpRoute(name: "DefaultApi", routeTemplate: "api/{controller}/{action}/{id}", defaults: new
                                                                                                                                         {
                                                                                                                                             id = RouteParameter.Optional
                                                                                                                                         });
    
                    appBuilder.UseWebApi(httpConfiguration);                
                }
            }
            
            private readonly UnityContainer _container = new UnityContainer();
            public void RegisterDependencies(HttpConfiguration config)
            {
           
                _container.RegisterType<INotificationProvider, RabbitMessageQueueNotificationProvider>();
                config.DependencyResolver = new UnityDependencyResolver(_container);
            }

            public void RegisterRestier(HttpConfiguration config, HttpServer server)
            {
                config.MapRestierRoute<MainApi>("Main", "api/Main", new RestierBatchHandler(server));
            }
        }
    }

# Api

    public partial class MainApi : DbApi<MainContext>
    {   
        private readonly INotificationProvider _notificationProvider;        
        
        public MainApi(INotificationProvider notificationProvider)
        {
            _notificationProvider = notificationProvider;
        }

        protected override IServiceCollection ConfigureApi(IServiceCollection services)
        {
            base.ConfigureApi(services);

            IServiceCollection output = services.AddScoped<INotificationProvider, MessageQueueNotificationProvider>();
            return output;
        }
    }

**Comment by chinadragon0515** [comment]
There are two ways to achieve this,

1. Register INotificationProvider  as DI service too, in this way, when use DI to get MainApi, it will get service INotificationProvider  first.

To register it as service, you can override method ConfigureApi method in API class, and content will be like 
base.configureApi(services);
services.AddScoped< INotificationProvider  , ProviderImplementation > ();

Refer to http://odata.github.io/RESTier/#04-03-Api-Service for more information, if the document is not clear for you, let us know, and we also accept pull request for the changes of document.

2. You can create a factory which will create a new MainApi with required parameters, then register this factory as DI service

Refer to this link for example http://odata.github.io/RESTier/#02-08-Customize-Query which is for ODataValidationSettings.

If your question is answered, help to close the issue, thanks.

**Comment by cilerler** [comment]
Thank you for prompt reply.

I already tried first method alone _(updated on code above)_ the moment I delete parameter-less constructor, it throws compile-time error at `config.MapRestierRoute<MainApi>("Main", "api/Main", new RestierBatchHandler(server));`

> ### Compile Time Error
'MainApi' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'TApi' in the generic type or method 'HttpConfigurationExtensions.MapRestierRoute<TApi>(HttpConfiguration, string, string, RestierBatchHandler)'	

So, I had to mix with 2nd suggestion and just changed the part as below and works like a charm.
```
public void RegisterRestier(HttpConfiguration config, HttpServer server)
{
   config.MapRestierRoute<MainApi>("Main", "api/Main", () => new MainApi(_container.Resolve<INotificationProvider>()), new RestierBatchHandler(server));
}
```

But not sure if I need to register anything else?

**Comment by chinadragon0515** [comment]
@cilerler I made a mistake, we have not get Api as DI service yet which is tracked with issue #337 , so I need to take what I have said.

In order to achieve what you need, you did it right now, and after we get #337 done, you can do in the first way as I said. let me know if you have any more questions or comments, thanks.

**Comment by chinadragon0515** [comment]
duplicate with #337
