### ISSUE TITLE
The query option $count is not allways working as expected

### ISSUE THREAD

**Issue by marianc** [OData/RESTier#397]
According to [OData V4 specification](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part1-protocol/odata-v4.0-errata02-os-part1-protocol-complete.html#_Toc406398308), $count result is not influenced by $top, $skip or $expand, as it is specified:

> The $count system query option ignores any $top, $skip, or $expand query options, and returns the total count of results across all pages including only those results matching any specified $filter and $search.

I found that sometimes the $count is limited to the $top value.

### Assemblies affected
I am using 'RESTier 0.4.0-rc2'.

### Reproduce steps
It is difficult to reproduce the issue because in most cases the behavior is correct. However I was able to reproduce it using [AdventureWorks2012 sample database](http://msftdbprodsamples.codeplex.com/releases/view/93587) with the following query:

> /SalesOrderHeaders?$filter=OnlineOrderFlag eq false&$orderby=SalesOrderID desc&$expand=Customer,Customer($expand=Store)&$count=true&$skip=0&$top=10

### Expected result
The expected result is count=3806.

### Actual result
The actual result is count=10.  

### Additional details
If $expand query option is removed the result is correct count=3806.

**Comment by chinadragon0515** [comment]
This is fixed with #287 , and 0.5 release will include the fix and we plan to release 0.5 release sometime of May. thanks.

**Comment by chinadragon0515** [comment]
I close this issue as it is already fixed.

**Comment by chinadragon0515** [comment]
@marianc  0.5 is official release, we highly recommend you to upgrade to this version.
