### ISSUE TITLE
need help with RESTier getting started

### ISSUE THREAD

**Issue by figuerres** [OData/RESTier#398]
I am not able to setup a working sample.
also the web pages refer to a sample project that is not in the GitHub 

### Assemblies affected
*Which assemblies and versions are known to be affected e.g. RESTier 0.4.0-rc2.*  

### Reproduce steps
create a web application with VS 2015 and an EF 6 model try to use RESTIer and get 404 errors

### Expected result
get the OData 4 endpoint json 

### Actual result
404 not found errors  

as the sample is gone I cant compare my project to the sample.
I only have 3 tables in my model.

**Comment by chinadragon0515** [comment]
Can you refer to our end to end test sample as a start point? https://github.com/OData/RESTier/tree/master/test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin

You can also clone all the code, load the solution into VS, and play with the sample, it is started as service, and you can make request from any client like web browser for get or other rest client for put/post and so on.

Let me know if you need more information.


If you want to start by yourself, you can follow the document http://odata.github.io/RESTier/#01-02-Bootstrap to create by your self.

**Comment by figuerres** [comment]
on:  http://odata.github.io/RESTier/
is a link that is broken.
the section is
2.1 Role Based Security


Currently the quality of the role-based security module is NOT guaranteed and this module will NOT be shipped with regular RESTier releases. Please use it at your own risk.

For example code, please refer to NorthwindApi.

that northwind link is a 404
https://github.com/OData/RESTier/blob/master/src/Microsoft.Restier.Samples.Northwind/Models/NorthwindApi.cs#L14-L24

**Comment by figuerres** [comment]
Now that I got a basic RESTier config to work I am looking for some idea of how to migrate from having many controller classes to using RESTIER
right now I have a base class that I use to make some things happen on all of my entities.
I see a lot of options in restier but possibly someone can recommend a path to follow?

what I have now in my base class is that it starts with:
  public class BaseOdataController<TDbContext, TIDataRecord> : ODataController
        where TDbContext : DbContext, new()
        where TIDataRecord : class, IDataRecord, new() {
and IDataRecord declares a few properties 

 public interface IDataRecord {
        int Id { get; set; }
        int CreatedBy { get; set; }
        DateTimeOffset CreatedDate { get; set; }
        int? WhoChanged { get; set; }
        DateTimeOffset LastChanged { get; set; }
        byte[] RowVersion { get; set; }
        bool RecDelete { get; set; }
    }

with that defined for all the entities that use the interface my Post / Patch / Get and Delete methods can update the standard properties automatically.
so if I can get REstier to see that a given entitiy impliments that interface and then call my logic to update I will be set to use RESTIER.

it looks like it can be done if I can just work out the nuts and bolts of how to hook it up.

**Comment by chinadragon0515** [comment]
The class link is https://github.com/OData/RESTier/blob/master/test/ODataEndToEndTests/Microsoft.Restier.Samples.Northwind/Models/NorthwindApi.cs#L22-L32, I will update the document soon, we also welcome pull request to update any document or fix of bugs.

**Comment by chinadragon0515** [comment]
Can I know do you use entity framework? How you define the model?

My understand  is you want restier to handle all the request, and do some check whether the class implement some interface, and if yes, call some code else?
No, restier can not do this directly, this is some customized logic restier can not reference.

But RESTier allows you do some additional customization beside RESTier logic on update/insert/delete, we allow you to customize logic before restier persist the change or after restier persist the change,
refer to http://odata.github.io/RESTier/#02-03-Submit-Logic and http://odata.github.io/RESTier/#02-09-Customize-Submit

So you can do is like before RESTier persist the change, you can add any logic, and change the ChangeSetItem content for change or persist.



For query part, you will need to process LINQ expression if you want any customization ,refer to  http://odata.github.io/RESTier/#02-08-Customize-Query

BTW we recommend questions to be posted stackoverflow, and here is tracking issues/bugs/feature request.

**Comment by figuerres** [comment]
I am looking on so but not much found there so far.
My model has about 30 tables now and I expect it to get at least 30 more tables before the system is done. Right now I use a base class that is derived from odatacontroller and has constraints that the entity must implement an interface that allows me to write generic code to do part of the post, patch, delete and get verbs. In looking at the docs I have seen an option to create methods like OnUpdating or OnInserting but having to do that for each of 30+ tables will just not scale up.

If there is a way to hook into the pre insert pre post pre delete actions without specifying the entity name then I can test for the entity implementing my interface and then act based on that.
Is there a way to do that ?
Or do I need to hook into the entity framework code ?

**Comment by chinadragon0515** [comment]
1. "Right now I use a base class that is derived from odatacontroller and has constraints that the entity must implement an interface that allows me to write generic code to do part of the post, patch, delete and get verbs. " I am curios how you get this work, can I know more details like you define many OData route attribute?  Also even with customize route information, can I know how you call other logic? Or this is something you want to do?

2. "In looking at the docs I have seen an option to create methods like OnUpdating or OnInserting but having to do that for each of 30+ tables will just not scale up.", we have another option as I mentioned above, refer http://odata.github.io/RESTier/#02-09-Customize-Submit, Customized Process Logic part, if document is not clear, we are welcome contribution, also if you do not have time to contribute, let me know, and I will find time to update document.

**Comment by figuerres** [comment]
documentation: I see a lot of version tags on different parts so it has not been clear which things are in the current nugget package or do I need to get the source and build from source?

also I see the section that you refer to but the page is missing a section to document how that should work, if need to I will dig into the code and try to find it....

what  I have been doing so far is to use a pattern that start with an interface that I apply to my ef model poco classes like this:

namespace ATrak2Model {
    public interface IDataRecord {
        int Id { get; set; }
        int CreatedBy { get; set; }
        DateTimeOffset CreatedDate { get; set; }
        int? WhoChanged { get; set; }
        DateTimeOffset LastChanged { get; set; }
        byte[] RowVersion { get; set; }
        bool RecDelete { get; set; }
    }
}

this sets up that each table has some columns that I can code against.

then by actual controller class is like this:

  public class BusinessEntitiesController : BaseOdataController<ATrak2Model.ATrak2Model, BusinessEntity> {
        readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        [EnableQuery]
        public IQueryable<BusinessEntity> GetBusinessEntities() {
            logger.Info("got request");
            return GetMany();
        }
        [EnableQuery]
        public SingleResult<BusinessEntity> GetBusinessEntity([FromODataUri] int key) {
            logger.Info("got request");
            return GetSingle(key);
        }
        public async Task<IHttpActionResult> Post(BusinessEntity BusinessEntity) {
            return await Add(BusinessEntity, base.ControllerContext.RequestContext.Principal.Identity.GetUserId<int>());
        }
        [AcceptVerbs("PATCH", "MERGE")]
        public async Task<IHttpActionResult> Patch([FromODataUri] int key, Delta<BusinessEntity> patch) {
            return await Update(key, patch, base.ControllerContext.RequestContext.Principal.Identity.GetUserId<int>());
        }
        public async Task<IHttpActionResult> Delete([FromODataUri] int key) {
            return await Delete(key, ControllerContext.RequestContext.Principal.Identity.GetUserId<int>());
        }
    }

and the base class has the rest of the code:

  /// <summary>
    /// A generic base class to aid in creating OData 4 controllers for assorted tables exposed via Entity Freamwork V6
    /// requires that the Entity class conforms to the IDataRecord interface and support "New".
    /// </summary>
    /// <typeparam name="TDbContext">an EF6 dbContext class</typeparam>
    /// <typeparam name="TIDataRecord"> an EF6 POCO class that impliment the IDataRecord Interface</typeparam>
    public class BaseOdataController<TDbContext, TIDataRecord> : ODataController
        where TDbContext : DbContext, new()
        where TIDataRecord : class, IDataRecord, new() {

        readonly log4net.ILog logger;

        private TDbContext db = new TDbContext();

        public  BaseOdataController(){
            logger = log4net.LogManager.GetLogger(this.GetType());
        }
        /// <summary>
        /// wrapper for selecting all records
        /// </summary>
        /// <returns></returns>
        public IQueryable<TIDataRecord> GetMany() {
            try {
                logger.Debug(" got request for " + typeof(TIDataRecord).FullName + " GetMany()");
                var dd = db.Set<TIDataRecord>().Where(x => x.RecDelete == false);
                logger.Debug(" got " + dd.Count().ToString() + "  " + typeof(TIDataRecord).FullName  + " Rows ");
                return dd;
            }
            catch (Exception ex) {
                logger.Error(" get many " + typeof(TIDataRecord).FullName + " failure ", ex);
                throw;
            }
        }

        /// <summary>
        /// wrapper for selecting one record by key
        /// </summary>
        /// <param name="key">Primary Key for the entity</param>
        /// <returns></returns>
        public SingleResult<TIDataRecord> GetSingle(int key) {
            try {
                logger.Debug(" got request for " + typeof(TIDataRecord).FullName + " GetSingle( " + key.ToString() + " ) ");
                var dd = SingleResult.Create(db.Set<TIDataRecord>().Where(x => x.Id == key && x.RecDelete == false));
                logger.Debug(" got 1 "  + typeof(TIDataRecord).FullName + " Row ");
                return dd;
            }
            catch (Exception ex) {
                logger.Error(" get single " + typeof(TIDataRecord).FullName + " failure ", ex);
                throw;
            }
        }

        /// <summary>
        /// wrapper for inserting a new record
        /// </summary>
        /// <param name="entity">new entity data</param>
        /// <param name="UserId">Id of the user whose token was used</param>
        /// <returns></returns>
        public async Task<IHttpActionResult> Add(TIDataRecord entity, int UserId) {
            if (!ModelState.IsValid) {
                logger.Debug(" Add " + typeof(TIDataRecord).FullName + " Bad Model State : " + string.Join(" | ", ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage)));
                return BadRequest(ModelState);
            }
            try {
                DateTimeOffset dtNow = DateTimeOffset.Now;
                entity.CreatedBy = UserId;
                entity.WhoChanged = UserId;
                entity.CreatedDate = dtNow;
                entity.LastChanged = dtNow;
                entity.RecDelete = false;
                db.Set<TIDataRecord>().Add(entity);
                await db.SaveChangesAsync();
                return Created(entity);
            }
            catch (Exception ex) {
                logger.Error(ex);
                return InternalServerError(ex);
            }
        }

        /// <summary>
        /// wrapper for updating a record
        /// </summary>
        /// <param name="key">Primary Key for the entity</param>
        /// <param name="patch">the changed data</param>
        /// <param name="UserId">Id of the user whose token was used</param>
        /// <returns></returns>
        public async Task<IHttpActionResult> Update(int key, Delta<TIDataRecord> patch, int UserId) {
            if (patch == null) {
                logger.Debug(" Update on  " + typeof(TIDataRecord).FullName + " Delta object is null! ");
                return BadRequest(" Invalid " + typeof(TIDataRecord).FullName + " Object  ");
            }
            Validate(patch.GetEntity());
            if (!ModelState.IsValid) {
                logger.Debug(" Update " + typeof(TIDataRecord).FullName + " Bad Model State : " + string.Join(" | ", ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage)));
                return BadRequest(ModelState);
            }
            if (!Exists(key)) {
                logger.Debug(" Update on  " + typeof(TIDataRecord).FullName + " with Key of " + key.ToString() + " Record not found ");
                return NotFound();
            }
            try {
                TIDataRecord entity = await db.Set<TIDataRecord>().FindAsync(key);
                patch.Patch(entity);
                DateTimeOffset dtNow = DateTimeOffset.Now;
                entity.WhoChanged = UserId;
                entity.LastChanged = dtNow;
                await db.SaveChangesAsync();
                return Updated(entity);
            }
            catch (Exception ex) {
                logger.Error(ex);
                return InternalServerError(ex);
            }
        }

        /// <summary>
        /// wrapper that takes a delete request and uses the RecDelete flag to mark it as deleted
        /// this allows us to logically delete a record with out actually removing it from the table in case we need 
        /// to keep a history of the data or undo a delete action for any reason.
        /// </summary>
        /// <param name="key">Primary Key for the entity</param>
        /// <param name="UserId">Id of the user whose token was used</param>
        /// <returns></returns>
        public async Task<IHttpActionResult> Delete(int key, int UserId) {
            if (!Exists(key)) {
                logger.Debug(" Delete of " + typeof(TIDataRecord).FullName + " with Key of " + key.ToString() + " Record not found ");
                return NotFound();
            }
            try {
                TIDataRecord entity = await db.Set<TIDataRecord>().FindAsync(key);
                DateTimeOffset dtNow = DateTimeOffset.Now;
                entity.WhoChanged = UserId;
                entity.LastChanged = dtNow;
                entity.RecDelete = true;
                await db.SaveChangesAsync();
                return StatusCode(HttpStatusCode.NoContent);
            }
            catch (Exception ex) {
                logger.Error(ex);
                return InternalServerError(ex);
            }
        }

        /// <summary>
        ///  test for is there a record by that key in the table
        /// </summary>
        /// <param name="key">Primary Key for the entity</param>
        /// <returns></returns>
        private bool Exists(int key) {
            return db.Set<TIDataRecord>().Any(e => e.Id == key && e.RecDelete == false);
        }

        /// <summary>
        /// follow the dispose pattern.
        /// </summary>
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing) {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }


this make sure that every edit to the record and the create of the record is being tracked automatically and the id of the authenticated / authorized login user is stamped in the whochnaged 

 
	  
      CreatedBy 
      CreatedDate 
      WhoChanged 
      LastChanged 
      RecDelete


by having this set of properties / columns updated in a consistant way I can then add an audit train in the sql server to log when records are changed and by who and as much detail as we need.
 this also makes a users "Delete" into a logical delete so that if there is a mistake we can "undo" the delete by just clearing the recdelete bit flag in the record.

so I am looking to keep that pattern working.

I do have a few tables that I have not been doing this with and with what I see with how restier is setup I will just need to make a bit of code to say "if this entity implements this interface then apply this logic.
so for a few tables I do nothing as they do not need the detail change tracking.

the other item is making sure that the 
ControllerContext.RequestContext.Principal.Identity.GetUserId<int>()
is accessable or is passed into my code in some way so that I can update the whochnaged property to show the current logged in user id.

I will get the code and try to see if I can follow it and will let you know.

any hints and any more documentation will of course help.
and I can add something to make this work better for other users I will be glad to contribute back to the project.

**Comment by figuerres** [comment]
I downloade the code and I am trying to find some of the parts you refered me to but they are not in the files...   is there a hidden branch of the code I need to find or is this just a plan that has not been written ?
for example I can find any of the following in the code I got from GitHub:
IQueryExpressionProcessor
DBApi
IServiceCollection

**Comment by chinadragon0515** [comment]
1. I am sorry about different tags of document,
      a). In Nuget, we have 0.4.0-rc2 release, any document with tag 0.4.0 or >=0.4.0 will work for this version.
      b). We are working to release 0.5.0 soon, and we are in process of public API review (this is also the reason you see some class name/namespace changed), any document marked with >=0.4.0 or >=0.5.0 will work for this version.

2. When I point the document, I always mean 0.5.0 version unless I clearly state other version.

3. With RESTier, you can still do this, you can implement interface IChangeSetItemProcessor, and make any changes to Entity.
    Seems the document is not clear, I will add more detail (Pull request on document is also welcomed), and you can also refer to https://github.com/OData/RESTier/blob/master/test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin/Submit/CustomizedSubmitProcessor.cs for example.
This should work for you and you can make base changes in method OnProcessingChangeSetItemAsync which is called before persistence is called.

4. For the class you listed,
https://github.com/OData/RESTier/blob/master/src/Microsoft.Restier.Core/Query/IQueryExpressionProcessor.cs

https://github.com/OData/RESTier/blob/master/src/Microsoft.Restier.EntityFramework/EntityFrameworkApi.cs (was DbApi before)

IServiceCollection, it is a class of dependency package. Not part of RESTier code.

**Comment by figuerres** [comment]
So I think what you are saying in part if I am right is that the source code in the repository is the 0.5.xx code and that I need to download and build that repository code to do this.
is that right ?
I will have to download it and see I guess...

**Comment by chinadragon0515** [comment]
Yes, and we plan to release 0.5 to nuget soon (later May or early June), and we are in process of public review for 0.5 release, we do not want big changes on public API for the next release which we plan to have first GA later this year.

**Comment by figuerres** [comment]
for now  I am looking at some of my own code to do what I need.
I tried to setup some code based on what I got here but had no luck in getting the functions I wanted.
I think that the code needs to be more completed and have some clear examples of use.
the test items are ok but with all the changes in the code and documentation it's just hard to make sure I am getting it right at this time.
I created what I thought were the needed classes and added the register lines and run the code, an updated happened to my data but the break point was never hit.
I tried to copy the source code to my project to help me try and step thru but that started creating issues with building  the solution.
so at least for now I am going to try and use my code with some changes to get what I need done.
I like the idea of what RESTIER is looking to do but I think it needs to be more completed 
or to possibly have more focus on how to make it work.
sample projects that are not part of the test / source tree so that we can stand them up and debugs them without getting into the stuff used to build the package.
also I never did find out if the authenticated user  (Principal) is carried from the entry point to the extensions.
if I need to update a "WhoChanged"  I need that.   on update, delete and Insert to EF I need to have the ID of the logged in user so that I can update the data with the id.
this is not the authorization this is to allow the DB to keep an audit trail of who is changing the records.
if the IPrincipal is attached to the context that has the request data then we can access it.

**Comment by chinadragon0515** [comment]
@figuerres I am sorry to hear I did not help you out with functions you needed, we will continue to improve product and documents, and I have some questions to understand the issue we have,

1. Do you build 0.5 version by yourself or using 0.4-rc2 from nuget? if you have not build 0.5 yet or request is not urgent, I will suggest you wait for a couple weeks and we plan to release  0.5 soon.

2. About the functions you need, you want to expose a data source as OData service, and you want some special logic for update and prefer a single class to handle these common special logic, is my understanding correct?

3. If my understanding of the function you need is correct, can I know the issues you have when you set RESTier with guide http://odata.github.io/RESTier/#01-02-Bootstrap and plugin customized logic before submit with document http://odata.github.io/RESTier/#02-09-Customize-Submit.
Also you can copy the sample code https://github.com/OData/RESTier/blob/master/test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin/Submit/CustomizedSubmitProcessor.cs  we have to the project you setup (note this need 0.5 version nuget package).
The more details we got, the easier for us to understand what we need to improve.

4. If you can share your sample project, I may take a look to see the register. And note for submit processor, it should be registered after base.ConfigureApi in your Api class (either extend EntityFrameworkApi or ApiBase) as document sample indicates.

5. "I tried to copy the source code to my project to help me try and step thru but that started creating issues with building the solution.", can I know whether you add/copy whole restier project or just some source code? And what's the issue you meet? 

6. When you means completed functions, can we know more details about what functions you think we are missing? 

7. For the security part, RESTier is transparent and adopt WebApi security logic, about Principal carried to extension method, we do not support this yet, I opened issue #403

**Comment by chinadragon0515** [comment]
No response for 2 weeks, close the issue.
If you see any issues, open new issues, thanks.
