### ISSUE TITLE
Entities using inheritance ignored by RESTier

### ISSUE THREAD

**Issue by jwobbe** [OData/RESTier#405]
I have an EF6 model and a few entities inherit from another entity.  The derived entities and their DbSets are ignored by RESTier.

### Assemblies affected
RESTier 0.5.0.0 (built from latest github source)

### Reproduce steps
Create a data model whose entities use inheritance.  Create a RESTier service from those entities and try to query for a derived entity.

### Expected result
Derived entities would be available through RESTier like the other EF entities 

### Actual result
The entities are not described in the metadata or available through the RESTier service in any way.

**Comment by chinadragon0515** [comment]
Duplicate with #117 
And already start some support, checked in the derived type model build two days ago, and will start work on query.
