### ISSUE TITLE
0.5.0 is official released, find it in nuget and try it!!

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#409]
Refer to announcement in link : https://blogs.msdn.microsoft.com/odatateam/2016/05/24/announcement-restier-v0-5-0-release/

Refer to link http://odata.github.io/RESTier/#06-07-0-5-0-beta for release notes. 

Any comments, suggestions are welcomed and appreciated.

**Comment by taspeotis** [comment]
I’ve used OData to expose data and its painful to filter collection navigation properties securely. It looks like Restier goes a reasonable way towards making this easier.

Thanks for this project.

**Comment by chinadragon0515** [comment]
@taspeotis , thanks, if you have any suggestions or comments, let us know, if you find any issues or new feature requests, open issue directly.

**Comment by chinadragon0515** [comment]
close it.
