### ISSUE TITLE
Ensure stable ordering for query

### ISSUE THREAD

**Issue by karataliu** [OData/RESTier#41]
ODataDomainController::GetQuery

investigate stable ordering in reference to WCF data services

**Comment by Tiberriver256** [comment]
I know this is pretty old but it looks like EnsureStableOrdering is on by default in WebApi. I see that you can disable it using ODataQuerySettings class and I also see directions for setting ODataValidationSettings.

Is there a simple method to globally set EnsureStableOrdering to false?

**Comment by karataliu** [comment]
@robertmclaws @xuzhg

**Comment by robertmclaws** [comment]
@Tiberriver256 What is Stable Ordering, and how do you configure it in WebAPI?

**Comment by robertmclaws** [comment]
@mikepizzo mentioned in the last Community Standup that the Stable Ordering method from WCF Data Services has been implemented in the latest WebAPI OData nightlies. We should be picking that up automatically in RESTier 1.0 Beta 2, so I'm going to close this for now. When Beta 2 comes out, if you still don't see it working properly, please re-open this issue and we'll investigate. Thanks!
