### ISSUE TITLE
How to implement CustomAuthentication that uses `Authorization` header value

### ISSUE THREAD

**Issue by cilerler** [OData/RESTier#417]
I implemented a custom authentication attribute that works fine if I derive from `ApiController`  But when I derive from `ODataController` it does not get triggered for regular requests like GET/POST etc.  I do not want to have the challenge in the class that I derived from `EntityFrameworkApi` since it shouldn't run anything (not even **CustomizedAuthorizer**) in there if user does not have a valid token.  Well I might be fine  to implement it in there if there is no other solution but even in that case I need to be able to retrieve **Authorization** header that I'm not sure if it is exposed in there or not.  Can you give me a head-light please.  Thanks in advance.
### Assemblies affected

RESTier 0.5.0
#### Startup

``` csharp

public class Startup
{
    public void Configuration(IAppBuilder appBuilder)
    {
        /// ...
        var notificationProvider = UnityConfig.GetConfiguredContainer().Resolve<INotificationProvider>();        
        using (var httpConfiguration = new HttpConfiguration())
        {
            /// ...
            httpConfiguration.MapRestierRoute<MainApi>("Main", "api/Main", () => new MainApi(notificationProvider), new RestierBatchHandler(server));
            httpConfiguration.Filters.Add(new IdentityBearerAuthenticationAttribute());
            /// ...
            appBuilder.UseWebApi(httpConfiguration);        
        }
    }
}
```
#### Authentication

``` csharp
public class IdentityBearerAuthenticationAttribute : Attribute, IAuthenticationFilter
{
    /// ...
}
```
#### MainController

``` csharp
[IdentityBearerAuthentication]
[Authorize]
public class MainController : ODataController
{
    private readonly INotificationProvider _notificationProvider;

    private MainApi _api;

    public MainController(INotificationProvider notificationProvider)
    {
        _notificationProvider = notificationProvider;
    }

    private MainApi Api => _api ?? (_api = new MainApi(_notificationProvider));

    /// ...
}
```
#### MainApi

``` csharp
public partial class MainApi : EntityFrameworkApi<MainContext>
{
    private static INotificationProvider _notificationProvider;


    public MainApi(INotificationProvider notificationProvider)
    {
        _notificationProvider = notificationProvider;
    }

    private class CustomizedAuthorizer : IChangeSetItemAuthorizer
    {
        private IChangeSetItemAuthorizer Inner { get; set; }

        public Task<bool> AuthorizeAsync(SubmitContext context, ChangeSetItem item, CancellationToken cancellationToken)
        {
            return Inner.AuthorizeAsync(context, item, cancellationToken);
        }
    }

    /// ...
}
```
### Expected result

Be able to hit **MainController** before I hit to **MainApi** so it can trigger **IdentityBearerAuthentication** or be able to retrieve request header values in **CustomizedAuthorizer** (not desired workaround)
### Actual result

It hits **MainApi** directly and there is no way for me to retrieve **Authorization** header in **CustomizedAuthorizer**

**Comment by chinadragon0515** [comment]
@cilerler we receive the issue and I will take a look but as RESTier is transparent to security part now, it will take time.

**Comment by chinadragon0515** [comment]
@cilerler I did some investigation and test,

In RESTier, the class CustomizedAuthorizer  is only used for the requested routed to RESTierController, and if there is some customized controller, the logic in class CustomizedAuthorizer  will not be called.

If your request is routed to RESTier controller, then define attribute in customized controller will not help.

Now you can make the attribute as the global configuration in register method which will make request to RESTier controller been authenticated by that attribute too.

The configuration will be "config.Filters.Add(new IdentityBearerAuthenticationAttribute ());"

Let me know whether this fixes your issue.

BTW, I see you use EnableRoleBasedSecurity, can I know how you use it now? we do not maintain it now, and it is not suggested to use.

**Comment by cilerler** [comment]
Thank you for your prompt response @chinadragon0515 

When you say `RESTierController` I believe you are actually talking about the one that derived from `ODataController` and not the one that derived from `EntityFrameworkApi<T>` correct?

I already tested with global filter _(also updated in the code above)_ it didn't get triggered earlier but tried again after your mention.  Unfortunately it still does not get triggered.  :cry:   

> Also even if it works then it will be applied to all the incoming requests including the ones should not have authorization. :pensive: 

About `EnableRoleBasedSecurity`, I actually couldn't be able to make it stable then saw one of your note and stopped working on it but looks like forgot to put `//x` in front of that line.  _(removed it from the code above)_ So please ignore that line and thank you for the warning. :+1:

**Comment by chinadragon0515** [comment]
@cilerler 
When I said RESTier controller, I mean a class named RestierController in RESTier library which is used to accept all the requests if user does not define his own controller.

I commit the test I did to my own repository (will commit to odata repository after I refine it), you can check the change I have from this link https://github.com/chinadragon0515/RESTier/commit/948742e2ea2c68959c818f568fe8ea1fccd11903

And here are what I do,

1. Divide security into two parts, one is authentication and the other is authorization.
2. Based on AuthenticationFilter and AuthorizationFilter.
3. Have two global configuration (one for Authentication and the the other is for Authorization).
4. Create a specific authentication filter for token generation.
5. In AuthenticationController, it ignores global authentication filter (and use his own filter) and ignore global authorization filter (without any authorization).
6. No real authentication or authorization is done, just for sample.

To run the test, get the code, import into VS,
Test three query,

1. Get http://localhost:18384/api/trippin/People(11), this request will be handled by controller within restier library RestierController. Will use global configured authentication filter and authorization filter.

2. Post http://localhost:18384/api/Trippin/CleanUpExpiredTrips, this request will be handled by TrippinController. Will use global configured authentication filter and authorization filter.

3. Post http://localhost:18384/test/Authenticate/login, will be handled by AuthenticationController. Will use customized authentication filter and no authorization filter.

This should meet your request that some request does not authentication or authorization. 

Let me know if you have any more questions. thanks.

**Comment by cilerler** [comment]
Thank you very much for all your time and attention. 😊

Short story long `[OverrideAuthentication]` solved my problem.  I had `[OverrideAuthorization]` and it didn't do the trick. 😉

Also, I continued to test with your code and had exception below at `HttpContext.Current.User = principal;` due to not existing `HttpContext.Current`. 
> *Object reference not set to an instance of an object.*

Other than that it works like a charm.  Thank you again!

_I didn't want to close the issue since you marked it as _in progress_ feel free to close

**Comment by ivanko2000** [comment]
Showing how to make AuthN/Z work in this context is valuable (even if somewhat out of scope here); it would be great if this sample were made part of the main code base examples / referenced in the documentation...

**Comment by chinadragon0515** [comment]
Will sample in this link https://github.com/chinadragon0515/RESTier/commit/948742e2ea2c68959c818f568fe8ea1fccd11903 works for you?  It has some high level demonstration on the security even it does not do the real authentication or authorization?  Or you are looking for something different?

**Comment by ivanko2000** [comment]
Yes, it's a good example. I just meant that it probably should be referenced in the documentation for easier discovery...

**Comment by chinadragon0515** [comment]
@ivanko2000 We want to see more user request, and also review with ASP .Net security team, make sure we recommend a best practice for most customers. Then we will commit to github and add document.

If you have any specified issues, open issue in github, it will help us to learn customer scenario. thanks

**Comment by mattpwg** [comment]
I am rather new to restier framework and also stumbled accross security topic. I'd highly appreciate some best practice documents.

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
