### ISSUE TITLE
Improve key parsing logic

### ISSUE THREAD

**Issue by karataliu** [OData/RESTier#42]
RestierQueryBuilder::GetPathKeyValues

Current parsing implementation does not allow key values to contain commas or equal.

**Comment by chinadragon0515** [comment]
Depending on the WebAPI to make KeyValuePathSegment.Values collection public (or have the parsing logic public).

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
