### ISSUE TITLE
Support key value with alias

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#421]
When request an entity with key, support key value as alias, and also validate back slash and slash support.

This is depending on https://github.com/OData/odata.net/issues/570

And a temp solution is added with issue https://github.com/OData/RESTier/issues/414

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
