### ISSUE TITLE
error after upgrade package to 0.5

### ISSUE THREAD

**Issue by lgadola** [OData/RESTier#427]
*Short summary (3-5 sentences) describing the issue.*  
I get error after upgrade to 0.5:
Reference to type 'IApi' claims it is defined in 'Microsoft.Restier.Core' but it could not be found

in
            await config.MapRestierRoute<MFOApi>(
                "MFOApi",
                "odata",
                new RestierBatchHandler(server));

### Assemblies affected
restier-0.5 beta

### Additional details
deleted the ASP.Net temporary files

**Comment by cilerler** [comment]
From the release notes in [here](http://odata.github.io/RESTier/#06-06-0-4-0-rc2)
> The interface `IApi` is now removed. Use `ApiBase` instead. We never expect users to directly implement their API classes from IApi anyway. The `Context` property in `IApi` now becomes a public property in ApiBase

**Comment by peder** [comment]
I get this error without referencing `IAPI` directly, just like the OP:

```await config.MapRestierRoute<Models.EcmDomain>("EcmApi", "", new RestierBatchHandler(server));```

If I follow the example from the `0.6.0` documentation and use the `using Microsoft.Restier.Publisher.OData.Batch;` namespace, it's unable to find it.

**Comment by peder** [comment]
Gotta be some user error on my part, I'm now using the following namespaces successfully:

```using Microsoft.Restier.Publishers.OData;
using Microsoft.Restier.Publishers.OData.Batch;```

Those replace the previous namespaces:

```using Microsoft.Restier.WebApi;
using Microsoft.Restier.WebApi.Batch;```

Now I think I'm good to go.

**Comment by chinadragon0515** [comment]
@peder we always not actively monitor comments against closed issues, if you have issues in future, I will suggest you open new issues, and it is also helpful for track.

And we have 0.6 release last week, there is not many API changes, but add lots of new features.
