### ISSUE TITLE
Composite primary key not recognized

### ISSUE THREAD

**Issue by lgadola** [OData/RESTier#428]
In my model I have entities with a composite primary key. 
When calling config.MapRestierRoute<MyApi> I get error System.InvalidOperationException - The entity 'xxx' does not have a key defined.

**Comment by chinadragon0515** [comment]
@lgadola can I know how you define your CLR class? You need to specify the composite key and order in CLR class in order model builder can recognize. You can refer to our sample class for composite key support https://github.com/OData/RESTier/blob/master/test/ODataEndToEnd/Microsoft.OData.Service.Sample.Trippin/Models/Order.cs

Let me know if you have more questions or comments.

**Comment by lgadola** [comment]
I have created the entities with EF.Reverse.POCO
key is defined with fluent api:
            HasKey(x => new { x.CurrencyPairId, x.DatePer });
so, the  [Column(Order = 0)] decoration is missing (might that be the problem?)

**Comment by chinadragon0515** [comment]
@lgadola Do you mean you use this tool https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator to generate code from Database, and which will generate a single cs file with class defined?

In this class, you need to add key attribute to your class key filed so model build can find the composite key or by default it will find attribute with name ID or classname+id, and it will not be able to find the attribute.

We also have an issue to auto pop database key as model key, and this is tracked with https://github.com/OData/RESTier/issues/413

**Comment by lgadola** [comment]
yes these issues are certainly related. Personally, I think that (composite) keys defined by fluent api must be supported by restier. Fluent api is very common, either on its own or in combination with decorators. Generation tools also seem to use it extensively. I have tried with MS Visual Studio out-of-the-box functionality of creating a code-first model from database and the symptoms are identical: Restier can't cope with it. I think it must be addressed.

**Comment by silverf1re** [comment]
Same issue here I think it needs to be addressed. My table with a combined primary key is not being generated in the CS code.
