### ISSUE TITLE
Improve exception handling in RestierModelBuilder.cs

### ISSUE THREAD

**Issue by advancedrei** [OData/RESTier#433]
[RestierModelBuilder.GetModelAsync()](https://github.com/OData/RESTier/blob/master/src/Microsoft.Restier.Publishers.OData/Model/RestierModelBuilder.cs#L15-L52) needs to have its implementation wrapped in a try/catch, and explicitly throw an exception if there is an error in model building.

This task is related to Issue #432.

**Comment by chinadragon0515** [comment]
Did some test, when the key is not defined, ODataConversionModelBuilder throws correct exception, can I know what else you expect? Which exception you think it is not clear for this class?

As this class does not do anything special, I will prefer we do not catch, check and re-throw, and if we see any message which is unclear, we can make ODataConversionModelBuilder  improve the message or exception been thrown, let me know if you have any more comments or suggestions? thanks.

**Comment by chinadragon0515** [comment]
Close the issue as no response for about 2 weeks. If you have any more suggestions or comments, open new issues. thanks
