### ISSUE TITLE
Improve exception handling in HttpConfigurationExtensions.cs

### ISSUE THREAD

**Issue by advancedrei** [OData/RESTier#434]
[HttpConfigurationExtensions.MapRestierRoute()](https://github.com/OData/RESTier/blob/master/src/Microsoft.Restier.Publishers.OData/Routing/HttpConfigurationExtensions.cs) needs to have each major operation (like [model building](https://github.com/OData/RESTier/blob/master/src/Microsoft.Restier.Publishers.OData/Routing/HttpConfigurationExtensions.cs#L54) or [convention creation](https://github.com/OData/RESTier/blob/master/src/Microsoft.Restier.Publishers.OData/Routing/HttpConfigurationExtensions.cs#L56) wrapped in separate try/catch statements so they can throw more informative exceptions that the debugger can catch and report back to the developer.

Also, line 54 should probably be awaited. If there is a specific reason it is NOT being awaited, there should be a comment above that line explaining why.

This task is related to Issue #432.

**Comment by chinadragon0515** [comment]
We expect each major functions will throw the correct exception and another wrapper means any low level changes to have more exception or more detail message will need wrap layer changes.

If some exception is not clear, we will work will low level to improve the exception.

As to line 54, I add clearly comments why it is not wait (which was wait before), let us know if you have more questions or suggestions,  thanks.

**Comment by chinadragon0515** [comment]
Close the issue as no response for about 2 weeks. If you have any more suggestions or comments, open new issues. thanks
