### ISSUE TITLE
An unhandled exception of type 'System.AggregateException' occurred in mscorlib.dll

### ISSUE THREAD

**Issue by lgadola** [OData/RESTier#436]
Above error is thrown and program is aborted
This error occurred while I tested restier with different frameworks/models.

### Assemblies affected
0.5.0-beta

### Reproduce steps
I have attached a sample program. Added Northwind.OData to the samples of a framework I was testing with ([URF](https://genericunitofworkandrepositories.codeplex.com/)).
Running Northwind.OData will throw the error on startup.

[Sample.zip](https://github.com/OData/RESTier/files/306269/Sample.zip)

**Comment by advancedrei** [comment]
This issue may be related to #432. This is the same exception that I saw at the same point in the process.

**Comment by lgadola** [comment]
thanks, that is the same issue
