### ISSUE TITLE
Auto-expanded navigational properties cannot be filtered out

### ISSUE THREAD

**Issue by CzPete** [OData/RESTier#437]
When using a query like
https://localhost/beta/me/tableDefinitions/TBK6ZUB2GOK8U6N6GZVVFUXDIK/columnDefinitions?$select=propertyName,displayName
the result set contains propertyName and displayName fields (as desired) but also navigation properties that are being auto-expanded (not desired) even when those properties are not listed in the $select list.
### Assemblies affected

OData 5.9.0-beta / RESTier 0.4.0
### Reproduce steps

See above
### Expected result

Only the properties listed in $select will be returned
### Actual result

Properties listed in $select + auto-expanded properties

**Comment by chinadragon0515** [comment]
About filter out auto-expand navigation properties,
Now per specification, if the navigation property is in $select, it will be not represented as inline content, but if it is in $expand, then its content will be represented as inline content.
With auto-expand, the real request url add the $expand=Choice, **then the choice content is represented as inline content is as expected.**

If we do not want to have Choice been represented as inline, we need to disable auto-expand, can we disable auto-expand if we do not want to have it represented inline? Thanks.

**Comment by chinadragon0515** [comment]
Web Api OData is working on some flag to exclude auto-expand property is there is a $select clause.

**Comment by chinadragon0515** [comment]
related to WAO https://github.com/OData/WebApi/issues/750

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
