### ISSUE TITLE
Partition the methods which need to defined in API class now

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#439]
Now we support kinds of customized logic includes,
1. Access control method like CanInsertPeople and so on, and these need to be defined in Api class.
2. Pre/Post Action method like OnInsertingPeople or OnInsertedPeople and so on, and these need to be defined in Api class.
3. Entity set filter method like OnFilterPerson ( have changed to entity type)
4. For the operation (action/function/action import/ function import), in order to make RESTier to do the model build and auto route, they must been defined in Api class.

These make APi class very big if lots of customization logic. 

Consider a design to separate the logic into different class/places.

**Comment by advancedrei** [comment]
So, one option that we are using today is to have our DbApi-inheriting class as the root of a partial class, and then have EntitySet-specific partial class files underneath. So it looks like this:

- SunbizDbApi.cs
  - CorporationInterceptors.cs
  - etc...

Using some of the same reflection conventions you're already using, you might be able to let people create classes like {EntitySetName}Api, and then repurpose your existing convention-mapping processes to look for that class name before using the authorization, query, and DB-commit interceptors.

**Comment by adamholdenyall** [comment]
Is there a way we could have an interface such as Interceptor<T>, of which you could have many instances on the Api class. The Interceptor interface would simply have OnFilter, CanInsert, CanDelete, CanUpdate etc. This way the name of the entity set does not have to be integrated into the function. I have worries about the maintainability of keeping the entity set name in line with all of the filtering functions.

**Comment by chinadragon0515** [comment]
@advancedrei Partial class is one of option, but it still requires the class have the same name even stored in different file. Some conversion like {EntitySetName}Api or some attribute defined for the class or some common interface to be extended to implement are other options we are considering.

**Comment by chinadragon0515** [comment]
@adamholdenyall can you help to elaborate your user scenario and proposal.
Do you proposal a common interface, then for entity set requires the customized logic, it will implements the interfaces. And the Api class has a list of these kinds of interfaces? Then will entityset name been part of the class name works for you?

**Comment by advancedrei** [comment]
I personally don't know that implementing an Interface is a good idea, because wouldn't that require every interface member to be implemented? That might end up with a lot of empty method implementations for some people.

I would would personally rather inherit from a base class that returns a default implementation (like returning "false" for all CanInsert/CanUpdate/CanDelete methods) that I can override as necessary.

**Comment by adamholdenyall** [comment]
@advancedrei,  yes that is a much preferable solution. If the parent class with the virtual methods is generic, you can have something like MyTripInterceptor : Interceptor<Trip>, and implement just the members you want. I also like the idea of locking it down pretty tight initially. 

With regards to the entity set in the class name @chinadragon0515, I am a very wary of tying the entity name to the class or methods in general. If you have the generic, you can always trust that instead. That way typos and refactoring can't change filtering.  You should also be able to just add these to the service collection and find all implementing types.

**Comment by chinadragon0515** [comment]
@advancedrei @adamholdenyall  thanks for your suggestions and comments.

I just initiated an internal discussion on this item, the basic idea now are
1. There is a dictionary for user to register customization logic class.
2. User can use any name for class, he need to register type and entity type into the dictionary.
3. RESTier code will auto register each implement class as DI service so the lifecycle of the instance will be managed by DI.
4. In class, user can implement conversion based method like CanInsert and so on.

Some consideration,
Did not use common attribute/interface/base class, as do not want to scan all assembles to find the classes implement some interface/base class or have common attribute.
Also not all method are required, so base class/interface are not best fit here.

I also want to know priority of this item from your view, is it an urgent request from you view?
I did not consider it is urgent for two reasons,
1. Partial class can be used.
2. We have interface for user to implement to control such logic all entity set which can fit request of user who does not want to implement logic for each single entityset or type, but common logic for all entity set and type.

**Comment by adamholdenyall** [comment]
So you would create the class, and register it in the dictionary, and at runtime, the class would be scanned for methods named CanInsert or OnFilter? What would the arguments passed into these functions be? If the argument and return type still look like this I think this setup would be sufficient.
`IQueryable<Trip> OnFilter(IQueryable<Trip>)`
The CanInsert, CanDelete, etc are much simpler and just return bools. However, is there a way we could get information about the element(s) they are trying to inert and delete?

I demoed a simple RESTier endpoint to some teammates yesterday, and they had quite a bit of trepidation about the method name-based entity resolution. I think providing an alternate solution based on registering types would ease some concerns with using this library. 

I understand that IQueryExpressionProcessor is available (if that is what you are referring to in #2), but the only examples in the repository deal with common functionality between all entity sets. Again, the main draw of OnFilter etc is that it is extremely easy to understand. You get an IQueryable in, perform some transformation, and return another IQueryable. It is my understanding that such focused logic in IQueryExpressionProcessor would require a very long chain or IQueryExpressionProcessors or many many if/else switch logic. Perhaps I really just need more examples of how to use a custom IQueryExpressionProcessor.

**Comment by advancedrei** [comment]
I disagree about the name-based method resolution... convention over configuration is most often a better approach, if the conventions are easily understood. There is a certain "magical" quality to RESTier that should not go away, just be easily and simply explained. I believe the primary issue here is code organization, and how to make sure you don't have 1 API file that is tens of thousands of lines of code long spanning multiple entity sets. I think there is a way to do that without losing the magic.

Also, the CanInsertXXX and CanDeleteXXX functions are global. Meaning you use them to turn on or shut off functionality for *everyone* on certain objects. You might do some role-filtering on a global level, but it's not for specific objects.

If you want to reject based on the object coming in, you have to add an OnInsertingXXX(XXX someObject) function, where XXX = your entity set name. That will allow you to inspect the object and then return proper codes (like Unauthorized) based on that object.

HTH!

**Comment by chinadragon0515** [comment]
@advancedrei "convention over configuration is most often a better approach", can you help to elaborate this statement especially what kinds of configuration you expect here, if there is some examples, that will be better.

**Comment by robertmclaws** [comment]
Closing this for now, can be handled well with code generation and partial classes. We will be posting some samples after we get the core 1.0 framework shipped. Thanks everyone for your input!
