### ISSUE TITLE
Support functions in $filter and $orderby

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#440]
Per specification, URL like these two should be supported,

http://localhost:18384/api/Trippin/People?$filter=Microsoft.OData.Service.Sample.Trippin.Models.GetNumberOfFriends ge 1
http://localhost:18384/api/Trippin/People?$filter=$it/Microsoft.OData.Service.Sample.Trippin.Models.GetNumberOfFriends ge 1

WebApi OData already supports these two request, need to add support in RESTier.

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
