### ISSUE TITLE
Q: Using RESTier with dynamic model?

### ISSUE THREAD

**Issue by xhead** [OData/RESTier#441]
Gert Drapers has a [2012 demo of building an OData service ](https://channel9.msdn.com/Events/TechDays/Techdays-2012-the-Netherlands/2280) that builds its metadata at runtime from the database in the connection string. 

Is there a good and/or simple way to do that using this framework? I'm thinking I need to build an Api class like EntityFrameworkApi (ie. inherit from Microsoft.Restier.Core.ApiBase) but I don't know where to go from there. 

Mike

**Comment by chinadragon0515** [comment]
Do you mean your database schema will change after service is up? At this moment, RESTier does not support dynamic model, model is built when service is up and cached, it will be used for all following request.

**Comment by rayao** [comment]
2 years ago we built a prototype which could do dynamic model building, with earlier version of RESTier, it's still possible to do this with 0.5.0, what you need is a model builder that read DB schema and generate POCO types and finally build EdmModel upon it.

**Comment by chinadragon0515** [comment]
@xhead can we know your user scenarios to understand why dynamic model is needed? Does open type work for you? What's the priority of the request? Do you use restier with entity framework?

**Comment by xhead** [comment]
In Gert's scenario, he built an OData service that served up whatever tables/views it saw in the data source, where the connection string was supplied in the web.config file. If you changed the connection string (and presumably restarted the service), it would automatically serve up the new data source content. 

You could use the same service with any data source, instead of building a type-specific service for each data source. 

My scenario is that I wanted to build an OData service for a database where the set of views that would be exposed is still in flux - and ongoing support and maintenance would be doing view maintenance by SQL DBAs rather than .NET coders. 

I've abandoned this particular approach in favour of pushing view data into Azure Table Storage since it has an OData REST API built in. I've written an SSIS component to do this inside SSIS packages.
