### ISSUE TITLE
Has a global configuration for namespace for all entityset/type/operation

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#442]
Model container namespace is default, need to make it be consistent with entity type

**Comment by chinadragon0515** [comment]
Per discussion, here is what we will do,

1.	Have a global configuration for namespace, by default it has no value, and if user set the value, all model built by RESTier will use this namespace.
2.	If operation attribute specify the namespace, this value will override the global configuration, and this namespace will be used.
3.	If no global namespace is set, then entity type and entity set will use the namespace of CLR class. Operation will use this namespace too.
4.	If no global configuration, no entity type and entity set built, no namespace configured for operation, then the Api class namespace will been used.


And as first step, we will make sure container does not use "default" as namespace.

**Comment by chinadragon0515** [comment]
Should work with #457

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
