### ISSUE TITLE
RESTier returns HTTP 404 for valid OData urls addressing Derived Types

### ISSUE THREAD

**Issue by vvdev** [OData/RESTier#444]
RESTier returns HTTP 404 not found for the following URL:
http://server/api/restier/TablePerHierarchyEntitySet/Namespace.DerivedType1 (without "/" at the end of URL)
but returns correct data for the following
http://server/api/restier/TablePerHierarchyEntitySet/Namespace.DerivedType1/ (WITH "/" at the end of URL)

First URL is valid according the http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part2-url-conventions/odata-v4.0-errata02-os-part2-url-conventions-complete.html#_Toc406398088

The problem is: by default .NET OData clients leave such URLs without ending "/"/

### Assemblies affected
RESTier 0.5.0 and current source code compiled locally

### Reproduce steps
Create EF6 model with base type HierarchyRoot and Derived Types DerivedType1 and DerivedType2, map hierarchy as TPH, expose as entity set TablePerHierarchyEntitySet

### Expected result
http://server/api/restier/TablePerHierarchyEntitySet/Namespace.DerivedType1 should return only instances of type DerivedType1

### Actual result
Returns "HTTP Error 404.0 - Not Found" IIS error page 

### Additional details
Tested with Visual Studio 2015 Update 2 with IISExpress

**Comment by cilerler** [comment]
If you don't mind, would you please create a sample app on GitHub and share here so we can test it.  It would be very time consuming to re-generate the issue you are having otherwise.  I appreciate your co-operation.

**Comment by vvdev** [comment]
Try please: https://github.com/vvdev/RESTier-Derived-Types-test

VS 2015 Update 2, SQL Server 2014 LocalDB.

The situation is even funnier: if I use RESTier 0.5.0 nuget package (current state of code), then buth URLs return HTTP 404.
If I replace restier nuget binaries with binaries built by myself from source code downloaded yesterday (these binaries are included in solution under "Latest RESTier sources compiled" folder) - then first URL (WITHOUT "/") return 404, second (WITH "/") returns expected result.

Thanks for your response.

**Comment by chinadragon0515** [comment]
In a typical IIS configuration, the dot in this URL will cause IIS to return error 404. You can resolve this by adding the following section to your Web.Config file:

<add name="ExtensionlessUrlHandler-Integrated-4.0" path="*" verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0"/>
    

You should have a similar configuration in your path, just replace path with *, let me know if this does not work for you.

It is document in web api odata page, I will add this into RESTier document.
http://www.asp.net/web-api/overview/odata-support-in-aspnet-web-api/odata-v4/odata-actions-and-functions

**Comment by vvdev** [comment]
Thanks for advice.

There are good and bad news.

The good is: this config change fixed RESTier with binaries build from current source code.

The bad: this change broke WCF services implemented as Service.svc hosted in the same application.

Can you suggest anything to keep both RESTier and .svc WCF services operational?

**Comment by chinadragon0515** [comment]
1. nuget does not work as derived type support is added after 0.5 release.

2. I do not have any suggestions to keep both work now, I will ask around to see whether there is any solutions. Can I know what is broken in WCF services? Do you have something like exception stack? error message? 

thanks

**Comment by vvdev** [comment]
Thanks for your help.

2. Just "HTTP Error 500.0 - Internal Server Error" on any HTTP call to any .svc service

Do you have any idea, when next version will be published as nugget package?

**Comment by chinadragon0515** [comment]
For release plan, my current plan is release 0.6 in 3Q and it will still based on Odata .Net Libraries 6.x and WebAPI OData 5.x.

Then release first GA in 4Q which will be based on Odata .Net Libraries 7.x and WebAPI OData 6.x.

This is not commitment now, and sorry I can not give more specified date as I just start 0.6 release.

One item I want to mention, comparing with 0.5 release, we do not expect big changes on public API in 0.6 and first GA release. User should be able to migrate from 0.5 to later release comparing with migrating from 0.4 to 0.5.

**Comment by vvdev** [comment]
Thanks for clarification.

Still would be great if you can suggest how to keep RESTier and WCF .svc services both operational.

**Comment by chinadragon0515** [comment]
document is updated.

**Comment by chinadragon0515** [comment]
@vvdev I did some test today, 

I run http://localhost:33488/NorthwindDataService.svc/ and http://localhost:18384/api/Trippin/$metadata on the same IIS, I did not see any issue.

Can you upload your demo project which can recreate the issue and the configurations you have so I can take a look? thanks

**Comment by chinadragon0515** [comment]
Have not got response in one week, close the issue.
If you have new issues, open new issues, thanks.
