### ISSUE TITLE
Multiple types were found that match the controller named 'Restier'

### ISSUE THREAD

**Issue by lgadola** [OData/RESTier#445]
Exception is thrown:
{"Message":"An error has occurred.","ExceptionMessage":"Multiple types were found that match the controller named 'Restier'. This can happen if the route that services this request ('dwh/{*odataPath}') found multiple controllers defined with the same name but differing namespaces, which is not supported.\r\n\r\nThe request for 'Restier' has found the following matching controllers:\r\nMicrosoft.Restier.WebApi.RestierController\r\nMicrosoft.Restier.Publishers.OData.RestierController","ExceptionType":"System.InvalidOperationException","StackTrace":"   at System.Web.Http.Dispatcher.DefaultHttpControllerSelector.SelectController(HttpRequestMessage request)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"}

### Assemblies affected
0.5.0-beta

There is only one Restier controller defined

**Comment by chinadragon0515** [comment]
Seems this is caused by old package left on the system, runtime finds a controller name "Microsoft.Restier.WebApi.RestierController" which is not part of 0.5 release.

Search your folder and find dll named Microsoft.Restier.WebApi.dll, them remove that dll, the issue should be resolved.

**Comment by lgadola** [comment]
thanks!
