### ISSUE TITLE
Make Operation supports return entity type is different from binding parameter entity type

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#447]
Make Operation supports return entity type is different from binding parameter entity type.

If function returns non entity set type or non entity set collection, there is no issue.

Current in RESTier, method like "public Trip getPersonTrip(Person person)" is not allowed as the binding parameter will fail. 

Need to add this support.

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
