### ISSUE TITLE
How can I inject a repository into my controller?

### ISSUE THREAD

**Issue by lgadola** [OData/RESTier#450]
Could you please provide an example on how to use a repository in restier?
(say you use a framework like [URF](https://genericunitofworkandrepositories.codeplex.com/) and need to inject a repository/service into the EntityFrameworkApi controller. How can this be achieved?
Thanks!

**Comment by chinadragon0515** [comment]
I do not have an example now, also we focus on OData part.
I am not sure what you mean " inject a repository/service into the EntityFrameworkApi controller", EntityFrameworkApi is not a Web Api controller, the Restier controller is transparent from consumer.

Can you be more specified on what you want to inject here? like achieve which goal?
BTW, we are not expert on other part, I will suggest you ask on stackoverflow where there are experts on all domains, and people may help you.

**Comment by lgadola** [comment]
I see it is probably out of the scope of restier.
Thanks!
