### ISSUE TITLE
How can i $orderby/$filter on $count of $expanded?

### ISSUE THREAD

**Issue by iqmeta** [OData/RESTier#451]
Hi,
great project. started playing around, but 

any plans on 4.8 => http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part2-url-conventions.html or http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part2-url-conventions/odata-v4.0-errata02-os-part2-url-conventions-complete.html#_Toc406398162

currently => 
`~/odata/user?$orderby=temp_products/$count`
 => The method or operation is not implemented.

I can do 

`~/odata/user?$expand=temp_products($count=true)
`

and 

`~/odata/user?$expand=temp_products($count=true)&$top=13
`

result is almost usable => count/elements per item available 
`{ "temp_products@odata.count":2,"temp_products":[{},{}] }`

But how can I now $filter and/or $order this (pageable) desc on the count from the expanded? 

If not implemented, are there currently any suggestion to workaround on cases like this.

Kind regards.

**Comment by chinadragon0515** [comment]
For the item not supported, it will be added support with https://github.com/OData/WebApi/issues/194

For your case, you want to get a list of user, and for user, it is ordered by the number of temp_products and its  temp_products are expanded? If this is the case, we need to wait for the issue I mentioned been fixed.

If not, I will see whether there is any workaround.

**Comment by iqmeta** [comment]
thanks for the quick reply!

I guess you got it right.

It's a very common data situation for pageable data,
like simple customer to orders querys.

Eg. you have 1000 Customers, paging them by 50 per page, expand on orders and sort them on sum, or orders count per customer, maybe add a filter on region or country in cutomer, plus maybe a filter on total value per order.

Basically lots of pageable main data in a grid with sum or count from side tables.

Wasn't able to build a query like that yet..

**Comment by chinadragon0515** [comment]
I understand your request, it is planned for Web Api next release and did not see code change from restier view, so I close the issue now, and you can track the support with Web Api OData issue.
