### ISSUE TITLE
Redesign the model extend mechanism

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#457]
Now, when user wants to extend a model based on model builder from EF, he needs to use low level ODL lib code to extend the model, we want to make it easier, make ODataConversionModelBuilder accept an existing model, tracked with issue OData/WebApi#755

Also when user wants to add some new entity type and entity set, and these entityset and type are used by operation, the model extend will need to overwride some existing logic.

Need to make this part model simpler.

**Comment by chinadragon0515** [comment]
refer to comments on PR https://github.com/OData/RESTier/pull/448

**Comment by chinadragon0515** [comment]
The other part is in order to support something like in sample https://github.com/OData/ODataSamples/tree/master/RESTier/SpatialSample, the model builder need to Ignore some property needed by provider layer and need to add some property ignored by provider layer.

Need to simplify this kind model build.

**Comment by ivanko2000** [comment]
Pinging this as 'still relevant' in case anyone is listening... :)

**Comment by ivanakcheurov** [comment]
Please, could you drop a line regarding the feauture of RESTier exposing **Computed DB fields**?
EF exposes them with `.HasDatabaseGeneratedOption(DatabaseGeneratedOption.Computed);`

**Comment by robertmclaws** [comment]
We're going to totally redesign how this works in Restier 2.0 to make it far simpler than it is today. Closing this for now, thanks to everyone for your input.
