### ISSUE TITLE
Support ASP .NET core

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#464]
related Web APi Odata support is tracked with issue https://github.com/OData/WebApi/issues/229 

related ODL support https://github.com/OData/odata.net/issues/568

**Comment by mikepizzo** [comment]
This is a common request, but first we need to complete work to support .NET Core in the underlying WebAPI OData. 

Closing as duplicate.

**Comment by fireya** [comment]
Hello! Are there any plans on port to .net core? Dependent library is beta4 and stable enough...

**Comment by madansr7** [comment]
@fireya, as Mike said above, supporting WebAPI OData in .Net Core is our focus right now.

**Comment by weitzhandler** [comment]
@mikepizzo 
Hi there, any news?
Is there Restier support for ASP.NET Core already?

**Comment by weitzhandler** [comment]
@mikepizzo
OData has now been open for .NET Core for a while.
Please consider reopening this issue to discuss RESTier Core.

**Comment by robertmclaws** [comment]
V1 will not be on .NET Core. The routing changes required to support OData in .NET Core 3.0 means it's gonna be a little while before the base OData libraries support it. The Restier pipeline is not architected cleanly enough to be able to support .NET Core without a major rewrite. So our plan is to ship 1.0 on .NET Framework 4.8, and then build a brand-new, clean pipeline implementation on .NET Standard 2.0. We'll then be able to build a clean implementation designed from the get-go for .NET Core 3.0, and then attempt to backport that to Classic ASP.NET as well.

We'll be talking more about those plans as soon as we get v1 out the door.

**Comment by weitzhandler** [comment]
Really appreciate your input and thanks for the hard work!

**Comment by weitzhandler** [comment]
> The Restier pipeline is not architected cleanly enough to be able to support .NET Core without a major rewrite.

Even .NET Core 2.x? Do you believe it can be adapted without massive effort so it can be used from .NET Core projects? OData does support .NET Core.

**Comment by weitzhandler** [comment]
Hey @robertmclaws and thanks for your response.
I just sat now for an hour digging into the option of porting it to .NET Core. Feasible with some work. What's hard, is doing it while maintaining backwards compatibility to net4.8, EF6 and others.
I'd work on it if I wasn't sure you're working so hard and on a tight schedule to ship V1 for .NET Framework.

**Comment by robertmclaws** [comment]
Thanks @weitzhandler! I appreciate you looking into it. Once we ship 1.0, we'll do some API design to figure out what we want 2.0 to look like. Once we decide on that, we'd love to have you pick up some of the features and code them out.

To you and anyone else looking into .NET Core, please don't waste your time with the current codebase. I cannot be clear enough about this: We do not want to retrofit code prototyped just after .NET 4.0 was released onto .NET Core 3 and beyond. We're going to start from scratch and build a modern pipeline with modern tooling, and then pull the appropriate code INTO that. We can build a significantly better product that way, and do it in less time.

**Comment by weitzhandler** [comment]
Related: https://github.com/OData/WebApi/issues/1748
