### ISSUE TITLE
Allow customize query result before return like for update

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#467]
Expose an interface with method like "IQueryable OnQueryedResult(IQueryable originaresult)", and user can customize the result in this method before the result is final show to end user.

In this way, user can remove some value from result or change some value from result.

Before we implement this feature, OnFilter should work for most case, like if user to clear password before return, he can create a OnFilter like below

```
        protected IQueryable<Person> OnFilterPerson(IQueryable<Person> entitySet)
        {
            return entitySet.Select(p => new Person
            {
                PersonId = p.PersonId,
                UserName = p.UserName,
                FirstName = p.FirstName,,
                LastName = p.LastName,
                Password = null
            }).AsQueryable();
        }
```

**Comment by ivanko2000** [comment]
Great idea - it would address one of my use cases.

**Comment by chinadragon0515** [comment]
@ivanko2000 Can I know what's the user case, I did not add this label for this issue as we think most user should be able to use our OnFilter feature to customize the result. 
I want to know you case to see whether onFilter can meet your request, if not, I will increase priority of this issue, thanks.

**Comment by ivanko2000** [comment]
@chinadragon0515, sorry, I misunderstood the description - existing OnFilter is indeed sufficient for my needs.

**Comment by chinadragon0515** [comment]
@ivanko2000 that's fine, I updated the description when I reply to you this morning, we will not implement this feature until we see cases where onfilter can not achieve even we know like filter collection of string result is not support, but we do want see some real cases before we proceed.

**Comment by mikepizzo** [comment]
Looks like OnFilter may be sufficient for current scenarios?
