### ISSUE TITLE
Ability to call convention methods from C#

### ISSUE THREAD

**Issue by robertmclaws** [OData/RESTier#469]
We have a complex object model derived from a RESTier service that we are manipulating in a browser. Since Breeze and many other JS frameworks don't properly support OData V4 and/or batching, we want to use an Action to post that complex object to the service. Inside that action, we want to break the object apart and submit it to the different RESTier convention methods in C#, so that each object being inserted can hit the validation logic in OnXXXXInserting, etc. It would basically be a "poor man's batch".

I'm imagining code that looks like this:

``` csharp
    public partial class TestApi : EntityFrameworkApi<CorporationsDbContext>
    {
        public bool SubmitCorporation(Corporation corporation)
        {
            using (var transaction = new TransactionScope())
            {
                'Here is one option for what the function would look like
                this.InsertObject(corporation);
                foreach (var principal in corporation.Principals)
                {
                    'Here is another option
                    this.Execute(EntityFrameworkApiMethods.Insert, principal);
                }
                foreach (var image in corporation.Images)
                {
                    'Here is a third possible option.
                    this.PostObject("Images", image);
                }
                transaction.Complete();
            }
        }
    }
```

Is that something that is possible today? If not, is it something that can get in there? Thanks!

**Comment by rayao** [comment]
OData batch?

**Comment by chinadragon0515** [comment]
If batch does not work for you and you only want to call conversion based method, then based the conversion you want to call like OnInserting and OnInserted, you can do something like this (option 2 in your case)

```
                    var processor = context.GetApiService<IChangeSetItemProcessor>();
                    if (processor != null)
                    {
                        await processor.OnProcessingChangeSetItemAsync(context, item, cancellationToken);
                    }
```

But here you need to construct submit context and ChangeSetItem by your self.
Will this work for you?

**Comment by advancedrei** [comment]
@rayao, very few javascript frameworks properly support OData Batch, so batch won't work for us.

@chinadragon0515, this looks like it could work... How would you construct the submit context? Does the code in your example do that?

Thanks guys!

**Comment by chinadragon0515** [comment]
For SubmitContext, you can refer to class ApiContextExtensions, method SubmitAsync, that's place restier code create SubmitContext,  this the link of code https://github.com/OData/RESTier/blob/master/src/Microsoft.Restier.Core/ApiContextExtensions.cs#L464

And for changesetitem, this is a DataModificationItem, this is the place RESTier code create one for insert, https://github.com/OData/RESTier/blob/master/src/Microsoft.Restier.Publishers.OData/RestierController.cs#L163

If only call conversion method, you will not need to have all parameters provided, and key are entity set name and DataModificationItemAction for DataModificationItem instance.

**Comment by robertmclaws** [comment]
OK, I'm looking over this again, and I think I'm pretty close to being able to construct my own specific "batch" for my needs. The question is, if I'm passing in a regular object that is an entity, not an EdmEntityObject, how do I convert it into an EdmEntityObject?

Thanks!

**Comment by VikingsFan** [comment]
you mean construct a EdmEntityObject?

    IEdmEntityType entityType = model.SchemaElements.OfType<IEdmEntityType>().First(c => c.Name == "Customer");
    EdmEntityObject customer = new EdmEntityObject(entityType);
    customer.TrySetPropertyValue("ID", 3);
    customer.TrySetPropertyValue("Name", "Sam");

**Comment by robertmclaws** [comment]
Yes @vikingsfan, but I mean from an existing, prepopulated Entity.

```cs
Corporation corp = new Corporation();
corp.Name = "Some Name";
var entityCorp = new EdmEntityObject(corp);
```
It should literally be this easy.

**Comment by VikingsFan** [comment]
@robertmclaws but currently we can have one CLR type map to multiple entity type, so we can't support to construct a EdmEntityObject use a CLR type.

**Comment by mikepizzo** [comment]
It sounds like there is a solution for the initial issue, the remaining request is to have a simple way to construct the EdmEntityObject; right?

**Comment by robertmclaws** [comment]
We're handling this an entirely different way in my new framework, and will consider publishing it at some point. Basically, we just built Manager classes that handle RESTier interception methods, and then have our own `Insert(entity)` methods that call `OnInserting(entity); db.SaveChanges(); OnInserted(entity);` Works just fine and doesn't require changes to the core.
