### ISSUE TITLE
Support geo related functions.

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#470]
Query options not working will be a blocker for us. Also does restier implements EDM.Geography related methods? Please find description below from Odata blog (http://www.odata.org/blog/geospatial-properties/) : 

geo.distance
Geo.distance is a canonical function defined between points. It returns a distance, as defined above. The two arguments must use the same topology & CRS. The distance is measured in that topology. Geo.distance is one of the corresponding functions for points. Geo.distance is defined as equivalent to the OGC SF Distance method for their overlapping domain, with equivalent semantics for geographical points.
geo.intersects
Geo.intersects identifies whether a point is contained within the enclosed space of a polygon. Both arguments must be of the same topology & CRS. It returns a Boolean value. Geo.intersects is a canonical function for any implementation that includes both points and polygons. Geo.intersects is equivalent to OGC SF's Intersects in their area of overlap, extended with the same semantics for geographic data.
geo.length
Geo.length returns the total path length of a linestring. It returns a distance, as defined above. Geo.length is a corresponding function for linestrings. Geo.length is equivalent to the OGC SF Length operation for geometric linestrings, and is extended with equivalent semantics to geographic data.

refer to Web Api issue https://github.com/OData/WebApi/issues/779

Note : the sample in odata blog is incorrect, and the sample request should be like 
http://localhost:18384/api/Spatial/People?$filter=geo.distance(PointLocation,geography'SRID=0;Point(142.1 64.1)') gt 0

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
