### ISSUE TITLE
Api class in documentation

### ISSUE THREAD

**Issue by web265p3** [OData/RESTier#471]
I am new to RESTier and I just started to read the documentation. From the beginning the documentation talks about the "API-class", but I cannot find a class "AdventureWorksApi" after I followed the tutorial. This is pretty confusing...

**Comment by VikingsFan** [comment]
You can find sample about AdventureWorksApi here http://odata.github.io/RESTier/v0.6/#02-02-entity-set-filters-new, and use it like: 

    config.MapRestierRoute<AdventureWorksApi>(
                "AdventureWorksLT",
                "api/AdventureWorksLT",
                new RestierBatchHandler(GlobalConfiguration.DefaultServer));

**Comment by web265p3** [comment]
I read the example, but I did not know where that I had to put AdventureWorksApi in the route. Thanks - its working.

**Comment by VikingsFan** [comment]
Updated  20189e5
