### ISSUE TITLE
Add custom attribute to property

### ISSUE THREAD

**Issue by Spragalas** [OData/RESTier#474]
O want some custom logic which i would apply on properties. The way I want to do this is to get custom attribute from $metadata, but I can't find way to add custom attribute.

**Comment by chinadragon0515** [comment]
The model builder does not support custom attribute yet, can I know if there is a custom attribute, what you want to be in the model? Some custom annotation on the property?

But we do support that you can set any custom annotation in the model, you can do something like this,

                var trackGuidProperty = tripType.DeclaredProperties.Single(prop => prop.Name == "TrackGuid");
                var term = new EdmTerm("Org.OData.Core.V1", "Computed", EdmPrimitiveTypeKind.Boolean);
                var anno = new EdmAnnotation(trackGuidProperty, term, new EdmBooleanConstant(true));
                model.SetVocabularyAnnotation(anno);

Will this work for you?

**Comment by Spragalas** [comment]
I just want to add 'queryable' attribute.

Basically i am building custom filtering for my page, where user could build its own query. However I want to have some restriction on which properties are queryable on which are not. And I don't  want to store list of queryable  properties in javascript. So I thought metadata would be perfect place for that.

I guess your solution would, if only I knew where to implement that

**Comment by chinadragon0515** [comment]
When you said queryable, do you mean whether it can be used in $select query option or used in $filter query option or others?

If you mean $filter, then you can add [NotFilterable] attribute to the property, then model build will auto create a QueryableRestrictionsAnnotation for the property and it will not be able to used in $filter.
If you want to get the annotation by yourself, you can use code like edmModel.GetAnnotationValue<QueryableRestrictionsAnnotation>(edmProperty);

To set customized annotation you need to know the target of element in model you want to set annotation, then use code like model.SetAnnotationValue(edmProperty, new QueryableRestrictionsAnnotation(restrictions)); to set the annotation, and use edmModel.GetAnnotationValue<QueryableRestrictionsAnnotation>(edmProperty); to get the annotation.

Refer to https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/QueryableRestrictionsAnnotation.cs for the source of QueryableRestrictionsAnnotation.

**Comment by mikepizzo** [comment]
@Spragalas; please let us know if @chinadragon0515's reference doesn't address your needs.

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
