### ISSUE TITLE
Check property/action permission annotation before request

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#480]
Should check these annotation before operation.

```
<!--  Permissions  -->
<Term Name="Permissions" Type="Core.Permission" AppliesTo="Property ComplexType TypeDefinition EntityType EntitySet NavigationProperty Action Function">
<Annotation Term="Core.Description" String="Permissions for accessing a resource"/>
</Term>
<EnumType Name="Permission" IsFlags="true">
<Member Name="None" Value="0"/>
<Member Name="Read" Value="1"/>
<Member Name="Write" Value="2"/>
<Member Name="ReadWrite" Value="3"/>
<Member Name="Invoke" Value="4"/>
</EnumType>
```

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
