### ISSUE TITLE
Make cache in static property as DI service then can have per APi cache

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#485]
Cache like 

```
    private static ConcurrentDictionary<IEdmEntitySet, bool> concurrencyCheckFlags
        = new ConcurrentDictionary<IEdmEntitySet, bool>();

    private static ConcurrentDictionary<IEdmStructuredType, IDictionary<string, PropertyAttributes>>
        typePropertiesAttributes
        = new ConcurrentDictionary<IEdmStructuredType, IDictionary<string, PropertyAttributes>>();
```

Move them to DI

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
