### ISSUE TITLE
Support API version

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#486]
User may have different version of the API, need to add some support to the API version.

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
