### ISSUE TITLE
ASP.NET Core Support

### ISSUE THREAD

**Issue by RehanSaeed** [OData/RESTier#487]
Does this library support ASP.NET Core? What's the story with ODATA and ASP.NET Core in general, I have looked around and not found any mention of the two together.

**Comment by chinadragon0515** [comment]
Duplicate with https://github.com/OData/RESTier/issues/464.

The depended library has not support ASP.NET core yet, referto #464 for more detail.

BTW, can I know do you plan to run on Linux platform

**Comment by RehanSaeed** [comment]
Thanks, I read those threads about a month ago, looks like no progress has been made.

We are not running on Linux yet but we do plan to long term. Our only blocker left is StackExchange.Redis.

**Comment by cilerler** [comment]
@RehanSaeed https://www.nuget.org/packages/Microsoft.Extensions.Caching.Redis.Core/
