### ISSUE TITLE
If there is reference, and navigation property is nullable, the key will be set as nullable.

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#492]
Like a Person has ID as key and a navigation property BestFriend and it is nullable, then ID of person is set as nullable. refer to https://github.com/OData/WebApi/issues/756  for more detail.

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
