### ISSUE TITLE
Make RESTier work with EF without CLR class

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#494]
Refer https://github.com/OData/RESTier/issues/481, comments from @moander 

I've been doing some research on how to implement a "database only" feature in RESTier but that has proven to be more difficult than first thought.

OData is a great way to expose a database, and a database server is a great place to store database schemas, so I thought it would be a good idea to be able to expose it directly without adding an extra layer of manual labor maintaining POCO classes.

So my feature request is something like this :)

`services.AddService<IModelBuilder>(new ModelBuilder("Data Source=server; Initial Catalog=DatabaseToExpose"));`

What I'm trying to do is to expose a database as-is using only a connection string, and without having to update/build/publish the web project after altering the db.

I was able to do it, but the solution was way to dirty to consider for production ;)

Extracting csdl/ssdl/msl from a connection string was straight forward using the built-in EntityStoreSchemaGenerator.

Loading the schema into a DbContext was also straight forward using the metadata=.. parameter in the EF connection string.

Then you could (not that anyone should;) do a new System.Data.Entity.DbContext("...") directly without even requiring a class MyDbContext : DbContext.

Running queries against the context will fail because it can't find any CLR objects backing it's schema. And I did not find any built-in stuff that could make them for me either, so from here the work-around get's really ugly.

The default T4 templates does not support pre-processing so I had to embed the whole thing, output them to disk at runtime, run the T4 transformer using the EDMX generated in the first step, read back the outputted files and compile them using the CSharpCompilation class.

Expose the DB using Restier

This is a lot of work when all you want to do is to expose a DB using OData ;)

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
