### ISSUE TITLE
Support some of the other attributes such as read-only

### ISSUE THREAD

**Issue by liqian19891011** [OData/RESTier#5]
This needs to define clearly. oCan consider prioritizing EF code-first

**Comment by challenh** [comment]
these EF attributes are verified in RESTier (either reflected on OData Edm or no effect )： Table, Column, NotMapped, Computed, ConcurrencyCheck ,Required,MaxMinLength,Timestamp.

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
