### ISSUE TITLE
Filter rules for all entity sets

### ISSUE THREAD

**Issue by moander** [OData/RESTier#501]
Is it possible to apply logic to all entities?

``` csharp
    public class AdventureWorksApi : EntityFrameworkApi<AdventureWorksContext>
    {
        public IQueryable<T> OnFilter<T>(IQueryable<T> entitySet)
        {
            return entitySet.Take(100).AsQueryable();
        }
    }
```

Thanks for all your great work!

**Comment by chinadragon0515** [comment]
You can not do this in APi class, but you can define your own class to implement this,
1. Implement a class like https://github.com/OData/RESTier/blob/master/src/Microsoft.Restier.Core/Conventions/ConventionBasedQueryExpressionProcessor.cs,  and implement IQueryExpressionProcessor.

2. Implement filter logic you want in method  public Expression Process(QueryExpressionContext context), add any filter logic to any entityset based on your request.

3. register it as DI service like https://github.com/OData/RESTier/blob/master/test/ODataEndToEnd/Microsoft.OData.Service.Sample.Trippin/Api/TrippinApi.cs#L579-L587, same as CustomizedSubmitFilter.

Then this will add filter you define in your IQueryExpressionProcessor.

**Comment by moander** [comment]
@chinadragon0515 Thanks. I will check it out.

Btw. Do you know if there is an easy way to set a global default on number of rows returned by a query when $top is not specified? 

Using `MaxTop=10` on `ODataValidationSettings`  throws on`/db/table?$top=11 `, but `/db/table` will return all available rows

**Comment by chinadragon0515** [comment]
@moander in the next release, we have greatly improve the way we control the query options include MaxTop, the default value if max of int, but you can change it via call config.MaxTop(10) before call configure route. Refer to http://odata.github.io/WebApi/#13-01-modelbound-attribute for more detail.

Note max top is only used to validate the top value specify by end user, it does not control the rows returned.

If you want to control the number of rows returned even there is no top specified, then you can use page attribute. refer to same link for more detail.

And note, the next release is not ready yet, we plan to have first beta released this week.
You can refer to http://chinadragon0515.github.io/RESTier/v1.0/#06-09-1-0-0 to have a preview of the release content.

**Comment by mikepizzo** [comment]
It appears that @chinadragon0515 addressed the open questions/issue. Please feel free to reactivate, or create a new issue, if there are remaining questions.

**Comment by papaja** [comment]
@chinadragon0515 I've read your answer but ConventionBasedQueryExpressionProcessor.cs is to complex. What would be simple implementation to add Top(10) AFTER all user filters are set?
