### ISSUE TITLE
Set Container properties w/o overriding ModelBuilder

### ISSUE THREAD

**Issue by robertmclaws** [OData/RESTier#504]
I have an API project where I have multiple RESTier contexts living at the same API root domain. It would be nice if I could have the following code:

``` cs
[Container(Namespace = "MyNamespace", ContainerName = "MyContainer")]
public partial class MyApi : EntityFrameworkApi<MyDbContext>
{
}
```

This would let me control properties on ModelBuilder without having to override the entire process just to set 2 properties.

Thanks!

**Comment by chinadragon0515** [comment]
Can I know what you means multiple RESTier contexts? Do you mean multiple Api class like MyApi1, MyApi2?

For each Api, you want to share model builder as logic are common except some properties?  How you want these properties are used? 
Will some customized defined attribute works for you?  Like you define the attribute, set the attribute and use values in attribute in model builder defined by you?

**Comment by robertmclaws** [comment]
I have one WebAPI project, let's call it MyProject. Inside it, I have two RESTier EntityFrameworkApi classes that are tied to two *different* `DbContext`s. Let's call them MyApi1 and MyApi2.

If I point the OData V4 Client T4 code generators at these two different APIs, they will both generate a class called "Container" that inherits from `DataServiceContext`. If I put those in the same namespace for the Client project, they won't compile because they will overlap.

I want to be able to change the name of the Container without having to implement all the code that RESTier makes me implement to override the ModelBuilder. I shouldn't have to implement 15 lines of code to change one property.

Using that description, as well as the example from my first post, the scenario I described would look like this:

```cs
[Container(Namespace = "MyNamespace", ContainerName = "MyApi1Container")]
public partial class MyApi1 : EntityFrameworkApi<MyDbContext1>
{
}

[Container(Namespace = "MyNamespace", ContainerName = "MyApi2Container")]
public partial class MyApi2 : EntityFrameworkApi<MyDbContext2>
{
}
```

Under the covers, when you are constructing your model internally, you would look to see if the class was decorated with the `ContainerAttribute`. If it was, you would set the Namespace and Container name properties for me, if the values were not null.

Does that make sense?

**Comment by chinadragon0515** [comment]
OK, I see, the expectation is some interface which allows user to overwrite namespace and container name for the default built model, for namespace, we already have issue https://github.com/OData/RESTier/issues/442 to cover this, and we will consider the container for this part.
We plan to do this with https://github.com/OData/RESTier/issues/457.

This is not planned in 1.0 release now, we are welcome and appreciate contribution on this.

**Comment by mikepizzo** [comment]
It looks like several folks requested this, but without an external contribution it was outside of the scope for 1.0.

**Comment by robertmclaws** [comment]
Will address this in a future release.
