### ISSUE TITLE
Patch a entity complex's complex property should only update the provided properties

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#508]
This is related to issue #505 

If we have entity type Person and complex type Location and City.

The person has a property whose type is Location, and Location has a property whose type is City, when patch person with some properties of City,  only the provided properties of City should be updated and other properties should keep unchanged.

If user is Put the person, then City should have default value (maybe null) for the properties which user does not provide the value.

**Comment by mikepizzo** [comment]
current behavior is non-compliant and could lead to unexpected data loss.

**Comment by robertmclaws** [comment]
Let's write a unit test to make sure the fix in WebAPI was picked up.

**Comment by robertmclaws** [comment]
@mikepizzo It looks like the "Patch" enum is not available on [System.Net.HttpMethod](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpmethod?view=netframework-4.8#properties) right now. So how are you folks handling this?

**Comment by mikepizzo** [comment]
Although there is not a static defined for PATCH, you can do new HttpMethod("PATCH") to specify the Patch method.

**Comment by robertmclaws** [comment]
Happy to say that I believe this issue to be resolved, and the unit test for PATCH passes. 🎉🎉🎉

**Comment by mikepizzo** [comment]
Awesome!
