### ISSUE TITLE
Batch/bulk insert/delete entities

### ISSUE THREAD

**Issue by cilerler** [OData/RESTier#509]
What is the best approach to insert/delete 10K+ entities through RESTier?
### Assemblies affected

RESTier 0.6.0

**Comment by chinadragon0515** [comment]
We did not do something special on this part, I just comments based on my previous experiences and OData protocol

1. For delete, I will suggestion an action that will accept some condition like "where lastModifiedDate < 2010/1/1", and then in the action method, you will get the parameter by yourself, construct a LINQ query and execute against DB.

2. For insert, it will depend on the entities, if entities does not have common properties value, then you'd can use batch request, and also enable zip for request content at http server layer.
If entities properties have common value, you can build customized JSON or even string parameter, create an action to accept a string parameter, and parse the parameter to construct entity by yourself.

**Comment by cilerler** [comment]
Thank you for the detailed response, can you give me a link for **batch request with _RESTier_** sample?

**Comment by chinadragon0515** [comment]
You refer to https://github.com/OData/RESTier/blob/master/test/ODataEndToEnd/Microsoft.OData.Service.Sample.Northwind.Tests/ODataFeedTests.cs#L76-L171

Or https://github.com/OData/RESTier/blob/master/test/ODataEndToEnd/Microsoft.OData.Service.Sample.Tests/BatchTests.cs

Let me know if you need more information.

**Comment by cilerler** [comment]
I appreciate for the reply, will look into this today/tomorrow and will get back to you.

**Comment by cilerler** [comment]
Some how, I forgot to return this message.  I apologize for that 😞
2nd one was the one which helped me.  Thank you! 🍟 🍺
