### ISSUE TITLE
Unable to use odata $select, $expand, and others by default

### ISSUE THREAD

**Issue by randbrown** [OData/RESTier#511]
Followed the tutorial at http://odata.github.io/RESTier/#01-02-Bootstrap

Unable to get odata $select, $filter, $expand,  and so on to work. 

Example of $select not working:
URL: 
http://localhost:5647/api/AdventureWorksLT/Customers?$select=FirstName
Response: 
{"error":{"code":"","message":"The property 'FirstName' cannot be used in the $select query option."}}

Example of $expand not working
URL:
http://localhost:5647/api/AdventureWorksLT/Customers?$expand=CustomerAddresses
{"error":{"code":"","message":"The property 'CustomerAddresses' cannot be used in the $expand query option."}}

### Assemblies affected
RESTier 1.0.0-beta  

### Reproduce steps
Follow step 1.2 here: 
http://odata.github.io/RESTier/#01-02-Bootstrap
I also received the same error when downloading the sample from here:
https://github.com/OData/ODataSamples/tree/master/RESTier/AdventureWorksLTSample

### Expected result
Expected to be able to use $select and $expand

### Actual result
Unable to use $select, $expand, and other odata features.

**Comment by chinadragon0515** [comment]
I will update the sample and document.

In the meanwhile, you can add this before register the route

// enable query options for all properties
            config.Filter().Expand().Select().OrderBy().MaxTop(null).Count();

More details, starting from 1.0.0 release, we have more control on query options like which properties can be selected or expanded, by default, it is disabled. And user can have more setting on the CLR class or properties to allow properties to be selected or expanded.

Refer to link http://odata.github.io/WebApi/#13-01-modelbound-attribute for more details.
With the configuration I paste above, it will enable query,select on all properties.

**Comment by chinadragon0515** [comment]
both sample and documents updated, close the issue.

If you have more issues, help to let me know, thanks.
