### ISSUE TITLE
How to set 'MaxExpansionDepth' query option in RESTier 0.6

### ISSUE THREAD

**Issue by ivanko2000** [OData/RESTier#512]
A question rather than an issue report: how does one set 'MaxExpansionDepth' query option in RESTier 0.6? This is in context of this error:
`The request includes a $expand path which is too deep. The maximum depth allowed is 2. To increase the limit, set the 'MaxExpansionDepth' property on EnableQueryAttribute or ODataValidationSettings.`

I tried several variants without success.

**Comment by chinadragon0515** [comment]
You can refer to http://odata.github.io/RESTier/#02-08-Customize-Query

or https://github.com/OData/RESTier/blob/master/test/ODataEndToEnd/Microsoft.OData.Service.Sample.Trippin/Api/TrippinApi.cs#L574-L590

Also note this is for 1.0, and 0.6 is same. thanks.
