### ISSUE TITLE
Add reference update support for sample service in odata.org

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#513]
Add reference update support for sample service in odata.org

like support this request
POST http://services.odata.org/TripPinRESTierService/People('fabioPintos')/Friends/$ref HTTP/1.1

It also passes an ID that does not contain the session, so I also wonder if that causes trouble:
{"@odata.id":"http://services.odata.org/TripPinRESTierService/People('taniaPintos')"}

Also update the code in odatasamples

**Comment by mirsking** [comment]
This is fixed by PR #515, now we can use $ref to GET/POST/DELETE friends of people, and also GET/PUT/DELETE BestFriend of people.
Session ID is handled for request URI to ensure POST/PUT to modify the entities in the same DataStore instance.
