### ISSUE TITLE
OnFilter<T> vs EF.DynamicFilters

### ISSUE THREAD

**Issue by a2dude** [OData/RESTier#516]
I currently have a multi tenant app which uses EF.DynamicFilters (Github) to isolate one tenant from another.  Is the OnFilter mechanism in Restier suitable / adequate to provide the same functionality if I switch to Restier?

**Comment by chinadragon0515** [comment]
I think Yes, onfilter is applied to every query of the entity type.

**Comment by mikepizzo** [comment]
Closing, as it appears this has been resolved. Let us know if you are encountering problems.
