### ISSUE TITLE
Expand is not working when calling an entity set bound operation.

### ISSUE THREAD

**Issue by vacuette** [OData/RESTier#517]
Expand is not working properly when calling an entity set bound operation.
### Assemblies affected

RESTier 0.6.0.0  
### Reproduce steps

Create an entityset bound operation:

```

[Operation(Namespace = "CSv2Api", IsBound = true, EntitySet = "Orders")]
public IQueryable<Order> GetByDate(IEnumerable<Order> orders, DateTimeOffset dateFrom, dateTimeOffset dateTo)
        {
            var orders1 = (from x in context.Orders
                          .Include("Customer")
                          where
                            (dateFrom == null || dateFrom == DateTimeOffset.MinValue || x.collectionDate >= dateFrom)
                            && (dateTo == null || dateTo == DateTimeOffset.MaxValue || x.collectionDate <= dateTo)
                            && x.removedDate == null
                          select x).AsQueryable<Order>();

            return orders1;
        }
```

Call it:

GET http://localhost:5586/api/CSv2/Orders/CSv2Api.GetByDateA(dateFrom=0001-01-01T00%3A00%3A00Z,dateTo=2016-09-16T13%3A24%3A09.0358338%2B02%3A00)$expand=Customer HTTP/1.1
Accept: text/html, application/xhtml+xml, image/jxr, _/_
Accept-Language: es-ES,es;q=0.5
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393
Accept-Encoding: gzip, deflate
Host: localhost:5586
Connection: Keep-Alive
### Expected result

We expected to obtain an "Order" collection with "Customer" property filled. Just as happened when using an unbound function with the same purpose.
### Actual result

"Customer" property is not included in "Order" entities we get.
### Additional details

The same operation as unbound, is working fine:

```
[Operation(Namespace = "CSv2Api", IsBound = false, EntitySet = "Orders")]
        public IQueryable<Order> GetOrdersByDate(DateTimeOffset dateFrom, DateTimeOffset dateTo)
        {
            var orders1 = (from x in context.Orders
                          .Include("Customer")
                          where
                            (dateFrom == null || dateFrom == DateTimeOffset.MinValue || x.collectionDate >= dateFrom)
                            && (dateTo == null || dateTo == DateTimeOffset.MaxValue || x.collectionDate <= dateTo)
                            && x.removedDate == null
                          select x).AsQueryable<Order>();

            return orders1;
        }

```

GET http://localhost:5586/api/CSv2/CSv2Api.GetOrdersByDateA(dateFrom=0001-01-01T00%3A00%3A00Z,dateTo=2016-09-16T13%3A24%3A09.0358338%2B02%3A00)$expand=Customer HTTP/1.1
Accept: text/html, application/xhtml+xml, image/jxr, _/_
Accept-Language: es-ES,es;q=0.5
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393
Accept-Encoding: gzip, deflate
Host: localhost:5586
Connection: Keep-Alive

In this case we get full-filled entites.

**Comment by chinadragon0515** [comment]
RESTier 1.0.0 has the same issues (note to created, need to make operation source has includes for expand).

@vacuette we are busy on some other items now, the response to this issue will be slow, we are appreciated any contributions on this.

**Comment by vacuette** [comment]
Thanks a lot for your fast response. Any useful information about it I'd find out, it will be a pleasure for us to share it and contribute :)

**Comment by mikepizzo** [comment]
Would still love to see a contribution for this.

**Comment by robertmclaws** [comment]
From @jspuij:

> I’ve actually had a look at this and I feel it cannot be solved unless we also fix #365 as the OperationSegment should be executed as part of the Query Building process. Now the query is already executed when you actually get to the last segment (which is the operation). No way to change the returned collection type anymore, so expand or include will not work here…
> 
> The best way to fix this is inside RestierQueryBuilder where there is now an EmptyHandler for Operation Segments… But there is no async support there and a lot of necessary instances are missing so it requires major refactoring…

Because of that, I don't think we'll be able to support this until V2.

**Comment by robertmclaws** [comment]
Hey folks! I know this issue has been open for a while, but when we were reviewing this issue with Microsoft, we noticed that the query URL was not correct. 

The url provided was: http://localhost:5586/api/CSv2/CSv2Api.GetOrdersByDateA(dateFrom=0001-01-01T00%3A00%3A00Z,dateTo=2016-09-16T13%3A24%3A09.0358338%2B02%3A00)$expand=Customer

but there is a question mark missing before the dollar sign. Would it be possible to check to see if it works with the question mark in the correct place, please? Thanks so much!

**Comment by mikepizzo** [comment]
It looks like this is still an issue that I can repro in Trippin:

Returns PlanItems:
https://services.odata.org/TripPinRESTierService/People('russellwhyte')/Trips?$expand=PlanItems

Doesn't return PlanItems:
https://services.odata.org/TripPinRESTierService/me/Trippin.GetFriendsTrips(userName='russellwhyte')?$expand=PlanItems

**Comment by mikepizzo** [comment]
Took me a while to track this down. It works with a FunctionImport, but not a bound function.

The Issue here is that RESTier/WebAPI won't serialize the expanded content if it doesn't have a navigationSource.

The navigation source is obtained from the operation definition -- for function and action imports, this is done through the "EntitySet" attribute property. For bound operations you technically can't specify an entity set (since we don't have references from the schema elements into the entity container), you can only specify a path from the binding parameter (although we do support binding to a particular entity set in WebAPI internally, that mechanism is not exposed. hmmm....). Instead, you bind the results of an entity-valued bound operation through an entity set path, which specifies the path from the binding parameter to a navigation property bound to an entityset (or just the binding parameter, if result comes from the same entity set as the binding parameter).

We don't currently have a way in RESTier to set the entityset path for a bound operation.  We have some default logic that sets the target entityset for the response to the same entityset as the binding parameter, but that fails unless the return type happens to be the same type as the binding parameter.

I have a PR to add the ability to set an EntitySetPath for a bound operation.  You can then address this by annotating the bound function as:

[Operation(Namespace = "CSv2Api", IsBound = true, EntitySetPath = "orders")]
public IQueryable<Order> GetByDate(IEnumerable<Order> orders, DateTimeOffset dateFrom, dateTimeOffset dateTo)
        {
            var orders1 = (from x in context.Orders
                          .Include("Customer")
                          where
                            (dateFrom == null || dateFrom == DateTimeOffset.MinValue || x.collectionDate >= dateFrom)
                            && (dateTo == null || dateTo == DateTimeOffset.MaxValue || x.collectionDate <= dateTo)
                            && x.removedDate == null
                          select x).AsQueryable<Order>();

            return orders1;
        }

**Comment by robertmclaws** [comment]
So this is a situation where I felt like we were exposing too much of OData's underlying semantics to the end user. While it is technically true that you can't specify the EntitySet in bound operations, from a functional standpoint the `EntitySet` string is trying to assist the projection system in narrowing the scope of the return type to be able to apply additional LINQ queries to the results.

From that standpoint, forcing people to remember which string parameter to use in which situation (much like the concept of "side effects") seems unnecessary.

So I removed the extra string parameter and adjusted the code to use the `EntitySet` parameter differently between bound and unnbound functions. The end result now looks like this:
```csharp
[Operation(Namespace = "CSv2Api", IsBound = true, EntitySet = "orders")]
public IQueryable<Order> GetByDate(IEnumerable<Order> orders, DateTimeOffset dateFrom, dateTimeOffset dateTo)
{
    var orders1 = (from x in context.Orders
                  .Include("Customer")
                  where
                    (dateFrom == null || dateFrom == DateTimeOffset.MinValue || x.collectionDate >= dateFrom)
                    && (dateTo == null || dateTo == DateTimeOffset.MaxValue || x.collectionDate <= dateTo)
                    && x.removedDate == null
                  select x).AsQueryable<Order>();

    return orders1;
}
```
Now, whether `IsBound` is specified or not, the developer should get the behavior they were expecting, without needing to understand the underlying semantics. Open to feedback if anyone thinks this is the wrong approach. Thanks!

**Comment by mikepizzo** [comment]
@robertmclaws -- the question is, does your change work when the returned entities are not from the same entityset as the binding parameter, but as one of the entity sets that a corresponding navigation property is bound to.  For example, for all orders within a certain date range, return the customers associated with those orders (as a collection of customers coming from the appropriate customers entity set).

For example:
~~~c#
[Operation(Namespace = "CSv2Api", IsBound = true, EntitySet = "customers")]
public IQueryable<Order> GetCustomersForOrdersByData(IEnumerable<Order> orders, DateTimeOffset dateFrom, dateTimeOffset dateTo)
{
    var customers = (from x in context.Orders.
                  where
                    (dateFrom == null || dateFrom == DateTimeOffset.MinValue || x.collectionDate >= dateFrom)
                    && (dateTo == null || dateTo == DateTimeOffset.MaxValue || x.collectionDate <= dateTo)
                    && x.removedDate == null
                  select x.Customer).AsQueryable<Order>();

    return customers;
}
~~~

**Comment by robertmclaws** [comment]
Yeah that's one think I want to chat about tomorrow... my knowledge of bound functions is weak, so I could be totally wrong. I want to build out our Bound function E2E tests to cover these types of situations.
