### ISSUE TITLE
Document section 2.7 is incorrect

### ISSUE THREAD

**Issue by hannespreishuber** [OData/RESTier#518]
*Short summary (3-5 sentences) describing the issue.*  
the .context.Filter() extension method doenst compile. After comparing it with the advantureworksLT Sample there is a package diffrence in Microsoft.ASPNET.Odata. Update Package with nuget fails

ndestens eine nicht aufgelöste Paketabhängigkeitseinschränkung wurde in der vorhandenen Datei "packages.config" erkannt. Alle Abhängigkeitseinschränkungen müssen aufgelöst werden, um Pakete hinzuzufügen oder zu aktualisieren. Wenn diese Pakete aktualisiert werden, kann diese Meldung ggf. ignoriert werden, wenn die folgenden Fehler den aktuellen Paketvorgang nicht blockieren: 'Microsoft.AspNet.OData 5.9.1'
Abhängigkeiten können nicht aufgelöst werden. "Microsoft.AspNet.OData 6.0.0' ist nicht mit 'Microsoft.Restier.Publishers.OData 0.6.0 Einschränkung: Microsoft.AspNet.OData (>= 5.9.1 && < 6.0.0)' kompatibel.
=
### Assemblies affected
*Which assemblies and versions are known to be affected e.g. RESTier 0.4.0-rc2.*  
Microsoft.ASPNET.Odata

### Reproduce steps
*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*  

### Expected result
*What would happen if there wasn't a bug.*  

### Actual result
*What is actually happening.*  

### Additional details
*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by chinadragon0515** [comment]
RESTier 0.6 is working with Web Api OData 5.x, you can not upgrade WAO to 6.0.0 if you are using restier 0.6.0.

RESTier 1.0.0 will work with WAO 6.0.0, and 1.0.0 beta was released weeks ago, and 1.0.0 (First GA) will be released soon.

Let me know if you have any more questions or comments.

**Comment by hannespreishuber** [comment]
thanks for clarificaton.
How to figre out within seconds that a Filter() Function extension, just exists in a spezific beta of Restier?
-Hannes

**Comment by hannespreishuber** [comment]
missing SetUrlConventions in Microsoft.aspnet.odata 6, was there in 5.9
described in doc for Restier 1

**Comment by chinadragon0515** [comment]
Our sample code will always update to the newest release version. 
For restier 0.6, it depends on WAO (Web API OData) 5.x, and RESTier 1.0 depends on WAO 6.x.

WAO 6.x is a breaking changes, all the interfaces changes from WAO will change in RESTier.

You can refer to http://odata.github.io/WebApi/#13-01-modelbound-attribute for the changes from WAO.

Specified to SetUrlConversions will be changed to "config.SetUrlKeyDelimiter(ODataUrlKeyDelimiter.Slash);"

Document need to updated.

**Comment by chinadragon0515** [comment]
Document is updated, close the issue.
