### ISSUE TITLE
Submit Logic - Authorization and Plug in user logic not being called 

### ISSUE THREAD

**Issue by randbrown** [OData/RESTier#520]
Docs section 2.3 does not appear to work with 1.0.0-beta.  
```
CanDelete<EntitySetName>
On<Insert|Updat|Delet|Execut><ed|ing><EntitySetName|ActionName>
```
None of these appear to be running in my tests.

### Assemblies affected
RESTier 1.0.0-beta

### Reproduce steps
Follow docs section 2.3

### Expected result
Expect protected methods to be called

### Actual result
Methods do not get called.

### Additional details
I was able to work around it by using Customized Submit as described in section 2.9.   However, I would expect the approach in 2.3 to work as well.

**Comment by chinadragon0515** [comment]
Can I know which method does not work? How you define the method?

I double check and verify, Can delete works well, we also have test cases cover this, you can refer to 

APi 

https://github.com/OData/RESTier/blob/master/test/ODataEndToEnd/Microsoft.OData.Service.Sample.Trippin/Api/TrippinApi.cs#L569-L572

And test cases
https://github.com/OData/RESTier/blob/master/test/ODataEndToEnd/Microsoft.OData.Service.Sample.Tests/TrippinE2ETestCases.cs#L1112-L1123

**Comment by randbrown** [comment]
Resolved it.  My methods were marked "protected internal".  I removed the internal and now it is working.  Sorry. 

FYI, I had used the code sample at http://restier.readthedocs.io/en/latest/server/method-authorization/
which must be wrong/outdated. I'm not sure if that site is maintained or not, but it shows up high in google results.

**Comment by robertmclaws** [comment]
Sorry about that, that particular website is a documentation site that I built (as an outsider) because I found the official documentation too difficult. I will try to update what's there for 1.0 this week.
