### ISSUE TITLE
NuGet Packages are not built properly.

### ISSUE THREAD

**Issue by robertmclaws** [OData/RESTier#528]
### Problem

The NuGet packages are built using the "pack" command against the .csproj files themselves, resulting in the most bare-bones possible package file. These package files do not contain any information about Restier as a product, nor do they contain the source files to make debugging issues easier.
### Solution

Each assembly needs a proper .nuspec file so that more details about the product can be added, like decsriptions, tags, and the like. These new .nuspec files also need to be modified to contain the source files, so that .symbols.nuspec files can be automatically generated and submitted to NuGet.

**Comment by chinadragon0515** [comment]
Can I know what's the information are missed? We use Nuget package explorer to validate the package before we deliver, We do build package based on nuspec. 
![image](https://cloud.githubusercontent.com/assets/12759740/18896962/a4d671fc-8558-11e6-9cd8-7e70e05e3d37.png)

For the source code, I do not think it is a good practice to make it part of product dll. We upload symbols file to https://nuget.smbsrc.net which is the new location for nuget package source files.

**Comment by robertmclaws** [comment]
I've actually partially fixed this issue in PR #560. I updated the batch file that builds the NuGet packages to let you pass in the version number into the command, as well as automatically build the Symbol packages too. The "push" command will automatically push the Symbols packages to the right place for it to work during debugging.

Since the projects now have NuSpec files, I'm going to close this issue.
