### ISSUE TITLE
No namespace for functions

### ISSUE THREAD

**Issue by liqian19891011** [OData/RESTier#53]
In the current implementation of a function, the namespace should be added
``` [ODataRoute("Products/Microsoft.Restier.Samples.Northwind.Models.MostExpensive")] ```

The Web API OData 5.4 had an extension to solve this problem, after RESTier integrate with the new version of Web API OData, this should be resolved.

**Comment by congysu** [comment]
This is for our sample project.

**Comment by congysu** [comment]
Related PR https://github.com/OData/WebApi/pull/338 & commit: https://github.com/OData/WebApi/commit/3c2f90ec7ca407ed9ba2be96330036fa513ba4a3
