### ISSUE TITLE
Code samples needing to be fixed on the Getting Started tutorial for Restier 0.6.0

### ISSUE THREAD

**Issue by albertosilva** [OData/RESTier#531]
I've found two things that seem to need to be fixed in the [Getting Started tutorial ](http://odata.github.io/RESTier/v0.6/)for Restier 0.6.0.

**Chapter 2.5 Model Building**
On the "Build an initial EDM model" section's sample, the GetModelAsync method receives a InvocationContext type as the 1st parameter, but should receive a ModelContext type.
![restier060_gs_1](https://cloud.githubusercontent.com/assets/5349774/18951038/dab217c6-863a-11e6-9d4f-bf221d550d8c.png)

**Chapter 2.8 Customize Query**
On the "Customized Auhorize Logic" subsection's sample of the "2. Customize Query Logic" section,
Instead of...

```
            return base.ConfigureApi(services)
                .AddService<IQueryExpressionInspector, CustomizedInspector>();
```

...there should be...

```
            return base.ConfigureApi(services)
                .AddService<IQueryExpressionAuthorizer, CustomizedAuthorizer>();
```

![restier060_gs_2](https://cloud.githubusercontent.com/assets/5349774/18951037/daafc6d8-863a-11e6-8e45-4a0ad3619696.png)

**Comment by chinadragon0515** [comment]
Yeah, we will update in docoument 1.0, and in 1.0, the ConfigureApi method has been changed to static method.

We are warmly welcome any contributions.

**Comment by mikepizzo** [comment]
This is a trivial fix, still in the docs, that we need to address before release.
