### ISSUE TITLE
Trippin sample service has an issue with any filter.

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#532]
From google discussion, this is an error

Hi all,

I'm using TripPinService, and want to select all people who don't have any trips.

Query: http://services.odata.org/V4/(S(ex4kdfkzz3oewkhos1trvgyk))/TripPinServiceRW/People?$filter=not(Trips/any())

But, it returns 500 Internal Server Error. {"error":{"code":"InternalServerError","message":"No generic method 'Any' on type 'System.Linq.Enumerable' is compatible with the supplied type arguments and arguments. No type arguments should be provided if the method is non-generic. "}}

Is this a bug in the service or my query?

Thanks,
Suvidha.

**Comment by mikepizzo** [comment]
This is failing because the any() operator has no body.  The following should work:
http://services.odata.org/V4/(S(ex4kdfkzz3oewkhos1trvgyk))/TripPinServiceRW/People?$filter=not(Trips/any(t:true))
