### ISSUE TITLE
Trouble understanding and getting tutorial working.

### ISSUE THREAD

**Issue by jc1231** [OData/RESTier#534]
Using the page http://odata.github.io/RESTier/ to start playing with RESTier.

I understand that RESTier is built on-top of oData but which version 3 or 4?

One of the first steps says to add "config.Filter().Expand().Select().OrderBy().MaxTop(null).Count();" line to your WebApiConfig but the Filter() extension method doesn't exist. So which library/namespace does this exist in?

I have an existing C# WebAPI 2.2/EF6 project with some existing endpoints.

I also using the EntityFrameworkApi<> object and can hit the /$metadata endpoint and it returns all my entity sets but I get a 404 trying to GET any api/entity.

I'm just kind of lost as the tutorial is very vague.

Is there an updated version of the tutorial or some other coherent resources available?

Also, is RESTier of production quality or still in a "beta" phase?

Thanks

**Comment by chinadragon0515** [comment]
1. It is for OData v4
2. You can refer to some end to end samples in link https://github.com/OData/ODataSamples/tree/master/RESTier/
3. We release first beta for GA, we are waiting for more feedback before we release official release. 
Any comments/suggestion are highly appreciated.

**Comment by RobinHoody** [comment]
@jc1231 It looks like the line:
`config.Count().Filter().OrderBy().Expand().Select().MaxTop(null);`
is dependant on the beta version, which isn't that clear from the tutorial. If you upgrade restier to the beta, it removes the restriction on microsoft.aspnet.odata and allows you to import the beta of that, which contains the extension method referenced in the tutorial. 
@chinadragon0515 please correct me if that's incorrect above, I just had the same issue and that's how I solved it. Just trying out restier now, thanks all for your effort, looks pretty cool.
