### ISSUE TITLE
Problem with Route in Custom Controller with Composite Keys

### ISSUE THREAD

**Issue by iqmeta** [OData/RESTier#538]
Workaround for this Problem?
https://github.com/OData/ODataSamples/issues/51

### Assemblies affected
RESTier 1.0.0-beta => and it's nuget dependencies 

### Reproduce steps
Try to add a custom controller with Composite Keys in Restier Project.

```
public class TestKey
    {
        [Key]
        [Column(Order = 1)]
        public long Id { get; set; }
        [Key]
        [Column(Order = 2)]
        public string SEASON { get; set; }
        [Key]
        [Column(Order = 3)]
        public string COLLECT { get; set; }
    }
```

```
[ModelValidationFilter]
    public class TestKeysController : ODataController
    {
        private readonly Data.MediaRepository _context = new Data.MediaRepository();
        [EnableQuery]
        public IQueryable<TestKey> Get()
        {
            return _context.TestKeys;
        }
        [EnableQuery]
        public TestKey Get([FromODataUri] string SEASON, [FromODataUri] string COLLECT, [FromODataUri] long Id)
        {
            return _context.TestKeys.Where(r => r.Id == 1).FirstOrDefault();
        }
    }
```

/TestKeys(Id=3,SEASON='E',COLLECT='F')
You always hit the default Get Method with the Parameters.

Generic EntityApiController works with Composite Keys. 
But we need to access own logic on eg. Batch, or certain Gets.

Is it possible to use MS AspNet.OData 5.8.0 again with Version 1.0.0-beta,
with the older version it's working.

**Comment by robertmclaws** [comment]
Not sure if this issue is still a problem or not. Closing it for now, if you still experience the issue with the very latest nightlies, or the upcoming 1.0 Beta 2 build, please re-open and we'll discuss.
