### ISSUE TITLE
$skip & $count=true OR $top & $count=true do not work together in the [Resource] defined in EntityFrameworkApi

### ISSUE THREAD

**Issue by jfshark** [OData/RESTier#541]
*Short summary (3-5 sentences) describing the issue.*  
Error message "Sequence contains no matching element" is thrown when requesting a resource, defined in API, using $top & $count=true together. 

### Assemblies affected
Microsoft.Restier.Core.1.0.0-beta

### Reproduce steps
Is reproduceabel in TrippinInMemory Sample with the requests:
http://localhost:xxx/(S(3lv2fmuzvx0mxeazycn4jzaz))/api/Trippin/People?$count=true&$top=10
http://localhost:xxx/(S(3lv2fmuzvx0mxeazycn4jzaz))/api/Trippin/People?$count=true&$skip=10

### Expected result
Returned paged results with the TotalCount

### Actual result
"innererror":{"message":"Sequence contains no matching element","type":"System.InvalidOperationException","stacktrace":"   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)\r\n   at System.Linq.Expressions.ExpressionHelpers.GetCountableQuery[TElement](IQueryable`1 query)\r\n   at Microsoft.Restier.Publishers.OData.Query.RestierQueryExecutor.<ExecuteQueryAsync>d__0`1.MoveNext()\r\n--- ...

**Comment by mikepizzo** [comment]
Should be fixed by @Mateusz-malicki's PR, once we are able to accept it.  Thanks!

**Comment by robertmclaws** [comment]
It looks like this issue is finally fixed in the latest nightly release! Great work everyone!
