### ISSUE TITLE
$count=true throws an exception, when projection is used in EntityFrameworkApi

### ISSUE THREAD

**Issue by jfshark** [OData/RESTier#542]
*Short summary (3-5 sentences) describing the issue.*  
$count doesn't work in [Resource] from EntityFrameworkApi, when the result is projected to DTO, using Selector

### Assemblies affected
Microsoft.Restier.Core.1.0.0-beta

### Reproduce steps

`public class EFApi : EntityFrameworkApi<CLModel>
    {
        public CLModel ModelContext => DbContext;
        [Resource]
        public IQueryable<Asset> AssetDTOs
        {
            get
            {
                return DbContext.Assets.Select(
                    a => new AssetDTO
                    {
                        Name = a.Name,
                        AssetClassValue = a.AssetClassValue,
                        AssetId = a.AssetId
                    }).AsQueryable();
             }
        }`
And then request http://localhost:xxx/api/v1/AssetDTOs?$count=true throws an Exception.
Request to http://localhost:7055/api/v1/Assets?$count=true works fine.

### Expected result
Returned EntitySet

### Actual result

{"error":{"code":"","message":"An error has occurred.","innererror":{"message":"Sequence contains no matching element","type":"System.InvalidOperationException","stacktrace":"   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)\r\n   at System.Linq.Expressions.ExpressionHelpers.GetCountableQuery[TElement](IQueryable`1 query)\r\n   at Microsoft.Restier.Publishers.OData.Query.RestierQueryExecutor.<ExecuteQueryAsync>d__0`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Restier.Core.Query.DefaultQueryHandler.<QueryAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at

**Comment by mikepizzo** [comment]
This should be addressed by @Mateusz-malicki's fix -- we just need to figure out why our CLA bot didn't get his contribution agreement.

**Comment by mateusz-malicki** [comment]
@mikepizzo: I can send it again if it would help;)

**Comment by robertmclaws** [comment]
I believe this has been fixed in https://github.com/OData/RESTier/commit/7d435358f8d9d0ce11f8a81e0e4f65ccfe614199, which will hopefully have a testable build soon. Once the update is release please re-open if you're still having problems. Thanks!

**Comment by cilerler** [comment]
@robertmclaws I will try to look into this probably late this weekend, in case you may want to look into before I work, here is a clue 💡 

## Unsuccessful

```http
@host = localhost:8080

### @name Unsuccessful
GET /api/Main/GetTestData1?$select=Label&$filter=startswith(Label,'PO')&$count=true
Host: {{host}}
Cache-Control: no-cache
```

```csharp
[Resource]
public IQueryable<ContentTypeCode> GetTestData1 => ModelContext.ContentTypeCodes.Where(ctc => ctc.Code < 4);
```

## Successful

```http
@host = localhost:8080
### @name Successful
GET /api/Main/GetTestData2?$select=Label&$filter=startswith(Label,'PO')&$count=true
Host: {{host}}
Cache-Control: no-cache
```

```csharp
using Microsoft.Restier.Core;
// ...
[Resource]
public IQueryable<ContentTypeCode> GetTestData2 => this.GetQueryableSource<ContentTypeCode>("ContentTypeCodes").Where(ctc => ctc.Code < 4);
```

**Comment by robertmclaws** [comment]
This is fixed in the very latest nightly build. Please check and make sure it works for you. If it does not, please let me know here and I'll re-open this ticket. Thanks!
