### ISSUE TITLE
Enable AlternateKeys

### ISSUE THREAD

**Issue by DHSBMarx** [OData/RESTier#543]
I cant enable alternate keys. With an plain WebAPI (5.9.0) it works.  

### Assemblies affected
RESTier 1.0.0

### Reproduce steps
Try to add config.EnableAlternateKeys in WebApiCofig.cs

### Expected result
Recognize as extension from System.Web.OData.Extensions

### Actual result
Reported as not known Element of httpconfiguration

**Comment by robertmclaws** [comment]
I'm closing this for now as out-of-date. If you are still having an issue, please feel free to re-open and provide more details, and we'll see if we can get it worked out for you. Thanks!
