### ISSUE TITLE
can not get RESTier package to load to project

### ISSUE THREAD

**Issue by jimclinton10** [OData/RESTier#544]
In following the documentation to Create an oData Service (1.2 Bootstrap an OData service), i can create the project and web app in Visual Studio 2013.  But when i try to Install the RESTier package via the Manage NuGet Packages, the operation fails with the following error message - "Install failed. Rolling back...
Could not install package 'Microsoft.Extensions.DependencyInjection 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

### Assemblies affected
Trying to install version 1.0.0-beta that comes up in the NuGet packages, but have also tried to load other versions via the Package Manager Console (Install-Package Microsoft.Restier 0.6.0).  Also tied to correct the issue by running the following command on the Package Manager Console (Install-Package Microsoft.Extensions.DependencyInjection.Abstractions -Version 1.0.0).

The project target framework is .NET Framework 4.5.2

### Reproduce steps
Follow the steps in the documentation at http://odata.github.io/RESTier/.  The issue is with 1.2 Bootstrap an OData service and installing the RESTier package.  I get to step 6 and Accept the License Agreement and then receive the error.

### Expected result
If there were no bug the RESTier package would get installed into the project. 

### Actual result
Receive the following error message - "Install failed. Rolling back...
Could not install package 'Microsoft.Extensions.DependencyInjection 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

**Comment by robertmclaws** [comment]
I'm pretty sure that this issue is because that package does not run on .NET 4.5.2 (as the error message says). I believe you're going to need to be on .NET 4.6 or higher to use RESTier.

**Comment by mikepizzo** [comment]
Please let us know if upgrading to .NET 4.6 or higher does not address the issue.
