### ISSUE TITLE
Setting the MaxNodeCount Property

### ISSUE THREAD

**Issue by fishnugget** [OData/RESTier#545]
This isn't really an "issue" I suppose, but I am getting this issue when querying my API.  

"The node count limit of '100' has been exceeded. To increase the limit, set the 'MaxNodeCount' property on EnableQueryAttribute or ODataValidationSettings."  

How do I increase this limit in the API?

**Comment by markdstafford** [comment]
Can you share a sample of a query that is violating the node count limit?

**Comment by fishnugget** [comment]
Ummm....  sure!  

http://somedataendpoint.com/api/ODataTransactionAPI/OdataTransactions?%24top=1001&%24filter=SomeID%20eq%20%279823AKJS1183265%27%20or%20SomeID%20eq%20%279823AKJS1183534%27%20or%20SomeID%20eq%20%279823AKJS1183269%27%20or%20SomeID%20eq%20%279823AKJS1183753%27%20or%20SomeID%20eq%20%279823AKJS1183793%27%20or%20SomeID%20eq%20%279823AKJS1183860%27%20or%20SomeID%20eq%20%279823AKJS1183843%27%20or%20SomeID%20eq%20%279823AKJS1183280%27%20or%20SomeID%20eq%20%279823AKJS1183954%27%20or%20SomeID%20eq%20%279823AKJS1183789%27%20or%20SomeID%20eq%20%279823AKJS1183695%27%20or%20SomeID%20eq%20%279823AKJS1184578%27%20or%20SomeID%20eq%20%279823AKJS1184077%27%20or%20SomeID%20eq%20%279823AKJS1183649%27%20or%20SomeID%20eq%20%279823AKJS1184849%27%20or%20SomeID%20eq%20%279823AKJS1183802%27%20or%20SomeID%20eq%20%279823AKJS1184846%27%20or%20SomeID%20eq%20%279823AKJS1184634%27%20or%20SomeID%20eq%20%279823AKJS1183840%27%20or%20SomeID%20eq%20%279823AKJS1184098%27%20or%20SomeID%20eq%20%279823AKJS1183904%27%20or%20SomeID%20eq%20%279823AKJS1183615%27%20or%20SomeID%20eq%20%279823AKJS1183917%27%20or%20SomeID%20eq%20%279823AKJS1184067%27%20or%20SomeID%20eq%20%279823AKJS1184191%27%20or%20SomeID%20eq%20%279823AKJS1184283%27%20or%20SomeID%20eq%20%279823AKJS1184284%27%20or%20SomeID%20eq%20%279823AKJS1184327%27%20or%20SomeID%20eq%20%279823AKJS1184451%27%20or%20SomeID%20eq%20%279823AKJS1184721%27%20or%20SomeID%20eq%20%279823AKJS1184735%27%20or%20SomeID%20eq%20%279823AKJS1184737%27%20or%20SomeID%20eq%20%279823AKJS1185159%27%20or%20SomeID%20eq%20%279823AKJS1184993%27%20or%20SomeID%20eq%20%279823AKJS1185127%27%20or%20SomeID%20eq%20%279823AKJS1184963%27&%24count=true&%24select=Amount%2CCPTCode%2CCPTDescription%2CDateofService%2CSomeID%2CLocation%2CPayer%2CPayerDescription%2CAgent%2CPostedDate%2CTransactionID_SDB%2CType​

Thanks for your help!

**Comment by markdstafford** [comment]
Well sure enough. :) I bet @chinadragon0515 could answer this in a heartbeat. If he doesn't get to it within the next day or two, I'll go scrub back in to figure it out.

**Comment by fishnugget** [comment]
That's awesome man, I'll be looking out!  In the meantime, do you know where that variable needs to be set?

**Comment by artur-moreira** [comment]
Look at this sample:
http://odata.github.io/RESTier/v0.6/#02-08-Customize-Query

and set the ODataValidationSettings.MaxNodeCount to the desired value

**Comment by markdstafford** [comment]
Perfect, thanks @artur-moreira!

**Comment by fishnugget** [comment]
Ok thanks!  I was looking at that, but where do I add it?  To what file?  Thank you guys for all the help!

**Comment by fishnugget** [comment]
I'm pretty new at this, so I still have one more question.  Where in the API should this code go?  I understand what it's doing, but I can't figure out where it fits in.  Thanks!
