### ISSUE TITLE
Customize Query Example

### ISSUE THREAD

**Issue by fishnugget** [OData/RESTier#546]
I am having some trouble changing the query settings after following the tutorial.  There is a section on this in the Docs, but I was wondering if someone had a little more in depth example of doing this.  Also in that section, the link that leads to the "end to end" solution seems to be broken.

Specifically, I am trying to change the MaxNodeCount.

**Comment by chinadragon0515** [comment]
Refer to the code here,
https://github.com/OData/RESTier/blob/master/test/ODataEndToEnd/Microsoft.OData.Service.Sample.Trippin/Api/TrippinApi.cs#L577-L587

You just need to MaxNodeCount and the sample has MaxExpansionDepth

**Comment by fishnugget** [comment]
Thanks for the help!  One last question, where should this code be added?

**Comment by chinadragon0515** [comment]
If you use Entity framework provider, you can defined a class extend EntityFrameworkApi<TrippinModel>, and replace TripinModel with your DbContext, put the logic in your own class, then during route register in WebApiConfig class using Api class defined by you like config.MapRestierRoute<YouOwnAPIClass>

**Comment by artur-moreira** [comment]
In other words: on your WebApiConfig
config.MapRestierRoute<YourContextApi>(
              routeName: "ODataRoute",
              routePrefix: "yourEndpointName",
              batchHandler: new RestierBatchHandler(GlobalConfiguration.DefaultServer));

and them, define a class "YourContextApi" with

    class YourContextApi : EntityFrameworkApi<YourContext>
    {
        protected override IServiceCollection ConfigureApi(IServiceCollection services)
        {
            // Override default OData validation settings
            Func<IServiceProvider, ODataValidationSettings> validationSettingFactory = sp => new ODataValidationSettings() {
                MaxNodeCount = 100 // desired value
            };

            return base.ConfigureApi(services)
                       .AddSingleton<ODataValidationSettings>(validationSettingFactory);
        }
    }

**Comment by fishnugget** [comment]
Ok.  I think I got it.  One last thing (hopefully):  Where should that class be defined?  Can it be placed in the WebApiConfig as well?  Thanks again for that example!  HUGE help!

**Comment by artur-moreira** [comment]
It's indifferent... Use your coding styles :)

**Comment by chinadragon0515** [comment]
The question is answered, close the issue.

**Comment by fishnugget** [comment]
I added that, but I am getting the following error.  

"No suitable method found to override" on the ConfigureApi method within the class.  Any idea why it's not finding the parent method?
