### ISSUE TITLE
guid primary key should be (guid) not ('guid')

### ISSUE THREAD

**Issue by fileman** [OData/RESTier#547]
I can get all entities with url/restierapi/entity, but when i try to get single entity with url/restierapi/entity(guid) response is Not Found, but if I try url/restierapi/entity('guid') result is ok.

**Comment by fileman** [comment]
ok, I followed [this document](http://docs.oasis-open.org/odata/odata/v4.0/os/part2-url-conventions/odata-v4.0-os-part2-url-conventions.html#_Toc372793851), guid type is (guid) not ('guid') and I think that Syncfusion has followed same documentation for their ODataV4Adaptor.

**Comment by mikepizzo** [comment]
Yes; we changed the syntax in OData V4 to not require quotes for guids.  We should fix this.

**Comment by robertmclaws** [comment]
I believe this is fixed, so I'm closing for now. If you still experience the issue with the latest nightlies, or the upcoming 1.0 Beta 2 release, please re-open and let us know what happened. Thanks!
