### ISSUE TITLE
Support asp.net v5

### ISSUE THREAD

**Issue by congysu** [OData/RESTier#55]
For now, RESTier is based on vCurrent.  Consider to support asp.net v5 together with OData Web API.

**Comment by robertmclaws** [comment]
Duplicate of https://github.com/OData/RESTier/issues/464. I know that the OData core components now support .NET Standard as of 7.2.0. I believe they are working on getting the ASP.NET portion working on ASPNETCORE now. Then Restier will pick up on that work.

HTH!
