### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ielbury** [OData/RESTier#550]
It looks like there is only one developer now. Looks like another Microsoft hatchet job :(

**Comment by fileman** [comment]
Signal of life ?
https://www.nuget.org/packages/WinInsider.Microsoft.Restier.Core/

**Comment by robertmclaws** [comment]
I've posted an updated build here with all of my latest fixes: https://www.nuget.org/packages/advancedrei.restier/. Please see this comment for more information: https://github.com/OData/RESTier/issues/540#issuecomment-298273592

**Comment by mikepizzo** [comment]
not...dead...yet... :-)

Microsoft transferred the internal ownership of this project from a team in China back to the US. We've had to build the new team largely from scratch so it's taken us a bit to get up and running.  Thanks to @robertmclaws and others who have continued to contribute to the project while we get our team rebuilt -- the advantage of open source is that, if there's an invested community, they can continue to maintain the project independently. If there wasn't such a community then it probably wouldn't be something we should be investing in anyway...

**Comment by vincedan** [comment]
any new udpate? it seems dead.... @mikepizzo

**Comment by weitzhandler** [comment]
@mikepizzo @robertmclaws 
Yet over a year later. Looks like OData & Restier are a dead end, are they?

**Comment by weitzhandler** [comment]
Oh, I see this post now: https://github.com/OData/RESTier/issues/616.

**Comment by robertmclaws** [comment]
FYI to everyone: https://github.com/OData/RESTier/issues/616#issuecomment-883656815
