### ISSUE TITLE
Record being duplicated on update

### ISSUE THREAD

**Issue by jonathanljames** [OData/RESTier#552]
When attempting to update a record using the Web API, it appears the record is being duplicated.  While the new data is being reflected in the new record, it is creating a new record with the new data instead of changing the existing record.  Has anyone else experienced something like this?

**Comment by mikepizzo** [comment]
Has anyone else encountered this?
@jonathanljames; do you have a repo?

This could be a serious if it's a general issue in RESTier, but I'd be surprised that nobody else had run into it.

**Comment by robertmclaws** [comment]
Closing due to no response. If you are experiencing this issue in the latest bits, please let us know. Thanks!
