### ISSUE TITLE
protected static new IServiceCollection ConfigureApi(...) in vsn 1.0beta not called

### ISSUE THREAD

**Issue by jhovesen** [OData/RESTier#553]
When overriding EntityFrameworkApi<SomeDbContext> class and implementing ConfigureApi(...), the static class is not called to be able to setup e.g. a service with .AddService(...).

### Assemblies affected
RESTier 1.0beta

### Reproduce steps
public class MyApi : EntityFrameworkApi<MyDbContext>
{
  public MyApi(...) : base(...) {}

  protected static new IServiceCollection ConfigureApi(Type apiType, IServiceCollection services)
  {
    return EntityFrameworkApi<TrippinModel>.ConfigureApi(apiType, services)
      .AddService<IChangeSetItemAuthorizer, MyChangeSetItemAuthorizer>();
   }
}
### Expected result
ConfigureApi(...) would be called when API is called.

### Actual result
ConfigureApi(...) is not callen when API is called.

**Comment by tuath** [comment]
Got the same problem !

**Comment by tuath** [comment]
found the solution : 
        public static new IServiceCollection ConfigureApi(Type apiType, IServiceCollection services)
        {
            services.AddService<IChangeSetItemAuthorizer, CustomizedAuthorizer>();
            return ApiBase.ConfigureApi(apiType, services);
        }


change visibility to public

**Comment by jhovesen** [comment]
So simple - Thanks!
