### ISSUE TITLE
convert byte array to string by odata automatic

### ISSUE THREAD

**Issue by xiaoxiaoji** [OData/RESTier#555]
I'm using odata v4 and Entityframework 6.0.0 to build my webservice,but when I get table from service the byte[] auto convert to string.
 
     Data in Oracle Sql Develper:AUDIT_ITEM_ID:10005000(raw)
     Data in Odata url response from chrome :AUDIT_ITEM_ID":"EABQAA=="
 
What can I do to prevent auto convert or some other advice?

**Comment by robertmclaws** [comment]
This is an Oracle + EF6 problem and not a RESTier problem.  The Oracle EF provider should allow you to change this behavior in the web.config, please check their documentation for more info.
