### ISSUE TITLE
ODataException message thrown within Submit Logic/Interceptors does not appear in JSON error response

### ISSUE THREAD

**Issue by andyminnitt** [OData/RESTier#556]
When throwing `ODataException `within a RESTier Interceptor, the message does not appear in the message field of the JSON error response object.

http://restier.readthedocs.io/en/latest/server/interceptors/

### Assemblies affected
RESTier 0.6.0

### Reproduce steps

`throw new ODataException("Error message.");`

 within a RESTier interceptor, example given in RESTier MkDocs: http://restier.readthedocs.io/en/latest/server/interceptors/

### Expected result
"Error message." would appear in the JSON response object.

### Actual result
{ "error":{ "code":"","message":"An error has occurred." } }

Once the RESTier service is published, only the high level error message is included.

**Comment by robertmclaws** [comment]
We've updated the code to return more error data if you have a `config.IncludeErrorDetailPolicy` set. Can you please check with the very latest Nightly builds (or the upcoming 1.0 Beta 2 release) and see if you're still running into this issue? Thanks!
