### ISSUE TITLE
ModelBuilder not respecting EntitySet<T>().EntityType.Page()

### ISSUE THREAD

**Issue by robertmclaws** [OData/RESTier#558]
WebAPI OData 7.0 allows you to control paging on a per-entity basis through the `.Page()` fluent configuration function on `ODataConventionModelBuilder`.

RESTier does not appear to honor this setting.

### Assemblies affected
RESTier 1.0.0-Beta1

### Reproduce steps
```
    public partial class TestApi : EntityFrameworkApi<TestContext>
    {

        public static new IServiceCollection ConfigureApi(Type apiType, IServiceCollection services)
        {
            return EntityFrameworkApi<TestContext>.ConfigureApi(apiType, services)
                .AddService<IModelBuilder, TestModelBuilder>();
        }

        #region Constructors

        /// <summary>
        /// 
        /// </summary>
        /// <param name="serviceProvider"></param>
        public TestApi(IServiceProvider serviceProvider) : base(serviceProvider)
        {
        }

        #endregion

    }

    internal class TestModelBuilder : IModelBuilder
    {
        public Task<IEdmModel> GetModelAsync(ModelContext context, CancellationToken cancellationToken)
        {
            var modelBuilder = new ODataConventionModelBuilder();

            modelBuilder.EntitySet<Bicycle>("Bicycles")
                .EntityType.HasKey(c => c.Id)
                .Page(250, 50);

            return Task.FromResult(modelBuilder.GetEdmModel());
        }
    }
```

### Expected result
I would expect to only see 50 results in the payload.

### Actual result
I see 70,000 results in the payload.

**Comment by mikepizzo** [comment]
Would love to see this fixed.

**Comment by robertmclaws** [comment]
Without making you dig in too deeply, based on what you know @mikepizzo, what would it take to fix this?

**Comment by robertmclaws** [comment]
RESTier is likely not looking at the ModelBuilder when it is calling the execution pipeline. Need to look into how to pull this out of the model builder and reconcile with the MaxTop() method.

**Comment by robertmclaws** [comment]
Tracking through the above-mentioned super-issue.
