### ISSUE TITLE
Support Delta Links

### ISSUE THREAD

**Issue by congysu** [OData/RESTier#56]
OData Web API and RESTier are yet to support Delta links.  ODataLib already supports Delta links after [6.3 release](http://blogs.msdn.com/b/odatateam/archive/2014/04/30/odatalib-6-3-0-release.aspx).  The issue in OData Web Api is https://github.com/OData/WebApi/issues/71

**Comment by pcosio** [comment]
Hi Team, Is Delta links yet supported in the 1.0.0-beta version of Restier? I mean if I send the HTTP Header (prefer = track-changes) any delta link is returned in the response. Moreover if I make this request
Entity?$select=Id,Name&$deltatoken=r3r2324342, the service returns 

{"error": {
   "code": "",
   "message": "Query option 'DeltaToken' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings."
}}

Then I could allow this by allowing Odata query Settings:
https://github.com/OData/RESTier/issues/419

Thanks. Restier is the best framework for working with ODATA services!

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
