### ISSUE TITLE
Possible Deadlock in RestierController.cs

### ISSUE THREAD

**Issue by robertmclaws** [OData/RESTier#563]
In `RestierController.ApplyQueryOptions`, we're calling an async method method on [Line 540](https://github.com/OData/RESTier/blob/master/src/Microsoft.Restier.Publishers.OData/RestierController.cs#L540) synchronously and using `.Result();` That is a no-no, and can introduce a deadlock in ASP.NET applications.

### Assemblies affected
RESTier 1.0.0-beta1  

### Reproduce steps
No reproduction necessary.

### Expected result
High volume traffic would complete successfully.

### Actual result
It is likely that in higher-volume situations, the API might lock up and stop responding.

### Additional details
The solution is to make the method asynchronous, so this call can be awaited properly. That will also require that the parent call be awaited as well.

**Comment by mikepizzo** [comment]
It looks like this was addressed in your merge (thanks!) 

Please re-open if you think it's still an issue.
