### ISSUE TITLE
Allow PreEvent processors to abort a database operation gracefully

### ISSUE THREAD

**Issue by robertmclaws** [OData/RESTier#567]
The Interceptors that are fired for OnInserting/OnUpdating/OnDeleting need to be able to prevent a database operation from happening, and return an error payload to the end user that is not a terrible (and also insecure) stack trace.

### Assemblies affected
RESTier 1.0.0-beta1 

### Reproduce steps
Let's say I have a system that is tracking physical addressed on the planet, validated through Bing Maps. Each record should be unique, there should be no duplicates.

In the boilerplate OData V3 controller template from Visual Studio, I can do this:
```csharp
public async Task<IHttpActionResult> Post(Address address)
{
    if (!ModelState.IsValid)
    {
        return BadRequest(ModelState);
    }

    try
    {
        var dbAddress = await DataContext.Addresses.FirstOrDefaultAsync(c => c.AddressLine == address.AddressLine && c.PostalCode == address.PostalCode);
        if (dbAddress != null) { return Created(dbAddress); }
        // Continue processing...
    }
}
```
However, that does not appear to be possible in Restier. Now, I may be missing something, but based on the objects [here](https://github.com/OData/RESTier/tree/master/src/Microsoft.Restier.Publishers.OData/Results), I don't think so.

### Expected result
I would expect to be able to do something about this:
```csharp
protected internal async Task<PreEventResult> OnCreatingAddresses(Address entity)
{
    var dbAddress = await this.DbContext.Addresses.FirstOrDefaultAsync(c => c.AddressLine == entity.AddressLine && c.PostalCode == entity.PostalCode);
    // RWM: Does not appear to be an equivalent for this line:
    if (dbAddress != null) { return Created(dbAddress); }

    Debug.WriteLine($"{DateTime.Now}: Address '{entity.Id}' is being created.");
    entity.DateCreated = DateTime.UtcNow;
}
```
In this case, PreEventResult would contain enough information to return error information and/or an alternative entity to short-circuit processing and return in the payload.

### Actual result
I'm stuck writing a Validator and throwing an "Invalid" result with descriptive text in the message, and leaving the end-developer to know the request was still basically excepted, so they can move on.

### Additional details
Another issue is to consider is that the PreEvent processor methods are where developers would intuitively add their pre-submit business logic validation. On a 35 EntitySet API, it does not make logical or practical sense to write a monolithic validator to handle that process.

**Comment by mikepizzo** [comment]
Would love to see a contribution for this.

**Comment by robertmclaws** [comment]
We're going to throw an exception for this. Might need to create a new one for the filter. Returning CREATED on this scenario is not kosher.
