### ISSUE TITLE
New Tool: Making Restier Tests Easier with Breakdance

### ISSUE THREAD

**Issue by robertmclaws** [OData/RESTier#569]
This isn't really an issue, more of an announcement. I've been building some enhancements to Restier that I've been shipping lately. My latest is called ["Testier"](https://www.nuget.org/packages/advancedrei.restier.testier). It's a set of tools to help make testing your Restier APIs easier.

One of the biggest problems I run into is having the system automagically pick up my convention-based methods. So I wrote some code that uses Restier's resolver logic to make a list of all the possible methods in your API, and then mark off whether or not it can actually find them.

[This code](https://github.com/advancedrei/Testier/blob/master/src/AdvancedREI.Testier.Tests.Restier/TestierGeneratorTests.cs#L43-L51) outlines how the tests work. The output looks similar to this (using the test API in the project):
```
--------------------------------------------------
Function Name                            |   Found
--------------------------------------------------
CanInsertPlayers                         |   False
CanUpdatePlayers                         |   False
CanDeletePlayers                         |   False
OnInsertingPlayers                       |   False
OnUpdatingPlayers                        |   False
OnDeletingPlayers                        |   False
OnFilterPlayer                           |   False
OnInsertedPlayers                        |   False
OnUpdatedPlayers                         |   False
OnDeletedPlayers                         |   False
CanInsertSports                          |   False
CanUpdateSports                          |   False
CanDeleteSports                          |   False
OnInsertingSports                        |   False
OnUpdatingSports                         |   False
OnDeletingSports                         |   False
OnFilterSport                            |    True
OnInsertedSports                         |    True
OnUpdatedSports                          |   False
OnDeletedSports                          |   False
CanInsertTeams                           |   False
CanUpdateTeams                           |   False
CanDeleteTeams                           |   False
OnInsertingTeams                         |   False
OnUpdatingTeams                          |   False
OnDeletingTeams                          |   False
OnFilterTeam                             |   False
OnInsertedTeams                          |   False
OnUpdatedTeams                           |   False
OnDeletedTeams                           |   False
CanExecuteTestMethod                     |   False
OnExecutingTestMethod                    |   False
OnExecutedTestMethod                     |   False
--------------------------------------------------
```

I still haven't figured out how to "discover" functions attached to EntitySets, so contributions are welcome. I'll be adding in a way to dump the list to a text file, so you can compare a "base" against the current incarnation, and have the test fail if it changes. It will be similar to [what the existing Restier tests already do](https://github.com/OData/RESTier/blob/master/test/Microsoft.Restier.TestCommon/PublicApiTests.cs).

It requires my distro of Restier to work, but I'll switch it to Microsoft's packages when they ship the next version.

I'll throw some docs up in the next few days. In the meantime, feedback is welcome. I hope this helps someone. :)

**Comment by mikepizzo** [comment]
Very cool!

**Comment by robertmclaws** [comment]
I'll be updating Breakdance.Restier to use the new pluralization naming conventions once they are integrated into master.
