### ISSUE TITLE
Complete EF7 to EDM model mapping

### ISSUE THREAD

**Issue by rayao** [OData/RESTier#57]
EF7 ModelProducer needs following features to be complete:
- Precision for Decimal and Duration type.
- How to map EF GenerateValueOnAdd and IsStoreComputed property to EDM property annotation.
- How to tell EF string type is of ANSI or Unicode.
- How to map some EDM built in complex type such as "Geography, Geometry, GeometryCollection" etc.
- How to know EF navigation property OnDelete behavior, so that it can be mapped to EDM.

**Comment by rayao** [comment]
Also,
* Update Northwind sample to build an equivalent (to EF6) DB model.

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
