### ISSUE TITLE
Trippin sample does not support $count=true with skip and/or top

### ISSUE THREAD

**Issue by jvitor83** [OData/RESTier#583]
Requesting to include the Count **works**!
http://services.odata.org/TripPinRESTierService/(S(3mslpb2bc0k5ufk24olpghzx))/People?$count=true

Requesting to include the Count and Skip or Top **not works**!
http://services.odata.org/TripPinRESTierService/(S(3mslpb2bc0k5ufk24olpghzx))/People?$count=true&$skip=0&$top=10

Response:
```
{
    "error": {
        "code": "",
        "message": "An error has occurred."
    }
}
```

**Comment by jvitor83** [comment]
Maybe it is the same issue as https://github.com/OData/RESTier/issues/541 ?

**Comment by robertmclaws** [comment]
This should have been fixed in https://github.com/OData/RESTier/commit/7d435358f8d9d0ce11f8a81e0e4f65ccfe614199. Please re-open if it wasn't. Thanks@
