### ISSUE TITLE
Full text search

### ISSUE THREAD

**Issue by Spragalas** [OData/RESTier#588]
Hi, 

I am building business application and I am using EntityFramework with Restier. However I am missing out for a $search functionality. I know it is not supported by OData Web Api (follow up link https://github.com/OData/WebApi/issues/66).

Anyhow I was wondering if there is a way to workaround this ? 

I would use that in the following fashion:

http://localhost/rest/ObjectSet?$filter=ParentId+eq+1&$ftr=i need this

So I guess what i am saying that I still need strict functionality of $filter option and a full text search on top on that.

Thanks

**Comment by Spragalas** [comment]
Any comments ?

**Comment by robertmclaws** [comment]
Hey sorry about the delay on getting back to you on this. I'm sure you've moved on, but in case you haven't, unfortunately if it's not supported in the core WebAPI experience, it's not going to be supported here. I will bring it up in the next Community Standup on Tuesday and see if I can get more info on when/if that feature is planned.

**Comment by robertmclaws** [comment]
I don't think this is going to be supported for a little while. I'm going to close it for now, as we're resetting to get 1.0 out the door. However, I've marked it as needing downstream support first, and I will be checking in on those monthly and seeing what we can do from there. Thanks so much for letting us know!
