### ISSUE TITLE
CS1703 trying to use from VS2015

### ISSUE THREAD

**Issue by uecasm** [OData/RESTier#590]
I'm trying to follow the Getting Started guide to experiment with RESTier in VS2015u3 with a .NET Framework 4.6.2 web application.

I've created the web project and used Nuget to add Microsoft.Restier 1.0.0-beta (since this appears to be the version covered in the documentation, given the presence of [Resource] attributes etc).

However this has added a bunch of additional packages that appear to duplicate those in the framework (such as System.Collections, System.Reflection, etc), and in particular the following errors:

    CSC : error CS1703: Multiple assemblies with equivalent identity have been imported: 'C:\Users\gavinl\Documents\Visual Studio 2015\Projects\ExperimentalRestApi\packages\System.Runtime.Extensions.4.1.0\lib\net462\System.Runtime.Extensions.dll' and 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\Facades\System.Runtime.Extensions.dll'. Remove one of the duplicate references.
    CSC : error CS1703: Multiple assemblies with equivalent identity have been imported: 'C:\Users\gavinl\Documents\Visual Studio 2015\Projects\ExperimentalRestApi\packages\System.Reflection.4.1.0\lib\net462\System.Reflection.dll' and 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\Facades\System.Reflection.dll'. Remove one of the duplicate references.

It's hard to tell (since the package manager UI in VS is dumb and doesn't show you the dependencies for the currently installed version of packages, only those for other versions) but it looks like the main culprit is the Microsoft.Extensions.DependencyInjection package, which targets .NETStandard, and this appears to make it want all the extra packages.

I can get it to build if I manually modify the project file to convert these references back to standard framework references rather than private assembly references, but I'm not sure if that has other consequences or if I should do that to more of the references, or if Nuget will try to revert them later.

**Comment by robertmclaws** [comment]
So, VS2015's support for .NET Standard is *terrible*. I'm not sure if they got to fix this in the later .NET Standard NuGet packages or not. The new release we're working on is .NET Standard for the core library and .NET 4.6.2 for the EF6 and ASP.NET packages.

I would highly recommend moving to VS2017 and .NET 4.7.2, if possible. I know there are a bunch of .NET Standard fixes that have been hanging around, and VS2017 is much better at this stuff.

I'm going to close this for now, but please feel free to re-open if the new version we release this month has the same problems. Thanks!
