### ISSUE TITLE
ETags do not work, If-Match & If-None-Match Headers comparison, Precondition Failed

### ISSUE THREAD

**Issue by nurf3d** [OData/RESTier#592]
*ETags are not being checked correctly. Every call ends with 412 Precondition required.*

### Assemblies affected
```
<package id="Microsoft.Restier" version="0.6.0" targetFramework="net452" />
<package id="Microsoft.Restier.Core" version="0.6.0" targetFramework="net452" />
<package id="Microsoft.Restier.Providers.EntityFramework" version="0.6.0" targetFramework="net452" />
<package id="Microsoft.Restier.Publishers.OData" version="0.6.0" targetFramework="net452" />
```

### Reproduce steps

1. *Clone test repository https://github.com/nurf3d/RestierTest*
2. *Issue HTTP-GET to /crm/People(1)*
![stage1](https://user-images.githubusercontent.com/9108292/30544140-cde7329e-9c85-11e7-85ac-3e82579436f6.PNG)
3. *Extract Etag from entity and issue another HTTP-GET with If-Match header set to Etag value*
![stage2](https://user-images.githubusercontent.com/9108292/30544147-d08de2fe-9c85-11e7-93b4-63820b7c8572.PNG)

### Expected result
*304 Not Modified*

### Actual result
*412 Precondition failed*  

### Additional details
*Somehow the Etag isn't compared correctly. HTTP-PUT and -Delete are also having the same issue.*

**Comment by robertmclaws** [comment]
I'm closing this as being out of date. If you are still having issues with the latest bits from the Nightly feed, please re-open the issue. Thanks!
