### ISSUE TITLE
No-WebApi approach

### ISSUE THREAD

**Issue by Vinss85** [OData/RESTier#593]
Hi, 
I have been using RESTier successfully in my company for already 1 year.
Lately a new scenario came up to me where i need to execute an OData query string outside of its canonical stack (not passing through the WebAPI) against my EntityFramework model.
I've been struggling a lot to find a way to easily parse and execute just the query string with poor results.
Do you have any suggestions?

Thanks :)

**Comment by robertmclaws** [comment]
Hey, I'm one of the new community managers for this project. Are you still having this issue? Thanks!

**Comment by robertmclaws** [comment]
Closing this due to no response.
