### ISSUE TITLE
AspnetCore

### ISSUE THREAD

**Issue by grahamehorner** [OData/RESTier#594]
Please consider creating examples for AspNetCore using EntityFrameworkCore

**Comment by robertmclaws** [comment]
We will not be supporting EF Core in our initial release, as the system is working on EF Standard, and we need to get the code out the door. We're going to rewrite RESTier for .NET Core 3.0, and when we do, we'll support EF Core and .NET Framework 6.3 as provider options.

Closing for now. Thanks for your feedback!

**Comment by robertmclaws** [comment]
Good news, this has changed! We now support ASP.NET Core 3.1 and later, running either EF6 or EFCore. More details: https://github.com/OData/RESTier/issues/616#issuecomment-883656815
