### ISSUE TITLE
XML Content Negotiation Support?

### ISSUE THREAD

**Issue by bkoliba** [OData/RESTier#595]
Looking to be able to support application/XML as the content type. Was'nt able to find anywhere that it states it isn't supported. If supported could you point me in the right direction on how to configure? Was able to add a custom formatter but it errors out (Microsoft.Restier.Publishers.OData.EntityCollectionResult cannot be serialized because it does not have a parameterless constructor.). Thanks

**Comment by robertmclaws** [comment]
AFAIK OData 4.0 dropped support for XML as a payload type, but don't quote me on that.

**Comment by bkoliba** [comment]
Thanks for the reply. Should of specified atom format application/atom+xml (tried using application/atom+xml, application/xml and application/atomsvc+xml as an accept header value). Was using this as a resource thinking it was supported http://docs.oasis-open.org/odata/odata-atom-format/v4.0/odata-atom-format-v4.0.html but was written back in 2013 so maybe it was dropped after that. Thanks again Robert.

**Comment by robertmclaws** [comment]
This NuGet package specifically says "JSON payloads", does not mention ATOM. I think they dropped it because I seem to recall seeing that they're taking the code for that feature totally out of the libraries now, instead of just deprecating them. Sorry, I wish I had better news.

**Comment by AlanWong-MS** [comment]
Yes, we dropped support for ATOM in favor of JSON. Thanks for the response, Robert.
