### ISSUE TITLE
Set API as READONLY

### ISSUE THREAD

**Issue by bastienlemaitre** [OData/RESTier#598]
Hi,
How can i set the API as READONLY mode ?
I've tried this into my API conf but not works..
```cs
        protected bool CanInsert()
        {
            return false;
        }
        protected bool CanUpdate()
        {
            return false;
        }
        protected bool CanDelete()
        {
            return false;
        }
```

Any idea ? Thanks !

**Comment by copypastedeveloper** [comment]
So I've got restier set up this way, and basically, what you're missing is the name of the entity at the end of each method.  For example mine look like this: 

```c#
        protected internal bool CanInsertCustomers => false;
        protected internal bool CanInsertPlatformClients => false;
        protected internal bool CanInsertProducts => false;
        protected internal bool CanInsertUsers => false;
        protected internal bool CanInsertUserProducts => false;
        protected internal bool CanUpdateCustomers => false;
        protected internal bool CanUpdatePlatformClients => false;
        protected internal bool CanUpdateProducts => false;
        protected internal bool CanUpdateUsers => false;
        protected internal bool CanUpdateUserProducts => false;
        protected internal bool CanDeleteCustomers => false;
        protected internal bool CanDeletePlatformClients => false;
        protected internal bool CanDeleteProducts => false;
        protected internal bool CanDeleteUsers => false;
        protected internal bool CanDeleteUserProducts => false;
        protected internal bool CanExecutePlatformClients => UserIsAdmin;
        protected internal bool CanExecuteUserProducts => UserIsAdmin;
```
Notice after the action I have each of my entity names.  You can also filter the execute, which I do for a couple of entities above, meaning only certain users can even query that part of the odata api.

**Comment by bastienlemaitre** [comment]
I've found another solution.
Add a ISubmitExecutor into services.

**Comment by robertmclaws** [comment]
@copypastedeveloper's approach is correct in this case... the Convention-based approach is to implement methods that follow the naming patterns, and return a boolean. It is important to note that this pattern does not evaluate whether or not you can update a *specific* entity, you have to implement either an interceptor or a validator for that.

Hope that helps!
