### ISSUE TITLE
Custom model builder PUT/PATCH not being called

### ISSUE THREAD

**Issue by JanKotschenreuther** [OData/RESTier#600]
I am using a custom model builder with some DTOs.
To build the API i use Controllers that inherit from ODataController.
Querying and posting data is no problem so far.
When i try to Update a record with a PATCH or PUT request, the corresponding controller actions are not being called, but instead i get Exceptions.

### Assemblies affected
RESTier 1.0.0-beta

### Reproduce steps
After creating a web-api project and installing the RESTier-NuGet-Package, i created a simple custom model builder.
Then i created a Controller that inherits from ODataController and implements Get/Post/Put/Patch Actions.
Then i made a Request to each of these Actions, but Put and Patch wont be called.

My Modelbuilder looks like this:
```
    public class CustomModelBuilder : IModelBuilder
    {
        public Task<IEdmModel> GetModelAsync(ModelContext context, CancellationToken cancellationToken)
        {
            var builder = new ODataConventionModelBuilder();
            
            builder.EntitySet<StoreDTO>("Stores");

            return Task.FromResult(builder.GetEdmModel());
        }
    }

public class StoreDTO
    {
        [Key]
        public int No { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
    }
```

The signatures of my controller-actions look like this:
```
[EnableQuery]
public IQueryable<StoreDTO> Get()
[EnableQuery]
public SingleResult<StoreDTO> Get([FromODataUri] int key)
public async Task<IHttpActionResult> Post(StoreDTO store)
public async Task<IHttpActionResult> Put([FromODataUri] int key, StoreDTO store)
public async Task<IHttpActionResult> Patch([FromODataUri] int key, Delta<StoreDTO> store)
```

### Expected result
The Put and Patch actions would be called to process my impleted logic.

### Actual result
The Put or Patch action is not being called.
Instead my global ExceptionHandler is catching Exceptions.
First i did get ChangeSetPreparer is missing exceptions.
After a change i did get null reference exceptions.

1. ChangeSetPreparerIsMissing
The documentation does not discuss anything like a ChangeSetPreparer i think.
I tried solving the problem myself anyway and changed my code, adding a ChangeSetInitializer and a SubmitExecutor but then i get NullReferenceExceptions.

Changed Code:
```
    public class ExternalApi : ApiBase
    {
        public ExternalApi(IServiceProvider serviceProvider) : base(serviceProvider)
        {
        }

        public static new IServiceCollection ConfigureApi(Type apiType, IServiceCollection services)
        {
            return ApiBase.ConfigureApi(apiType, services)
            .AddService<IModelBuilder, CustomModelBuilder>()
            .AddService<IChangeSetInitializer, ChangeSetInitializer>()
            .AddService<ISubmitExecutor, SubmitExecutor>();
        }

        private class ChangeSetInitializer : IChangeSetInitializer
        {
            public Task InitializeAsync(SubmitContext context, CancellationToken cancellationToken)
            {
                context.ChangeSet = new ChangeSet();
                return Task.FromResult<object>(null);
            }
        }

        private class SubmitExecutor : ISubmitExecutor
        {
            public Task<SubmitResult> ExecuteSubmitAsync(SubmitContext context, CancellationToken cancellationToken)
            {
                return Task.FromResult(new SubmitResult(context.ChangeSet));
            }
        }
    }
```

2. After these Changes i get NullReferenceExceptions with the following stackTrace:

bei Microsoft.Restier.Publishers.OData.RestierController.CreateResult(Type resultType, Object result) bei Microsoft.Restier.Publishers.OData.RestierController.CreateUpdatedODataResult(Object entity) bei Microsoft.Restier.Publishers.OData.RestierController.d__3f.MoveNext() --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde --- bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) bei Microsoft.Restier.Publishers.OData.RestierController.d__20.MoveNext() --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde --- bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) bei System.Threading.Tasks.TaskHelpersExtensions.d__3`1.MoveNext() --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde --- bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) bei System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext() --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde --- bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) bei System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext() --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde --- bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) bei System.Web.Http.Controllers.ExceptionFilterResult.d__0.MoveNext() --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde --- bei System.Web.Http.Controllers.ExceptionFilterResult.d__0.MoveNext() --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde --- bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) bei System.Web.Http.Dispatcher.HttpControllerDispatcher.d__1.MoveNext() --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde --- bei System.Web.Http.Dispatcher.HttpControllerDispatcher.d__1.MoveNext() --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde --- bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) bei System.Web.Http.HttpServer.d__0.MoveNext()

### Additional details
I already had a working RESTier-Project, that does not use a CustomModelBuilder or extended EntityFramework model.
Both projects use the same configuration beside the difference with the custom-model-builder.
My applicationhost and the webconfigs are configured to allow Put/Patch-Requests.
I also tried adding AcceptVerbsAttribute to explicitly allow Put/Patch but it didnt change anything.

**Comment by JanKotschenreuther** [comment]
I found a solution or at least a workaround.
I changed my WebApiConfig a little bit.

Instead of:
MapRestierRoute(...) from Microsoft.Restier.Publishers.OData.HttpConfigurationExtensions
i am using now:
MapODataServiceRoute(...) from System.Web.OData.Extensions.HttpConfigurationExtensions

**Comment by robertmclaws** [comment]
Just so you know, your change too RESTier completely out of your pipeline and mapped everything the WebAPI OData way. If you'd still like help getting custom functions working, please let me know. Closing this out. Thanks!
