### ISSUE TITLE
$select fails at xml

### ISSUE THREAD

**Issue by Tintifax73** [OData/RESTier#603]
Hi,

I try to make my first steps with asp.net, webapi and odata, and ran into this issue:

Everything works fine, until I try to reduce the output fields with the $select parameter. If I try to Access my controller with Accept "application/XML", and no odata Parameter, "http://localhost:59692/Products" the result is a beautiful XML result. If I call it like this "http://localhost:59692/Products?$select=Name", the result is an error like this:

ArgumentException: Object of type 'System.Linq.EnumerableQuery`1[Microsoft.AspNet.OData.Query.Expressions.SelectExpandBinder+SelectSome`1[(..)Product]' cannot be converted to type 'System.Collections.Generic.IEnumerable`1[(..)Product]

This error only occurs with "Application/XML", requests with Result Json work perfect. Also $filter work as it should. (http://localhost:59692/Products?$filter=Id eq 3)

Is this a "Design-Issue", selecting some fields in XML is not possible - or is this a configuration issue?

My WebApiConfig.cs looks like this:

        public static void Register(HttpConfiguration config)
        {
            // Web API configuration and services

            // Web API routes
            config.MapHttpAttributeRoutes();

            config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "api/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );

            ODataModelBuilder builder = new ODataConventionModelBuilder();
            builder.EntitySet<Product>("Products");
            config.MapODataServiceRoute(
                routeName: "ODataRoute",
                routePrefix: null,
                model: builder.GetEdmModel());

            config.Filter().Expand().Select().OrderBy().MaxTop(null).Count();

            var odataFormatters = ODataMediaTypeFormatters.Create();
            config.Formatters.InsertRange(0, odataFormatters);
        }

Thanks for the support!

Best Thomas

**Comment by vstribrny** [comment]
As far as I know, the "application/atom+xml" is still not part of OASIS standard of OData V4 and therefore intentionally not supported by underlying OData/WeApi, see OData/WebApi#639 for example. I think the "application/xml" works "by default" due to Web API MVC serialization rules.

**Comment by Tintifax73** [comment]
Thank you. No, as described: application/XML works, but if I filter the result with the $select Parameter, it does not work anymore.

**Comment by robertmclaws** [comment]
This does not appear to be a RESTier issue. If you are still experiencing this problem, I would suggest opening it in the https://github.com/OData/WebApi issues list.

Good luck!

**Comment by HisokaHxHPW** [comment]
Hi I have the same problem. How did you fix this?
