### ISSUE TITLE
RESTier SQLAzure ApplicationID token authentication?

### ISSUE THREAD

**Issue by ErikErkelens** [OData/RESTier#604]
I'd like to use RESTier with a SQL Azure database, but I have to authenticate by adding an authentication token to the database requests, is there a way to do that in the 1.0 library?

I've looked at the hooks that are provided for inserting, queries, but there is database access before those take place.

I've tried setting the token in the model constructor, using the DBContext's Connection property, but it looks like the model can be long-lived, and I don't see how to update the token after construction.

**Comment by robertmclaws** [comment]
Restier doesn't provide this by default, but it's just WebAPI 2 under the covers, so any existing OAuth solution for WebAPi or OWIN will work just fine. I'm currently using Restier + Auth0 for token-secured APIs and I love it.

**Comment by ErikErkelens** [comment]
Correct me if I'm wrong, but I think you're talking about securing the API, and how that works is pretty well documented. 

I'm looking for a way to use a database that requires token based authentication (SQL Azure using AD), that's a different issue. 

I need to fill in the SQLConnection's AccessToken in a setup like this: https://michaelcollier.wordpress.com/2016/11/03/connect-to-azure-sql-database-by-using-azure-ad-authentication/

**Comment by ErikErkelens** [comment]
Thank you very much, showing how to add the the scoped DBContext provider helped.

I got it to work, although not nearly as nice as I’d have hoped. I could not find a way to have IServiceColletion::AddEfProviderServices run (called by EnityFrameworkApi::ConfigurApi) so that it could register the internal Modelbuilder, Mapper etc., without also allowing it to set up its own provider for DBContext as well. 

The ‘native’ instantiation pre-empted ‘my’ version of model instantiation, so I'm now removing it from services registry before adding mine.

**Comment by jspuij** [comment]
Yep, the current implementation of DI in this library does not work for you but mostly against you, you're not the first to notice ;-)

You could choose to encapsulate the token request / renewal mechanism in the parameterless constructor of your derived DbContext like this:

```csharp
public class YourDataContext : DbContext
{
    // call the base constructor with a connection provided
    // by PrepareConnection() and ownConnection = true.
    public YourDataContext() : base(PrepareConnection(), true)
    {

    }

    private static SqlConnection PrepareConnection()

    {
        // do some fancy stuff here to obtain a token.
        var connection = new SqlConnection("Connection string here");
        connection.AccessToken = authenticationResult.AccessToken;
        connection.Open();

        return connection;
    }
}
```
This way you're pretty sure that everyone creating an instance of YourDataContext uses the right token / authentication mechanism to connect to the database. Your credentials and authentication code would be buried deep inside this class though.
I prefer registering my DbContext once in my own DI container for the entire application at the application entry point, including the necessary credentials and settings there, not spread around your code base.
Unfortunately that's not possible ATM.

**Comment by ErikErkelens** [comment]
Setting the token in the constructor is actually where I started (and will go back to), but couldn't get that to work because I didn't have hasOwnContext=true and .Open() as in your example.

Would be nice to have cleaner solution for this, one that would also take into account that the AccesToken, in Azure AD's case, is obtained asynchronously.

Thanks for helping get this to work @jspuij !

**Comment by robertmclaws** [comment]
Glad you were able to get this worked out. We're going to totally re-work the DI implementation for the v2 release... for now we have to live with the hand we were dealt. But you are right that this implementation is weak and hard to work with, it's my top priority for the rewrite.

Thanks!
