### ISSUE TITLE
need support for @odata.bind

### ISSUE THREAD

**Issue by vincedan** [OData/RESTier#610]
It seems @odata.bind not supported when use PATCH to update one entity
all other fields of that entity have been updated to db successfully, but for navigation property/foreign key, not updated.

### Assemblies affected
*Which assemblies and versions are known to be affected e.g. RESTier  pre 1.0

### Reproduce steps
create two entities Company/ Employee.  create a foreign key [AccountManager] in Company which refer to Employee. add some data for testing.

run fiddler to test service.
POST http://localhost:1842/ApplicationData/$batch HTTP/1.1
Host: localhost:1842
Connection: keep-alive
Content-Length: 572
Accept: multipart/mixed
Origin: http://localhost:1234
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36
Content-Type: multipart/mixed;boundary=batch_55b3-fe30-05f8
Referer: http://localhost:1234/HTMLClient/
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Cookie: msls-client-parameters=preferredLanguage=zh-CN

--batch_55b3-fe30-05f8
Content-Type: multipart/mixed; boundary=changeset_0fb9-0b27-a979

--changeset_0fb9-0b27-a979
Content-Type: application/http
Content-Transfer-Encoding: binary

PATCH Companies(1) HTTP/1.1
Content-ID: 0
If-Match: W/"YmluYXJ5J0FBQUFBQUFBSnhvPSc="
Prefer: return-content
Accept: application/json;odata.metadata=full
Content-Type: application/json;odata.metadata=full

{ 
"CompanyName":"new 123",
"AccountManager@odata.bind":"http://localhost:1842/ApplicationData/Employees(1)"
 }
--changeset_0fb9-0b27-a979--

--batch_55b3-fe30-05f8--
 

### Expected result
[CompanyName] and [AccountManager] fields should be updated with new value both.
### Actual result
db commit done. [ComanyName] changed as expected. but [AccountManager] not.
base on oasis standard: 8.5 Bind Operation in http://docs.oasis-open.org/odata/odata-json-format/v4.0/odata-json-format-v4.0.html

**Comment by vincedan** [comment]
#158

**Comment by vincedan** [comment]
#284
#https://github.com/OData/WebApi/issues/158#issue-54015025

**Comment by robertmclaws** [comment]
We're not able to support this now, as it is not supported lower in the stack. I'm going to close it, but we will re-evaluate stack issues periodically and adjust from there. Thanks for reportng this to us!
