### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by lgadola** [OData/RESTier#612]
Is this another one of Microsofts' dead ends they tend to lead us programmers into?
Beta from 2016 and since then - nothing.

**Comment by MichelZ** [comment]
#611

**Comment by darestov** [comment]
I second the question. Hey team, is there anybody there? Maybe the project has been rebranded to smth like 'Microsoft OData Foundation' or included in another big framework?

**Comment by cilerler** [comment]
https://github.com/OData/RESTier/issues/540

**Comment by robertmclaws** [comment]
https://github.com/OData/RESTier/issues/616#issuecomment-883656815
