### ISSUE TITLE
add typeless entities support

### ISSUE THREAD

**Issue by mojobec** [OData/RESTier#613]
right now `ApiBaseExtensions.EnsureElementType` validates the entity type.
[typeless entities](https://blogs.msdn.microsoft.com/leohu/2013/11/04/typeless-entity-object-support-in-webapi/)

**Comment by robertmclaws** [comment]
Thank you for the feedback! Unfortunately, I don't believe we'll be able to get this on the roadmap any time in the forseeable future... there is just too much to do to get v1 out the door and the rewrite everything for .NET Core 3.0. But it will be here in the archives, and if we get time someday we'll take a look.

Thanks again for the suggestion!
