### ISSUE TITLE
OnFilter method with Select throws error

### ISSUE THREAD

**Issue by jm8985** [OData/RESTier#638]
*Short summary (3-5 sentences) describing the issue.*  

### Assemblies affected
RESTier 1.0.0-beta 

### Reproduce steps
-Follow simple tutorial 1.2 "Bootstrap an OData service" [here](http://odata.github.io/RESTier/)
-Add OnFilter method. The where clause works, but not select. This is my code:

` protected IQueryable<AGR_test> OnFilterAGR_test(IQueryable<AGR_test> entitySet) {

            return entitySet.Select(p => new AGR_test()
            {
                
                AGR_Header_RecID = p.AGR_Header_RecID,
                SR_SLA_RecID = p.SR_SLA_RecID
               
            }).AsQueryable();

        }`

### Expected result
Should work as described here [Issue 467](https://github.com/OData/RESTier/issues/467)
I'd like to null some fields before they are returned, or simply hide them from certain clients in our database.

### Actual result
Throws error message " The entity or complex type 'ClientAPI.Models.AGR_test' cannot be constructed in a LINQ to Entities query."

**Comment by brettmas** [comment]
This is a standard EF behaviour, it won't let you construct a new version of the entity you're querying.

**Comment by robertmclaws** [comment]
I was basically going to say the same thing as @brettmas. What is the use case for projecting a new instance of the **same** entity?

**Comment by jm8985** [comment]
The use case for projecting a new instance of the same entity: I would like only some fields to be visible in that class. By not including them in the select, they return null values. Hence certain API users would see StreetAddress1 property as null, as they do not have permission.

The select should be dynamic, customized per request.

I've managed to accomplish this with the standard odata controller, and the [automapper ](https://automapper.org/)package. But I would much prefer to use Restier.

**Comment by jm8985** [comment]
This is what the odata controller looks like:
```// GET: odata/Sources
        [EnableQuery]
        public IQueryable<Source> GetSources()
        {
            //ShowFormat should be read in from user permission table
            bool ShowFormat = false;
            try {
                Mapper.Initialize(cfg =>
                {
                        cfg.CreateMap<Source, Source>()
                           .ForMember(dest => dest.Format, opt => opt.Condition(src => (ShowFormat == true)));
                   
                });

            } catch (Exception e) {
            }
            
            return db.Sources.ToList().Select(u => Mapper.Map<Source>(u)).AsQueryable();
            
        }
```

**Comment by jm8985** [comment]
In chinadragon0515's post [here](https://github.com/OData/RESTier/issues/467#issue-166714156) He mentioned that OnFilter could be used to nullify a password field. Was that never the case?

**Comment by jm8985** [comment]
Closing this, I'm using standard OData controllers with automapper to accomplish this.
