### ISSUE TITLE
Where is the "Filter" method?

### ISSUE THREAD

**Issue by ahdung** [OData/RESTier#644]
which dll and namespace?
 
![ID截图20190711152536](https://user-images.githubusercontent.com/12094247/61030536-2cc38380-a3f0-11e9-96da-10b1a4c2f9f8.png)

**Comment by robertmclaws** [comment]
Add `using Microsoft.AspNet.OData.Extensions;` to your file, and then right-click the usings area and select "Remove and sort usings". ;)

HTH!
