### ISSUE TITLE
Entity validation needs to return ODataExceptions

### ISSUE THREAD

**Issue by vincedan** [OData/RESTier#653]
json format for exception output should be uniformed. 
version:RC1

### Reproduce steps
1) if entity has validation attribute, for example, MaxLength(10) , if request is invalid, return json is like bellows:

![error1](https://user-images.githubusercontent.com/16057386/66501360-db618800-eaf5-11e9-8956-459e8f570f51.png)

2) if request etag is wrong， json will return like 

![error2](https://user-images.githubusercontent.com/16057386/66501370-e0bed280-eaf5-11e9-9f3e-d168e873b4d7.png)

### Expected result
* message or Message,[Id,PropertyName,Serverity]  ==> as standard, I think all property name for Message/Id/PropertyName/Serverity should be in lowercase, like message/id/propertyname...
* it is better to have one property, to indicate returned error json is validation error, or run-time error/ or other name termed.

well-format error information is helpful in error handling at the client side.

**Comment by robertmclaws** [comment]
Thanks for reporting this, we'll fix it for RTM.

**Comment by robertmclaws** [comment]
This will be fixed for the next Release Candidate, which will go out before Friday.. The new format will now look like this:

```json
{
    "error": {
        "code": "",
        "innererror": {
            "message": "The operation cannot be performed because one or more objects are invalid.  Please inspect the ChangeSetValidationException.ValidationResults property for more information.",
            "type": "Microsoft.Restier.Core.Submit.ChangeSetValidationException"
        },
        "message": "Validaion failed for one or more objects.",
        "validationentries": [{
                "validatortype": "System.ComponentModel.DataAnnotations.MaxLengthAttribute",
                "propertyname": "Isbn",
                "severity": "Error",
                "message": "The field Isbn must be a string or array type with a maximum length of '13'."
            }
        ]
    }
}
```

It's not ideal, because I would rather it be in camelCase vs all lowercase, but I can't do anything about that.

Please let me know if you have any other issues. Thanks!

**Comment by vincedan** [comment]
thanks a lot.  @robertmclaws

**Comment by robertmclaws** [comment]
It's not that it's not possible (I used Newtonsoft.Json for the changes) it's that OData uses all lowercase for their properties, so I have to do the same here for consistency. Thanks though!
