### ISSUE TITLE
Question or Feature expected: need common for logic handling for CRUD

### ISSUE THREAD

**Issue by vincedan** [OData/RESTier#655]
We can write user logic code On<Insert|Updat|Delet|Execut><ed|ing> to provide data manipulation as required, related expected method will be executed by reflection if existing, But if I wanna write handling for common scenario, for example, log all data deletion operation, or fill audit columns such create time/update time, It won't write logics for entity one by one. right now do we have a solution for current version of Restier? I roughly went through Restier sourcecode and found DefaultSubmitHandler class can not be extended. If no solution at this time point, could we change the API and provide extension ability?

**Comment by cilerler** [comment]
We already have that logic in place.  You may find the details in here http://odata.github.io/RESTier/#02-09-Customize-Submit

**Comment by vincedan** [comment]
thank @cilerler. that is what I need. :)
