### ISSUE TITLE
OData batching not working with OWIN

### ISSUE THREAD

**Issue by newclaus** [OData/RESTier#657]
I've updated your project Microsoft.Restier.Samples.Northwind.AspNet and used OWIN. 

> https://github.com/newclaus/RESTier/commit/bed9ba73939071a647e34002b661f750f0a4b54c

Now if you try to execute batch

```
curl --location --request POST 'http://localhost:60605/$batch' \
--header 'Content-Type: multipart/mixed;boundary=changeset_5b6a4369-0691-426c-89c4-1213e30250b3' \
--data-raw '--batch_43b8fcbc-2040-47d8-b9fc-4a165d83cfff
Content-Type: multipart/mixed; boundary=changeset_5b6a4369-0691-426c-89c4-1213e30250b3

--changeset_5b6a4369-0691-426c-89c4-1213e30250b3
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 1

POST http://localhost:60605/Regions HTTP/1.1
OData-Version: 4.0
OData-MaxVersion: 4.0
Content-Type: application/json;odata.metadata=minimal
Accept: application/json;odata.metadata=minimal
Accept-Charset: UTF-8
User-Agent: Microsoft.OData.Client/7.6.1
Accept-Language: en-US
X-Accept-Ui-Culture: en-US

{"@odata.type":"#Microsoft.Restier.Samples.Northwind.AspNet.Data.Region","RegionID":100, "RegionDescription": "region-100", "Territories": []}
--changeset_5b6a4369-0691-426c-89c4-1213e30250b3--
--batch_43b8fcbc-2040-47d8-b9fc-4a165d83cfff--
'
```

you'll receive a response containing

> {"Message":"No HTTP resource was found that matches the request URI 'http://localhost:60605/Regions'.","MessageDetail":"No route data was found for this request."}

It's all along of HttpConfigurationExtensions.MapRestier. In previous version the method accepted an ODataBatchHandler which was registered. Now there just is a bool parameter allowing to use batch handler. But it's instatiated using GlobalConfiguration.DefaultServer and OWIN isn't working with it. I've added an overload of the method MapRestier accepting HttpServer and used it in 

https://github.com/newclaus/RESTier/commit/ffd75536201970c2a8e7b35807da6812f346fdbd

So in this way it works

**Comment by jspuij** [comment]
This is because GlobalConfiguration.Defaultserver is null in Owin environments.. @robertmclaws it seems we missed this one and there is good reason why the batcher was not created by the framework. Ideas, other than changing MapRestier again to accept a BatchHandler?

See https://github.com/OData/RESTier/blob/d414f2807806f84ef15a0c2e857093af02f3e0b3/src/Microsoft.Restier.AspNet/Extensions/HttpConfigurationExtensions.cs

**Comment by robertmclaws** [comment]
Looks like we may just be able to do a null check and then do this: https://github.com/OData/WebApi/issues/976#issuecomment-303673128

**Comment by jspuij** [comment]
We cannot create the server from the configuration, as the user might want to do that themselves and change properties on it.

**Comment by robertmclaws** [comment]
Let's have a chat at some point and mess around with some options... I feel like there is a way to make it work for now... remembering that the batch handler is fundamentally broken from a DI standpoint anyway, and so we really shouldn't be letting people mess with it in this iteration.

**Comment by jspuij** [comment]
Agree. There is an even worse issue: The RestierBatchHandler needs to be registered with servicetype as <ODataBatchHandler> like this:

```
 if (batchHandler != null)
                {
                    builder.AddService<ODataBatchHandler>(Microsoft.OData.ServiceLifetime.Singleton, sp => batchHandler);
                }
```

If you don't, you get the following exception:
`
System.Net.Http.UnsupportedMediaTypeException: 'No MediaTypeFormatter is available to read an object of type 'EdmEntityObject' from content with media type 'multipart/mixed'.'
`

Just spent two days tracking this issue down.
