### ISSUE TITLE
Assigning explicit namespace in RestierModelBuilder breaks scenarios with entities from multiple namespaces

### ISSUE THREAD

**Issue by vvdev** [OData/RESTier#659]
RestierModelBuilder assigns ODataConventionModelBuilder.Namespace to first namespace of entity types (https://github.com/OData/RESTier/blob/2b357358ec3878ceac4ffeecbbcb6f830ffc5ca0/src/Microsoft.Restier.AspNet/Model/RestierModelBuilder.cs#L47 ).
That is, probably, ok for projects where all entity types are located in one namespace but breaks most of scenarios if entity types come from more than one namespace.

In our project we have an assembly which defines all entity types. That assembly is shared between server and client sides, we do not generate proxy/DTOs to access RESTier endpoint.

All worked fine with prev release (https://github.com/OData/RESTier/releases/tag/1.0.0-beta) but got broken when we upgrade to latest release
Everything works with latest code base IF I comment out that string.

I propose to assign ODataConventionModelBuilder.Namespace ONLY if all entity types come from the same namespace, otherwise leave it in default state (string constant "Default"). But even in case of single namespace it looks like that it is not needed to assign this Namespace property explicitly (seems like OData implementations anyway take first NS of entity types to expose as Namespace attribute of  Schema element in $metadata).
Additionally we can think about the possibility to explicitly set/override this Namespace if needed.

### Assemblies affected
1.0.0-rc1.20191003.1
https://github.com/OData/RESTier/releases/tag/1.0.0-rc1.20191003.1

### Reproduce steps
Define entities in more than one namespace, create EF6 DbContext, expose using RESTier.
On client side use basic DataServiceContext to access RESTier endpoint, override ResolveName with string ResolveNameFromType(Type type) => type.FullName;  

### Expected result
Simple and complex queries, CRUD operations posted with SaveChangesOptions.BatchWithSingleChangeset work fine.

### Actual result
There is no way to  to write single straightforward implementation of Type->Name/EntitySet name  resolution, one or another data access scenario fails depending on "hacks" in ResolveName implementation.

**Comment by robertmclaws** [comment]
So, I dug into this a little bit, and the only thing that was changed between Beta and RC1 was that I simplified the ODataModelBuilder constructor to include that line inline, whereas before it was separate.

In the Restier APIs I've built, where the model is more complex than what Restier is expecting, we've had to 100% take over model generation ourselves.

I would like to have a way at some point to just plug into what Restier generates and modify that before it is committed to the pipeline, but that won't make it info V1.

So I think the behavior you're experiencing may actually be on the DataServiceContext side (potentially a bug that has since been fixed) and not on the Restier side.

The solution in this case is to use code to manually construct the model, and don't explicitly set the Namespace. I know that's not ideal, but it should get you back up and running.

**Comment by vvdev** [comment]
@robertmclaws, thanks for your response.

But as a short term/temp solution: if you just remove that line - wouldn't it fix "my" issue and at the same time keep working for the rest of scenarios?
Or are there scenarios where that Namespace is really must be set to function?

Currently i downloaded the code, commented out that line, built and use these DLLs in our solution - works for now but not too elegant and maintainable :)

**Comment by robertmclaws** [comment]
If I remove that line, I'm concerned it will fix you but break everyone else.

As a general rule, I do not recommend using the DataServiceContext anymore. The code is simply too old. I recommend Simple.OData.Client instead. We don't have any unit tests that run DataServiceContext requests through Restier APIs, so we can't guarantee that behavior.

So, because swapping out your clients is not likely, this is a more maintainable solution:

```csharp
    public class YourDbContextModelBuilder : IModelBuilder
    {

        public Task<IEdmModel> GetModelAsync(ModelContext context, CancellationToken cancellationToken)
        {
            var modelBuilder = new ODataConventionModelBuilder();
            
            // RWM: Register each of your entities like this:
            var model1 = modelBuilder.EntitySet<YourEntity>("YourEntities");
            // RWM: Here you can also hide things and manipulate required values.
           //model1.EntityType.Ignore(c => c.IsDeleted);

            // RWM: Register each of your non-entity models like this:
            modelBuilder.ComplexType<SomeNonEntityType>();

            return Task.FromResult(modelBuilder.GetEdmModel());
        }

    }
```
and then register it this way:
```csharp
            config.UseRestier<YourRestierApi>((services) =>
            {
                // This delegate is executed after OData is added to the container.
                // Add you replacement services here.
                services.AddEF6ProviderServices<YourDbContext>()
                    .AddChainedService<IModelBuilder, YourDbContextModelBuilder>()
                    .AddSingleton(new ODataValidationSettings
                    {
                        MaxAnyAllExpressionDepth = 3,
                        MaxExpansionDepth = 3,
                    });
            });
```

HTH!

**Comment by vvdev** [comment]
@robertmclaws, thank you very much!
I was able to override default restier's model builder behavior and now it works :)

Thanks a lot for your effort, it's simply invaluable.

**Comment by robertmclaws** [comment]
Glad it worked, thanks so much! At some point, I'd love to hear more about your project and what you're using Restier for. Please feel free to email me at robert at nimbleapps dot cloud. Have a great day!

**Comment by vvdev** [comment]
@robertmclaws, i'm sorry to post again under closed issue, but i have some new input.

I made some research i now i'm 99.99% sure that ODataConventionModelBuilder.Namespace should be explicitly set ONLY when all entity types are defined in the same clr namespace.

Please compare two files attached: they contain $metadata output with and without ODataConventionModelBuilder.Namespace set.

The difference is: when we set Namespace, ODataConventionModelBuilder ignores clr namespace of entity types and expose metadata with original type names BUT with one and the same Namespace (we assign to the property). Check navigation property definitions, i think there the problem is most visible. In runtime when data modification request is coming from client, i guess, RESTier just cant map entity set types to actual CLR types.

At the same time when we don't set Namespace all type name+namespace are preserved and map 1 to 1 to corresponding CLR types.

I found similar case on stackoverflow [https://stackoverflow.com/questions/27688728/odataconventionmodelbuilder-with-multiple-namespaces]


So i'm not trying to say that behavior of RestierModelBuilder must be changed ASAP (especially because workaround is known), but it definitely is something to research and think more before one of coming releases/package updates.

[Restier Metadata with ODataConventionModelBuilder.Namespace set.txt](https://github.com/OData/RESTier/files/3955607/Restier.Metadata.with.ODataConventionModelBuilder.Namespace.set.txt)
[Restier Metadata WITHOUT ODataConventionModelBuilder.Namespace set.txt](https://github.com/OData/RESTier/files/3955608/Restier.Metadata.WITHOUT.ODataConventionModelBuilder.Namespace.set.txt)

PS: i'll write you about our project and RESTier usage experience as soon as we fully migrate our solution to all up to ate code, it will take couple of weeks :)
