### ISSUE TITLE
TypeOf queries return ResourceNotFound unless trailing slash added to the Path part of the url

### ISSUE THREAD

**Issue by vvdev** [OData/RESTier#661]
Found a behavior change.

Current version properly processes OfType queries ONLY when trailing slash is added to the path part of the url, otherwise returns ResourceNotFound.

Examples:
Doesn't work: http://localhost:10257/odata/v4/restier/WarehouseExpenseOperation/Domain.Warehouse.WarehouseTransitionOperation
http://localhost:10257/odata/v4/restier/WarehouseExpenseOperation/Domain.Warehouse.WarehouseTransitionOperation?$expand=Items

Works:
http://localhost:10257/odata/restier/WarehouseExpenseOperation/Domain.Warehouse.WarehouseTransitionOperation/
http://localhost:10257/odata/v4/restier/WarehouseExpenseOperation/Domain.Warehouse.WarehouseTransitionOperation/?$expand=Items

As i got from OData docs trailing slash is not required by standard: http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_AddressingDerivedTypes

That definitely worked with previous version 1.0.0-beta and got broken after upgrade to the latest 1.0.0-rc1.20191003.1

### Assemblies affected
1.0.0-rc1.20191003.1
https://github.com/OData/RESTier/releases/tag/1.0.0-rc1.20191003.1

### Reproduce steps
Base class Domain.Warehouse.WarehouseExpenseOperation, derived class Domain.Warehouse.WarehouseTransitionOperation

Entity Set WarehouseExpenseOperation

Query for subtype `WarehouseExpenseOperation.OfType<WarehouseTransitionOperation>()`

### Expected result
http://localhost:10257/odata/v4/restier/WarehouseExpenseOperation/Domain.Warehouse.WarehouseTransitionOperation
request sent and server returns all instances of WarehouseTransitionOperation

### Actual result
server returns ResourceNotFound

**Comment by robertmclaws** [comment]
@vwdev Are you making raw queries or using an OData client library?

**Comment by vvdev** [comment]
@robertmclaws, our code uses client inherited from Microsoft.OData.Client.DataServiceContext to make calls, but during investigation i also made raw queries - that's how i found that trailing slash in Path part helps.

**Comment by robertmclaws** [comment]
Hey @mikepizzo do you have any idea why this might have happened?

**Comment by robertmclaws** [comment]
@vvdev Any chance you could check to see if this is still happening in RC8? If so we can look into it. Thanks!

**Comment by vvdev** [comment]
@robertmclaws, i'm sorry, but will be unable to try it for next 3-5 weeks, after that will check.

**Comment by robertmclaws** [comment]
I'm closing this as stale. If it's still an issue, please let us know!
