### ISSUE TITLE
Targeting .NET 5.0 for Restier v2

### ISSUE THREAD

**Issue by fileman** [OData/RESTier#668]
After reading [https://devblogs.microsoft.com/odata/move-odata-to-net-5/](https://devblogs.microsoft.com/odata/move-odata-to-net-5/), I think is better to skip .net 3.1 and go directly to .net 5.x (where x is the LTS version number)

**Comment by fileman** [comment]
today I have watched [this community standup ](https://www.youtube.com/watch?v=LNczo0feHaw)... if I didn't misunderstand it's in your plan.

**Comment by Necromant24** [comment]
it will be good to migrate RESTier to dotnet 5, and add samples with role based authentification
