### ISSUE TITLE
"The request resource is not found." when filtering using nullable int entity field

### ISSUE THREAD

**Issue by RazvanManolache** [OData/RESTier#669]
Restier throws exception on filter on nullable entity fields.

### Assemblies affected
Microsoft.Restier.Core-latest (2020/07/09 - from sources)

### Reproduce steps
So i'm doing this filter on an entity
`http://localhost/DataService/api/VgDeliverables?$filter=(((Id%20ne%200)%20and%20(Name%20eq%20%27asdf234234%27))%20and%20(IdCompany%20eq%2092))`

nicer format for the filter:
`$filter: (((Id ne 0) and (Name eq 'asdf234234')) and (IdCompany eq 92))`

### Expected result
to get an empty array like this one
{"@odata.context":"http://localhost/DataService/api/$metadata#VgDeliverables","value":[]}

### Actual result
`{"error":{"code":"","message":"An error has occurred.","innererror":{"message":"The request resource is not found.","type":"Microsoft.Restier.Core.StatusCodeException","stacktrace":"   at MethodCallExpression Microsoft.Restier.Core.Query.DefaultQueryHandler.CheckWhereCondition(MethodCallExpression methodCallExpression) in ....`

If it finds a record it doesn't crash with error ResourceNotFound. Only if it doeswn't find a record,it throws the exception. 

I'm talking about this code in restier.core:

```
var rightExpression = binaryExpression.Right as ConstantExpression;
if (rightExpression != null && rightExpression.Value != null)
{
       // This means where statement is key segment but not for $filter
      throw new StatusCodeException(HttpStatusCode.NotFound, Resources.ResourceNotFound);
}
```

the binary expression value looks something like
`{((Convert((($it.Id != value(Microsoft.AspNet.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.Int32]).TypedProperty) AndAlso ($it.Name == value(Microsoft.AspNet.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.String]).TypedProperty))) AndAlso ($it.IdCompany == Convert(value(Microsoft.AspNet.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.Int32]).TypedProperty))) == True)}`

It gets there because in the below code it skips checks if any records are returned

```
private static async Task CheckSubExpressionResult(
            QueryContext context,
            IEnumerable enumerableResult,
            QueryExpressionVisitor visitor,
            IQueryExecutor executor,
            Expression expression,
            CancellationToken cancellationToken)
        {
            **if (enumerableResult.GetEnumerator().MoveNext())**
            {
                // If there is some result, will not have additional processing
                return;
            }
```
### Additional details
It does get weirder. IdCompany is int?. If it's not nullable it works fine.

it checks the where, but the binaryexpression looks like: 
`{((($it.Id != value(Microsoft.AspNet.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.Int32]).TypedProperty) AndAlso ($it.Name == value(Microsoft.AspNet.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.String]).TypedProperty)) AndAlso ($it.IdCompany == value(Microsoft.AspNet.OData.Query.Expressions.LinqParameterContainer+TypedLinqParameterContainer`1[System.Int32]).TypedProperty))}`

and so it has no problem

**Comment by RazvanManolache** [comment]
After another weird error

'Cannot compare elements of type 'System.Collections.Generic.ICollection`1 Only primitive types, enumeration types and entity types are supported

I figured out through some debugging and trial and error that i need to set HandleNullPropagation to HandleNullPropagationOption.False. Future reference for people struggling:

 config.UseRestier<SmartCommunication.WCF.RestierContext>((services) => {
                    services.AddEF6ProviderServices<MyContext>();
                    
                    services.AddSingleton(new ODataQuerySettings()
                    {
                        EnableConstantParameterization = true,
                        EnableCorrelatedSubqueryBuffering = true,
                        EnsureStableOrdering = true,
                        **HandleNullPropagation = HandleNullPropagationOption.False,**
                        HandleReferenceNavigationPropertyExpandFilter = true
                        
                    });
                    //services.AddSingleton(typeof(ISecurityHelper), SecurityHelper.Instance);
                });

**Comment by robertmclaws** [comment]
Thanks for digging into this, I really appreciate you taking the time!

I'm checking in a small change to `CheckWhereCondition` to write an additional message to the Console to set `HandleNullPropagation` and to see your comment above for more details. I will also make sure that it gets added to the documentation.

Thanks for your contribution! 👊🏻
