### ISSUE TITLE
TripPinRESTierService fails with query parameter $count and $top

### ISSUE THREAD

**Issue by erlethor** [OData/RESTier#670]
There seems to be a bug in the public sample implementation of OData v4:
https://services.odata.org/TripPinRESTierService/

_I am afraid I don't know if this is the right place to address this bug. If not, do you have some advice where to create this issue? Or maybe you could kindly forward it in case you know._

Combining $count with $top or $skip causes an error.

### Reproduce steps
This works: 
https://services.odata.org/TripPinRESTierService/People?$count=true

This causes an error:
https://services.odata.org/TripPinRESTierService/People?$count=true&$top=10

### Expected result
Response with ` "@odata.count"`and up to 10 entries

### Actual result

**500 Internal Server Error**
``` JSON
{"error":{"code":"","message":"An error has occurred."}}
```

**Comment by fileman** [comment]
the sample is based on RC1

**Comment by robertmclaws** [comment]
Hmmm, this still exists. @mikepizzo could you please look into it when you get a chance? Maybe the bits need to be updated? Thanks!

**Comment by mikepizzo** [comment]
Fixed by using latest Microsoft.AspNet.OData.

**Comment by erlethor** [comment]
Thanks a lot for fixing this issue
