### ISSUE TITLE
Using both ConventionBased Interceptors and CustomSubmitProcessor

### ISSUE THREAD

**Issue by andreav** [OData/RESTier#672]
After upgrading RESTier it seems like the combination of ConventionBased Interceptors and CustomSubmitProcessor is no more working.

Before upgrading I had some working code like the following for triggering both convention based interceptors and CustomSubmitProcessor:

        // inside my Restier ODataController
        public static new Microsoft.Extensions.DependencyInjection.IServiceCollection ConfigureApi(System.Type apiType, IServiceCollection services)
        {
            return EntityFrameworkApi<MyEntities>.ConfigureApi(apiType, services)
                .AddService<IChangeSetItemFilter, CustomizedSubmitProcessor>()
        }

        // Inside CustomizedSubmitProcessor .cs
        public class CustomizedSubmitProcessor : IChangeSetItemFilter
        {
            public Task OnChangeSetItemProcessedAsync(SubmitContext context, ChangeSetItem item, CancellationToken cancellationToken)
            {
                   // some stuff here

                   return Inner.OnChangeSetItemProcessedAsync(context, item, cancellationToken);
            }
        }

        // again, inside Restier ODataController
        protected void OnInsertedMyEntity(EEB.DataAccess.MyEntity myentity)
        {
                   // some code
        }

After ugrading I had to change both the registration of my CustomizedSubmitProcessor and return statement into the OnChangeSetItemProcessedAsync (maybe this is the problem?)

        // inside WebApiConfig.cs
        config.UseRestier<MyODataCotroller>((services) =>
            {
                services.AddEF6ProviderServices<MyEntities>();

                services.AddChainedService<IChangeSetItemFilter>((sp, next) => new CustomizedSubmitProcessor());
            });

        // Inside CustomizedSubmitProcessor .cs
        public class CustomizedSubmitProcessor : IChangeSetItemFilter
        {
            public Task OnChangeSetItemProcessedAsync(SubmitContext context, ChangeSetItem item, CancellationToken cancellationToken)
            {
                   // some stuff here

                   return Task.FromResult<object>(null);     // <---- this is the change
            }
        }

Before the upgrade: when inserting one entity , both methods where invoked:
- CustomizedSubmitProcessor::OnChangeSetItemProcessedAsync
- OnInsertedMyEntity

After the upgrade:
- If I register my CustomizedSubmitProcessor  only the CustomizedSubmitProcessor::OnChangeSetItemProcessedAsync is invoked.

- If I do not register my CustomizedSubmitProcessor , the interceptor is invoked.

Is it possible to restore the previous behavior?

### Assemblies affected
master branch, commit 88d5ab0

### Reproduce steps
Register both a ConventionBased Interceptor and a CustomSubmitProcessor

### Expected result
Both callback are invoked

### Actual result
Only one is invoked

**Comment by jspuij** [comment]
@andreav Restier builds a chain of IChangeSetItemFilter instances. There are multiple, even within Restier itself. You will have to call 

`Inner.OnChangeSetItemProcessedAsync(context, item, cancellationToken);`

or the chain is aborted and further processing isn't done.

**Comment by robertmclaws** [comment]
@andreav Did this get handled? In Restier v2 calling the inner handler will not be necessary, since there will be a much more intuitive pipeline design.

**Comment by andreav** [comment]
Hello,
I'm no more on that project from a long time ago.

Sorry but honestly I do not remember.
