### ISSUE TITLE
Is the RESTier product dead?

### ISSUE THREAD

**Issue by Vaccano** [OData/RESTier#676]
I see that there has been no checkins for 2 years.  But the Microsoft Docs link here as the replacement of WCF Data Services.

I am confused.  Are the docs just out of date?  Is this project no longer being worked on?

**Comment by Vaccano** [comment]
My bad.  I did not see that the source had been checked into two days ago.

**Comment by robertmclaws** [comment]
See this post for more details: https://github.com/OData/RESTier/issues/616#issuecomment-883656815
