### ISSUE TITLE
Bound Actions inside Api are not called anymore

### ISSUE THREAD

**Issue by HRasch** [OData/RESTier#679]
Bound Operations with parameters inside the Api-Class are not called anymore

### Assemblies affected
Microsoft.Restier.AspNet 1.0.0-rc6.20210327.5  

### Reproduce steps
Create a bound Operation with parameter like 

```
[Operation(IsBound = true, EntitySet = "Accounts", OperationType = OperationType.Action)]
public Account LinkAddress(Account account, int addressId)
{
    var address = DbContext.Set<Address>().Find(addressId);

    account.Addresses.Add(address);
    DbContext.SaveChanges();

    return account;
}
```

until rc6 this method could be called by

(Post) http://myservice:xxx/Accounts(4)/LinkAddress
{
   addressId: 6
}

### Expected result
the opertion should get called

### Actual result
Http 500 / 404 is returned

### Additional details
I tried it with namespace prefix, without... nothing worked. If i downgrade to rc5, the method get's called.
Maybe it's also possible to check how the proxy that get's generated with "OData Connected Service" would build the correct proxy definition. I always have trouble with namespace-prefixes. So the Restier-Routing should address this by offering an option if the operations are called including the namespace-prefix.

**Comment by robertmclaws** [comment]
Hey @Hrasch, thanks for letting us know. The initialization code changed quite a bit, can you please share your `config.UseRestier()` and `config.MapRestier` calls so I can see how your service is configured?

Thanks!

**Comment by HRasch** [comment]
Sure, here it is:
` config.UseRestier<NVShopContextApi>(services => services
                .AddEF6ProviderServices<NVShopContext>()
                .AddSingleton(new ODataValidationSettings
                {
                    MaxAnyAllExpressionDepth = 3,
                    MaxExpansionDepth = 3
                })
                .AddChainedService<IQueryExpressionSourcer>((sp, next) => new EFQueryExpressionSourcer())
                .AddChainedService<IQueryExpressionAuthorizer>((sp, next) => new EFQueryExpressionAuthorizer())
                .AddChainedService<IChangeSetInitializer>((sp, next) => new EFChangeSetInitializer())
            );

            config.MapHttpAttributeRoutes();

            config.MapRestier<NVShopContextApi>("NVDataContextApi", "odata", true);`

**Comment by robertmclaws** [comment]
Yeah I need to see the version for RC 6 please. Thanks!

**Comment by HRasch** [comment]
RC6:
```
public static void Register(HttpConfiguration config)
{
    config.Filter().Expand().Select().OrderBy().MaxTop(null).Count();

    //config.SetUseVerboseErrors(true);
    config.UseRestier(builder => builder.AddRestierApi<NVShopContextApi>(services => services
        .AddEF6ProviderServices<NVShopContext>()
        .AddSingleton(new ODataValidationSettings
        {
            MaxAnyAllExpressionDepth = 3,
            MaxExpansionDepth = 3
        })
        .AddChainedService<IQueryExpressionSourcer>((sp, next) => new EFQueryExpressionSourcer())
        .AddChainedService<IQueryExpressionAuthorizer>((sp, next) => new EFQueryExpressionAuthorizer())
        .AddChainedService<IChangeSetInitializer>((sp, next) => new EFChangeSetInitializer())
    ));

    config.MapHttpAttributeRoutes();

    config.MapRestier(builder => builder.MapApiRoute<NVShopContextApi>("NVDataContextApi", "odata", true));
}
```

I tested a little but around and wrote a test-method like this:

```
public class Publisher
{

    public string Id { get; set; }
    public string Name { get; set; }
    ...
}
```

```
[TestMethod]
        public async Task BoundAction()
        {
            var payload = new
            {
                Name = "Test"
            };

            var response = await RestierTestHelpers.ExecuteTestRequest<LibraryApi, LibraryContext>(HttpMethod.Post, resource: "/Publishers('Publisher2')/ChangeName", payload: payload, acceptHeader: WebApiConstants.DefaultAcceptHeader);
            var content = await TestContext.LogAndReturnMessageContentAsync(response);

            response.IsSuccessStatusCode.Should().BeTrue();
            response.StatusCode.Should().Be(HttpStatusCode.OK);
        }
```
This could call this new api-method:

```
[Operation(IsBound = true, OperationType = OperationType.Action, EntitySet = "publisher")]
public Publisher ChangeName(Publisher publisher, string name)
{
    if (publisher == null)
    {
        throw new ArgumentNullException(nameof(publisher));
    }

    Console.WriteLine($"Id = {publisher.Id}");
    publisher.Name = name;

    return publisher;
}

```

with this test I could call the method, but no chance in my project. I thought it may depend on the parameter and that it may have become case sensitive or something. A HTTP-GET on the address "http://localhost:54252/odata/Accounts(6)" returns a valid account-record, but if I try to call the bound operation with postman, I had no luck at all. 

With the rc2 i didn't had this problems, but i know, the rewriting to .net 5.0 changed a lot.

My goal is it in the end to use the OData Connected Service to create a c# proxy class. But at moment I'm not even able to create a Postman request that targets my operation.

With the RC6 i always get a 404, no matter what i do :-(

**Comment by robertmclaws** [comment]
Can you try taking out the 3 chained services and seeing if that works? Restier registers those under the covers for you, so that might be interfering.

The issue could also be that Breakdance changed quite a bit in RC6, and so the build you have may not work for testing anymore. The `RestierTestHelper` class is moving to a new `Microsoft.Restier.Breakdance` package, but we've had a few issues getting that package published that we're trying to work out.

But try taking out the 3 chained services, and see if the function is showing up in the `/odata/$metadata` endpoint. Thanks!

**Comment by HRasch** [comment]
Hm, I currently need the QueryExpressionSourcer and the ChangeSetInitializer cause they are custom implementations. Restier expects to have properties that have the same name like the entities. I don't have this properties in my ef model, i just use the generic set method with a repository-pattern. So i detect the type instead of a property name and call the generic method instead. But I will review if this error may depend on my custom implementations.

**Comment by HRasch** [comment]
There are just two small modifications to the default Initializer / Sourcer:

```
internal class EFQueryExpressionSourcer : IQueryExpressionSourcer
{
  public Expression ReplaceQueryableSource(QueryExpressionContext context, bool embedded)
  {
      //Ensure.NotNull(context, nameof(context));

      if (context.ModelReference.EntitySet == null)
      {
          // EF provider can only source *ResourceSet*.
          return null;
      }

      dynamic api = context.QueryContext.Api;

      var dbContext = api.DbContext as DbContext;

      var entityType = dbContext.GetSetTypeByName(context.ModelReference.EntitySet.Name);
      var setMethod = dbContext
          .GetType()
          .GetMethods()
          .FirstOrDefault(x => x.Name == "Set" && x.IsGenericMethod);

      var dbSet = setMethod.MakeGenericMethod(entityType)
          .Invoke(dbContext, new object [] {});

      return Expression.Constant(dbSet);
  }
}
```
Initializer:

```
public async override Task InitializeAsync(SubmitContext context, CancellationToken cancellationToken)
{
    if (context == null)
    {
        throw new ArgumentNullException(nameof(context));
    }

    dynamic api = context.Api;
    var dbContext = api.DbContext as DbContext;

    foreach (var entry in context.ChangeSet.Entries.OfType<DataModificationItem>())
    {
        var resourceType = dbContext.GetSetTypeByName(entry.ResourceSetName);

        // This means request resource is sub type of resource type
        if (entry.ActualResourceType != null && resourceType != entry.ActualResourceType)
        {
            // Set type to derived type
            resourceType = entry.ActualResourceType;
        }
        //...
```
And the extension Method:
```
public static Type GetSetTypeByName(this DbContext dbContext, string name)
{
    var efModel = ((IObjectContextAdapter)dbContext).ObjectContext.MetadataWorkspace;
    var efContainer = efModel.GetItems<EntityContainer>(DataSpace.CSpace)
        .FirstOrDefault(x => x.Name == dbContext.GetType().Name);
    var efEntitySet = efContainer.EntitySets.FirstOrDefault(x => x.Name.Equals(name));
    var efEntityType = efEntitySet.ElementType;

    var itemCollection = (ObjectItemCollection)efModel.GetItemCollection(DataSpace.OSpace);
    var objectSpaceType = efModel.GetObjectSpaceType(efEntityType);
    var clrType = itemCollection.GetClrType(objectSpaceType);

    return clrType;
}
```

Btw, it would be nice if the logic to determine the Set could be factored out...

There is no problem to get data from the sets. Even the metadata is correct. For me it looks like there's a problem with the routing.

I thought it may belong to the Url-Dot Problem, but it worked on rc2 correctly and I have this Entry for the ExtensionlessUrlHandler in my web.config.

   ```
 <handlers>
      <remove name="ExtensionlessUrlHandler-Integrated-4.0"/>
      <remove name="OPTIONSVerbHandler"/>
      <remove name="TRACEVerbHandler"/>
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0"/>
    </handlers>
```

**Comment by robertmclaws** [comment]
Try adding a trailing slash to the second parameter on MapApiRoute and see what happens. I think it needs to be "odata/" not "odata".

**Comment by robertmclaws** [comment]
[This test is passing](https://github.com/OData/RESTier/blob/master/src/Microsoft.Restier.Tests.AspNet/FeatureTests/FunctionTests.cs#L113-L125), so the issue could also be that you don't have the updated Breakdance binaries yet. We brought Breakdance into the Restier product, but are not able to publish the NuGet package yet due to a certificate issue. If you're still using the old CloudNimble.Breakdance.Restier, then the tests will fail.

**Comment by HRasch** [comment]
I think this test covers an other usecase. This function is bound to the collection, my function binds to a single record. My expectation is that the entity is adressed by the url parameter (key) and then the function is called with the adressed entity as first parameter (if i understood odata correctly, but that's how it worked in the past).

`http://myservice:xxx/odata/Accounts(4)/LinkAddress`

the payload in the body then parses to the parameters of the method in the Api-Class


```
public class NVShopContextApi : EntityFrameworkApi<NVShopContext>
{
      //.... ctro aso


      [Operation(IsBound = true, EntitySet = "Accounts", OperationType = OperationType.Action)]
      public Account LinkAddress(Account account, int addressId)
      {
          var address = DbContext.Set<Address>().Find(addressId);
      
          account.Addresses.Add(address);
          DbContext.SaveChanges();
      
          return account;
      }
```

The Method appears in the metadata and imo the definition is correct.

```
<Action Name="LinkAddress" IsBound="true" EntitySetPath="Accounts">
<Parameter Name="account" Type="NVShop.Core.Domain.Account"/>
<Parameter Name="addressId" Type="Edm.Int32" Nullable="false"/>
<ReturnType Type="NVShop.Core.Domain.Account"/>
</Action>
```

When I use the OData Connected Services to generate a proxy for my service, an extension method is generated. There's a small problem with the namespace-prefix, so i removed it, because i think restier don't support namespace prefixes on the methods.

```
[global::Microsoft.OData.Client.OriginalNameAttribute("LinkAddress")]
public static global::Microsoft.OData.Client.DataServiceActionQuerySingle<global::NV.ERP.eGate.Proxy.Account> LinkAddress(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::NV.ERP.eGate.Proxy.Account> _source, int addressId)
{
    if (!_source.IsComposable)
    {
        throw new global::System.NotSupportedException("The previous function is not composable.");
    }

    return new global::Microsoft.OData.Client.DataServiceActionQuerySingle<global::NV.ERP.eGate.Proxy.Account>(_source.Context, _source.AppendRequestUri("LinkAddress"), new global::Microsoft.OData.Client.BodyOperationParameter("addressId", addressId));
}
```

The proxy is correctly generated as DataServiceSingleQuery, with a simple parameter. Even the parameter is generated in lowercase.

On the client side, i simple call this method like 

`container.Accounts.ByKey(account.Id).LinkAddress(address.Id).GetValue();`

With RC6 is always get a http 404 as result.

The difference to the mentioned test case is that the account-entity is addressed by it's key. I haven't found any test that covers this case. All action tests pass the entity as first parameter together with the payload.

**Comment by robertmclaws** [comment]
Can you please send me the contents of the payload you are posting to that method?

Thanks!

**Comment by HRasch** [comment]
![image](https://user-images.githubusercontent.com/23297306/114220783-b8bf6200-996c-11eb-8ea7-dd68ea17d61d.png)

**Comment by HRasch** [comment]
I have another guess. I took the source and included it to my project to check out why i always get a http 404. The result was that some requests are do not even hit the RestierRoutingConvention. 

```
POST: http://localhost:54252/odata/Accounts(6)/LinkAddress

POST: http://localhost:54252/odata/Accounts(6)/NVShop.Core.Domain.LinkAddress

```
When i change the address to something invalid without a dot, the RoutingConvention the breakpoint in SelectController is hit. 

Cause of this I guess it may have something to do not with restier itself but with Microsoft.AspNet.OData and the routing-convention. Now I downgraded to Microsoft.AspNet.OData to version 7.4.1 and Restier to Version 1.0.0-rc4.20200909.1. 

Now, when I call the the method with my client-proxy, the action is called again. My guess is: Something changed in the Microsoft.AspNet.OData library with the odata routing and the restier converter is not called anymore.

**Comment by robertmclaws** [comment]
So I'm building a unit test in the codebase to test this. However, I suspect the issue MIGHT be that the payload is spelled incorrectly: you're missing a 'd' in addressId.

**Comment by robertmclaws** [comment]
Also, you're not hitting the routing convention because there was a change in how Restier handles the bindings. Take the EntitySet out of the OperationAttribute and fix your payload spelling mistake and let me know if you hit it.

**Comment by robertmclaws** [comment]
We have released an updated version to NuGet. Please grab 1.0.0-rc6.20210412.2, and make the changes I specified in my last post, and you should be good to go.

**Testing your scenario:**
- Api method is [here](https://github.com/OData/RESTier/blob/master/src/Microsoft.Restier.Tests.Shared/Scenarios/Library/LibraryApi.cs#L116-L125).
- Unit test supporting it is [here](https://github.com/OData/RESTier/blob/master/src/Microsoft.Restier.Tests.AspNet/FeatureTests/FunctionTests.cs#L60-L79).

**Comment by HRasch** [comment]
Thank you very much for your efforts, I will test it out and give you a feedback. A short question because I noticed a little difference in the url: is it correct that some brackets on the method are required? Just wondering because innerer noticed them before and can‘t remember that they are generated from the Proxy.

**Comment by HRasch** [comment]
In the lastest version, the actions are called again if I remove the namespaces that are prefixed from the odata connected services. :-)

**Comment by robertmclaws** [comment]
Outstanding! I'm going to go ahead and close this, please feel free to re-open if it continues to be a problem. Thanks so much!
