### ISSUE TITLE
Disable signing on the test DLLs and samples.

### ISSUE THREAD

**Issue by jspuij** [OData/RESTier#685]
We might want to try and disable signing on the test DLLs and samples to be able to use the Simple OData client to end-to-end test our APIs.

**Comment by jspuij** [comment]
On investigation, this isn't so easy, as a lot of InternalsVisibleTo attributes from the main assemblies point to the test assemblies. We would have to adjust quite a few unit tests, not sure whether that's worth it.
However, it seems Simple OData Client is reconsidering signing its packages, which would be really helpful for us:

https://github.com/simple-odata-client/Simple.OData.Client/issues/806

**Comment by robertmclaws** [comment]
Simple.OData.Client is now shipping as a signed assembly, so we're able to leverage it in our unit tests to ensure proper batch behavior, without breaking the build process.
