### ISSUE TITLE
RESTier provider for Swagger

### ISSUE THREAD

**Issue by karataliu** [OData/RESTier#69]
Investigation/Implementation of RESTier provider for services with Swagger document.

**Comment by joshbooker** [comment]
Yes please make this a priority so we can use RESTier with Azure App Service.  Related issue:
https://github.com/OData/WebApi/issues/278

**Comment by 0xced** [comment]
Swashbuckle.OData already [supports RESTier routes for top-level entity types](https://github.com/rbeauchamp/Swashbuckle.OData#restier).

**Comment by robertmclaws** [comment]
As previously mentioned, Swashbuckle.OData already supports this. I'm closing for now, but if you try 1.0 Beta 2 and experience an issue, please open a new ticket and we'll address it. Thanks!
