### ISSUE TITLE
Has anyone tried to add OpenAPI/Swashbuckel/Swagger to this solution.

### ISSUE THREAD

**Issue by ssquiresusps** [OData/RESTier#690]
*Short summary (3-5 sentences) describing the issue.*  

### Assemblies affected
*Which assemblies and versions are known to be affected e.g. RESTier 0.4.0-rc2.*  

### Reproduce steps
*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*  

### Expected result
*What would happen if there wasn't a bug.*  

### Actual result
*What is actually happening.*  

### Additional details
*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by ssquiresmn** [comment]
This question relates to the Microsofr.Restier.Samples.Northwind.AspNetCore project. As best I can tell it looks like the specific Entities to be exposed to the swagger/openapi spec might be done in the restierapibuilderextension.cs maybe under line 56?   If I wanted to use the restier framework against the northwind database and wanted to limit what was exposed entities to HttpGets on Orders, Customers & Employees what where would I implement these changes?   I'd also like to leverage swashbuckle to create OpenAPI documents.

**Comment by robertmclaws** [comment]
Restier 1.1 comes with built in OpenAPI / Swagger support. Check out https://nuget.org/packages/Microsoft.Restier.AspNetCore.Swagger for more details!
