### ISSUE TITLE
Does RESTier supports CRUD directly to database tables or it only operates on strongly typed entities?

### ISSUE THREAD

**Issue by mehdipanjwani-ains** [OData/RESTier#693]
I would like to use RESTier but my database tables/views will be created by the users in future and are not known. Is RESTier suitable for such a need? 
In other words, does RESTier supports CRUD directly to tables or it only operates on dbcontext and strongly typed entities? 
Thanks.

**Comment by robertmclaws** [comment]
Closing this for now, we may consider it as a goal for Restier 2.0.
