### ISSUE TITLE
.NET6 Roadmap

### ISSUE THREAD

**Issue by 2002Ezio** [OData/RESTier#700]
In the wiki is reported the the support for .NET 5/6 and later is coming in the second half of 2021.

I'he found the branch "breakdance-net5", but it is not clear to me if it is ready to use in a project.

Is any roadmap on when it will be available?

Thank you

**Comment by robertmclaws** [comment]
Restier RC7 just released with .NET 6 support, and has also been checked into "Main". See the samples for more information :)
