### ISSUE TITLE
EntitySet filters are not fired when retrieving data via navigation properties

### ISSUE THREAD

**Issue by paulvanbladel** [OData/RESTier#71]
E.G. canonical customer order relation.
When I have an entityset filter on customers and request the customers the filter is applied. OK.
When I request orders and expand on customers:   /api/MyApi/Orders?$expand=Customers the customer filter is NOT applied.
That's not ok, because it makes it worthless as a vehicle for row level security. The customer data which is filtered out by the customer filter should NOT be included in the order data.

**Comment by joshbooker** [comment]
+1 Great Suggestion Paul!  Please make this a priority!

**Comment by karataliu** [comment]
Thanks for the feedback, we've put this in feature backlog.

Related in Vocabulary document:
http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/vocabularies/Org.OData.Capabilities.V1.xml

* NavigationRestrictions
* ExpandRestrictions

**Comment by advancedrei** [comment]
Any movement on this? It's a huge requirement for us.

Thanks!

**Comment by chinadragon0515** [comment]
support will be added to collection used in,
1. path segments
2. $expand
3. filter like Trips/Any(), then filter against Trips will be applied.
4. Type case includes expand, path segment.

And filter on single navigation property is not handled now.

**Comment by chinadragon0515** [comment]
Code merged, need to add docs before this issue been close, and one breaking change is before conversion Onfilter methos is OnFilter<EntitySet>, and now it will be OnFilter<EntityType>, and EntityType can only be based type which will be used to filter both base type and all derived type.

**Comment by chinadragon0515** [comment]
document updated, close the issue.
