### ISSUE TITLE
.NET Core 3.1, .NET 5, & .NET 6 support now in Restier RC7!

### ISSUE THREAD

**Issue by robertmclaws** [OData/RESTier#712]
Hey folks! Wanted to let you know that RC7 went out yesterday, and it now fully supports .NET Core variants, including running ASPNET Core 6.0 + Entity Framework Classic 6.0.

We're already running RC7 in production on a dozen systems, and it's ready for your use.

We anticipate 1.0 will go live in early May. So if you have any issues, please let us know.

**Comment by vincedan** [comment]
good news 😂

**Comment by JuanEstradaUY** [comment]
Hi, do you plan to fix the aggegations not working in the current code?
There is an open issue with more information here:
https://github.com/OData/RESTier/issues/667

**Comment by robertmclaws** [comment]
@JuanEstradaUY Please check the 1.0 RTM bits that chipped today and see if aggregations work for you now. Thanks!
