### ISSUE TITLE
SaveChange stopped working after upgrading to 1.0.0-rc8.20220714.1 from 1.0.0-rc6.20210412.2 

### ISSUE THREAD

**Issue by vendettamit** [OData/RESTier#716]
My application is unable to update any entities after upgrading to latest RC. It's throwing exception 'Method not found'. 

`Error - Method not found: 'System.Collections.Generic.IList`1<Microsoft.Restier.Core.Submit.ChangeSetItem> Microsoft.Restier.Core.Submit.ChangeSet.get_Entries()'.`

### Assemblies affected
Restier nuget package 1.0.0-rc8.20220714.1

### Reproduce steps
Here's the simplest sample that works in rc6 but not in rc8
```
	var ctx = ServiceProvider.GetRequiredService<Container>();
	var s = ctx.Settings.Find(x => x.ID == 1);
	
	s.Value = "Test3";
	ctx.UpdateObject(s);
	await ctx.SaveChangesAsync();
```
Works in 1.0.0-rc6.20210412.2 
But not in 1.0.0-rc8.20220714.1 

Here's my configuration:
	
```
			config.Filter().Expand().Select().OrderBy().MaxTop(1000).Count().SetTimeZoneInfo(TimeZoneInfo.Utc);

			config.UseRestier((builder) =>
			{
				// This delegate is executed after OData is added to the container.
				// Add your replacement services here.
				builder.AddRestierApi<MyContextApi>(services =>
				{
					// this gets called by Restier
					services.TryAddScoped(GetMyContext);
					services.AddEF6ProviderServices<CMECF.Common.Data.MyContext>();
					services.TryAddSingleton<IQueryExpressionAuthorizer, ODataAuthorizer>();
				});
			});


			// Web API routes. Setup before Restier otherwise it throws an exception
			config.MapHttpAttributeRoutes();

			config.MapRestier((builder) =>
			{
				builder.MapApiRoute<MyContextApi>("MyContext", "api/MyContext", true);
			});
		
```
			
What do I have to do to make it work again? I couldn't find any release notes for breaking changes (if any).

**Comment by vendettamit** [comment]
uhhh!!! Never mind. The Microsoft.Restier.EntityFramework is not a dependency and didn't update when I updated the Microsoft.Restier.Aspnet. After updating the EF package it worked.

**Comment by robertmclaws** [comment]
So a couple of notes:
- You should not need to register the DbContext yourself, it is registered automatically with AddEF6ProviderServices(). You can either access it as your specific type (in your case `MyContext`) OR a `DbContext`.
- Within an `[Operation]`, the `DbContext` property of `EntityFrameworkApi<>` already has the `DbContext` instance _scoped to the specific request_. So, you can just use that to do your work.

Glad the NuGet update worked, and hope all that helps!

**Comment by vendettamit** [comment]
Thank you @robertmclaws for the tips. I have a WebAPI and OData hosted in same API to allow legacy app to directly perform simple crud via OData endpoint. Also the connection object have some additional customization so it is injected in Context that's why there's `GetMyContext` method. I'm still getting myself familiar with the RESTIER and OData. So I might keep posting issues/questions here and on SO.
