### ISSUE TITLE
Using `MaxTop` doesn't change the limit for `Top`

### ISSUE THREAD

**Issue by KristofferStrube** [OData/RESTier#719]
When we configure OData in the Startup class with `MaxTop` it doesn't change the actual limit for how big a `Top` request we can make from an `ODataClient`. The standard limit is `5` meaning that we can't make `Top` requests larger than `5`.

### Assemblies affected
I know that this is a problem in version `2.0.0-CI-20220915-060434` of Restier, but I don't know in which version the bug was introduced.

### Reproduce steps
1. Configure your Restier API with a `MaxTop` to 1000.
2. Use a `ODataClient` to make a request on that API which uses a `Top` command with a value larger than `5`

### Expected result
You would get the expected amount of elements back from the query.

### Actual result
You get an error telling you that you can't request more than `5` elements when using a `Top` command.

**Comment by ozzioma** [comment]
Any update on this?

**Comment by robertmclaws** [comment]
Tracking through the above-mentioned super-issue.
