### ISSUE TITLE
Imperative views should be able to return data with a shape different from the boilerplate entity types.

### ISSUE THREAD

**Issue by paulvanbladel** [OData/RESTier#72]
Most line of business app have list screens where a combination or a subset of fields is needed rather than the boilerplate entity types.
It make sense to restrict the whole functionality of imperative views to READ-ONLY.
Imperative views should fully take into account the definined entity filters on the boilerplate entity types.

**Comment by joshbooker** [comment]
+1 Great suggestion Paul!  Please make this a priority.

**Comment by karataliu** [comment]
For current, this could be accomplished by falling back to WebAPI OData. But we could also try to explore new ways to make it easier to archive this in RESTier.

**Comment by lgadola** [comment]
Is there any news on how to extend the model with imperative views?
(without falling back to WebAPI)

**Comment by lewischeng-ms** [comment]
@lgadola Imperative views are supported from the beginning. Please see the doc here: http://odata.github.io/RESTier/#16-01-Model-building and search for *Extend a model from Api class*. Thanks.

**Comment by lgadola** [comment]
@lewischeng-ms 
could you please provide an example of how to extend an EF EDM with custom types? That would be very helpful.
Thanks, Lukas

**Comment by lewischeng-ms** [comment]
@lgadola In order to extend with **custom types**, you must have already defined the corresponding EDM entity types in the model. RESTier cannot deal with CLR types and entity types that are generated "on the fly" because there are many technical difficulties on projection support in both Web API and Entity Framework. Sorry about that.

If you need an example, suppose you have an entity type `Person` in the database and a custom type `PersonWithAge` for the view. You may write the public property like this:

```
public IQueryable<PersonWithAge> PeopleWithAge
{
    get { return DbContext.People.Select(p => new PersonWithAge(p); }
}
```

And please see http://odata.github.io/RESTier/#16-01-Model-building for how to manually add a custom entity type `PersonWithAge` to your model.

Thanks.

**Comment by chinadragon0515** [comment]
@paulvanbladel @joshbooker @lgadola Can I know whether you have any more questions with this item? If not, I will close the issue.

**Comment by lgadola** [comment]
thanks, it is clear to me

**Comment by joshbooker** [comment]
I think what Paul is saying is that RESTier can only return a  IQueryable<T> where T is a single Entity type in the model.  So in the example code above you get a collection of Person type.  Has that changed?  

I believe, what he's suggesting is to return a custom type.  So <T> could be a subset of properties from a join of multiple entity types, for example.  

The second part of his suggestion is if the base entities have entity filters, those filters must be enforced on the imperative views.  I believe this has it's own issue# somewhere.

**Comment by chinadragon0515** [comment]
@joshbooker The example above return a collection of customized type PersonWithAge, and for the PersonWithAge constructor, it will accept a person, you can define how PersonWithAge to set its property values.

For the onfilter part, this will require user to define OnfilterPersonWithAge as for restier itself, it does touch the map information.  We will consider this when we implement Issue #192

**Comment by chinadragon0515** [comment]
A imperative view samples was added with PR #461 , any one has any comments is highly welcomed.

**Comment by chinadragon0515** [comment]
I did not hear further comments, close the issue now, if any one has any other questions or issues or request, open new issues.
