### ISSUE TITLE
How to override BaseAddressFactory to replace @odata.context uri?

### ISSUE THREAD

**Issue by tachyus-ryan** [OData/RESTier#721]
I host OData behind a reverse proxy. The internal API is returned in the `@odata.context`, but I would like to replace that with the public API URI.

### Assemblies affected
RESTier 1.0.0-rc8.20220714.1

### Reproduce steps
1. Host RESTier API behind [YARP](https://microsoft.github.io/reverse-proxy/)
2. Response contains the URI for the OData API and not the YARP URI
3. Attempt to set `ODataInputFormatter.BaseAddressFactory` and `ODataOutputFormatter.BaseAddressFactory`:
``` csharp
    builder.Services.AddControllers(options =>
    {
        options.EnableEndpointRouting = false;

        foreach (var inputFormatter in options.InputFormatters.OfType<ODataInputFormatter>())
            inputFormatter.BaseAddressFactory = _ => new Uri("https://example.com");

        foreach (var outputFormatter in options.InputFormatters.OfType<ODataOutputFormatter>())
            outputFormatter.BaseAddressFactory = _ => new Uri("https://example.com");
    });
```

### Expected result
Should see `@odata.context: "https://example.com/odata/$metadata"` URI

### Actual result
Still see `@odata.context: "http://localhost:5000/odata/$metadata"` URI

**Comment by robertmclaws** [comment]
Are you OK with me turning this into a helper method for Restier 1.0? It's 🔥

**Comment by tachyus-ryan** [comment]
Absolutely!

**Comment by tachyus-ryan** [comment]
@robertmclaws I just made an update to my snippet above. The approach I used initially did not work if I hosted OData in a path off the root. I changed it so that it will replace the host rather than always resolve to the host.
