### ISSUE TITLE
Restier 1.0 Has Finally Shipped!

### ISSUE THREAD

**Issue by robertmclaws** [OData/RESTier#722]
Restier 1.0 for ASP.NET 4.7.2, ASP.NET Core 3.1, .NET 6.0, and .NET 7.0 is now live! It's been a long 8 years, but we Finally made it to GA! Please check out the latest bits on GitHub and let us know what you think!

**Comment by vincedan** [comment]
.....so long......, thanks team.

**Comment by michallabuzsybilla** [comment]
There is no single line of documentation saying HOW TO USE IT. What kind of joke is it?

**Comment by robertmclaws** [comment]
> What's the default $metadata route/URL? is it /odata/$metadata?

The default route depends on the route name you register the service with. [In this example](https://github.com/OData/RESTier/blob/8b29d6b27f51a5d4bfb12902cd8c7c0f87d3b22e/src/Microsoft.Restier.Samples.Northwind.AspNetCore/Startup.cs#L87), the route is /$metadata.

**Comment by OlzhabaevSh** [comment]
Congrats!
