### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by yzorg** [OData/RESTier#727]
*Short summary (3-5 sentences) describing the issue.*  

### Assemblies affected
None.  Mostly asking about project status, documentation, and **readme** (aka GitHub 1st thing developers see when evaluating the library).

### Reproduce steps
This project looks "dead" from the outside.  It looks like the very minimal effort was put in to update it to *"slightly"* newer odata (but open discussion asking about odata 8.x makes me think it doe NOT support the **recommended** odata for .NET 7+.

```readme.md
## Supported Platforms
Restier 1.0 currently ships with support for Classic ASP.NET 5.2.7 and later. 
Support for .NET 5 and later is coming in the second half of 2021.
```

The above snipppet from readme makes the project look dead.  That version of ASP.NET has been out of support for YEARS.

### Expected result
Devs come here, see this is a "living and working" project, and devs use it. 

### Actual result
Devs come here, or the primary documentation site, see cobwebs and references to ancient dead .NET versions, and run away screaming.  : )

**Comment by plettb** [comment]
Yep, I came here looking for a solution to expose my data via OData quickly and easily.  The project looks like it has so little activity that I'm reluctant to start with it.

**Comment by DennyFiguerres** [comment]
can anyone give an example of current use with core 6 or core 7 ??
or is this a dead end ?
kind of looks like a dead end right now....

**Comment by robertmclaws** [comment]
Restier is in active development and has shipped a functioning V1, as well as numerous improvements and enhancements in CI builds.

None of the developers are paid to work on this project, so lack of checkins does not mean that the project it dead. It's actively used in dozens of apps, and we'll be working on Restier 2.0 + OData v8 in the near future.

**Comment by robertmclaws** [comment]
I've updated the home page with more details, including how to get started, the frameworks that are supported, and links to the samples. Hope that helps!

**Comment by plettb** [comment]
> can anyone give an example of current use with core 6 or core 7 ?? or is this a dead end ? kind of looks like a dead end right now....

I can say that we're using it and are very pleased with it so far, but I share your concerns.  Fortunately it feels like we have now had a little reassurance.
