### ISSUE TITLE
Support for Capabilities in WebAPI/RESTier

### ISSUE THREAD

**Issue by congysu** [OData/RESTier#73]
Services built with RESTier should have a way to expose an accurate Capabilities vocabulary.
This might depend on WebAPI work items, such as:
https://github.com/OData/WebApi/issues/258
https://github.com/OData/WebApi/issues/107
https://github.com/OData/WebApi/issues/98

Related ODataLib issue:
https://github.com/OData/odata.net/issues/152

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
