### ISSUE TITLE
How to replace the .AddChainedService<T> Method

### ISSUE THREAD

**Issue by yulivee** [OData/RESTier#757]
Currently using RESTier version `1.1.0-rc.1.20231121.1` I get the following tooltip:

![AddChainedService](https://github.com/OData/RESTier/assets/12939922/9ed649c1-a64e-4e93-ae6d-be5053db4862)

We use the `AddChainedServicesMethod` to extend the `IChangeSetItemAuthorizer` with custom logic we depend on. 

If this way is deprecated, how is it supposed to look going forward? Where do I find up-to-date documentation on this topic?

[Chapter 2.3 in the Docs](http://odata.github.io/RESTier/#02-09-Customize-Submit) recommend using the `ConfigureApi()` method in the Api-Class but I get an Error-Message stating `EntityFrameworkApi<T>` does not contain a definition for `ConfigureApi`. I am a bit lost on that... The Northwind-Sample for AspNetCore is a less complex example and does not include custom Authorizer Logic

**Comment by yulivee** [comment]
Tooltip still exists after update to Restier v1.1.0. Still clueless. The referenced docs seem out of date

**Comment by robertmclaws** [comment]
If I'm not mistaken, you can call `.AddChainedService<IChangeSetItemAuthorizer, YourChangesetItemAuthorizer>()` after [this line](https://github.com/OData/RESTier/blob/main/src/Microsoft.Restier.Samples.Northwind.AspNetCore/Startup.cs#L54-L61).

That's pretty much [how the built-in one is registered here](https://github.com/OData/RESTier/blob/main/src/Microsoft.Restier.Core/Extensions/ServiceCollectionExtensions.cs#L218).

I'm going to close this as solved, but feel free to re-open it if you have any other questions. Thanks!
