### ISSUE TITLE
Verify: Save order of batched requests is guaranteed

### ISSUE THREAD

**Issue by congysu** [OData/RESTier#76]
RESTier has an EF provider with transaction batch save support.  Verify if the following issue still exists:
Save order of batched requests is not guaranteed (e.g., could insert line-items before inserting parent order)

**Comment by congysu** [comment]
Related [test case](https://github.com/OData/RESTier/blob/master/test/Microsoft.Restier.Samples.Northwind.Tests/ODataFeedTests.cs): `public async Task TestBatch()`.

**Comment by congysu** [comment]
On client side, create a batch request:
1.	Create a new Customer
2.	Create a new Order: order has a foreign key to the new customer.
3.	Commit

and:
1.	Create a new Customer
2.	Create a new Order: order has a foreign key to the new customer.
3.	Rollback on server side.

The result is:
An e2e test to cover this scenario in RESTier.

**Comment by lewischeng-ms** [comment]
Case added in #84
