### ISSUE TITLE
Northwind sample uses DB script, instead of .mdf | .ldf

### ISSUE THREAD

**Issue by congysu** [OData/RESTier#77]
Consider changing the [Microsoft.Restier.Samples.Northwind](https://github.com/OData/RESTier/tree/master/src/Microsoft.Restier.Samples.Northwind) sample to use DB script, e.g., [instnwnd.sql](https://msdn.microsoft.com/en-us/library/ff851969(v=vs.100).aspx), instead of .mdf and .ldf files.

**Comment by lewischeng-ms** [comment]
Committed as https://github.com/OData/RESTier/commit/6f4e16c387f87b6e7260513f0471b0dcdc131043
