### ISSUE TITLE
Schema manipulation via RESTful calls to the $metadata service

### ISSUE THREAD

**Issue by congysu** [OData/RESTier#81]
For example, send a POST request to `/$metadata/Types` to create a type.

Support create, update, delete schema elements: types, operations, and also entity container elements: entity sets, operation imports.
[15      Metadata Service Schema](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part3-csdl/odata-v4.0-errata02-os-part3-csdl-complete.html#_Toc406398100)
[MetadataService.edmx](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/models/MetadataService.edmx)

Related issues:
https://github.com/OData/odata.net/issues/54 https://github.com/OData/odata.net/issues/88 https://github.com/OData/odata.net/issues/181

**Comment by jslegers** [comment]
I suppose this is related to the question [Fetching $metadata for a specific collection or entity with Odata web services in Microsoft Dynamics NAV 2016](http://stackoverflow.com/questions/35543769/fetching-metadata-for-a-specific-collection-or-entity-with-odata-web-services-i) that I posted on StackOverflow today?!

**Comment by robertmclaws** [comment]
Realistically, this is not likely to happen. I'm closing this down for now, and we'll re-evaluate it for inclusion in the future.
