### ISSUE TITLE
Deadlock is occurred when one of the request in batch failed. ContentId in batch is not handled correctly.

### ISSUE THREAD

**Issue by karataliu** [OData/RESTier#82]
When sending request with $number links, the server will not return 

it would throws internal exception when Uri contains $2.

--batch_a48943c6-ee47-46f4-91cb-6e4335a3b6a6
Content-Type: multipart/mixed; boundary=changeset_ff84f2ad-0f3b-4bdd-adfa-eb54f7c101b6

--changeset_ff84f2ad-0f3b-4bdd-adfa-eb54f7c101b6
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 1

POST http://localhost.fiddler:18384/api/Trippin/Airlines HTTP/1.1
OData-Version: 4.0;NetFx
OData-MaxVersion: 4.0;NetFx
Content-Type: application/json;odata.metadata=minimal
Accept: application/json;odata.metadata=minimal
Accept-Charset: UTF-8
User-Agent: Microsoft ADO.NET Data Services

{"@odata.type":"#Microsoft.Restier.WebApi.Test.Services.Trippin.Models.Airline","AirlineCode":"DL","Name":"American Delta"}
--changeset_ff84f2ad-0f3b-4bdd-adfa-eb54f7c101b6
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 2

POST http://localhost.fiddler:18384/api/Trippin/Flights HTTP/1.1
OData-Version: 4.0;NetFx
OData-MaxVersion: 4.0;NetFx
Content-Type: application/json;odata.metadata=minimal
Accept: application/json;odata.metadata=minimal
Accept-Charset: UTF-8
User-Agent: Microsoft ADO.NET Data Services

{"@odata.type":"#Microsoft.Restier.WebApi.Test.Services.Trippin.Models.Flight","AirlineId":"DL","ConfirmationCode":"JH58496","Duration":"PT0S","EndsAt":"2014-02-10T16:30:00+08:00","FlightId":0,"FlightNumber":"DL589","FromId":"KSEA","SeatNumber":"C32","StartsAt":"2014-02-10T15:00:00+08:00","ToId":"ZSSS"}
--changeset_ff84f2ad-0f3b-4bdd-adfa-eb54f7c101b6
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 3

PUT $2/Airline/$ref HTTP/1.1
OData-Version: 4.0;NetFx
OData-MaxVersion: 4.0;NetFx
Accept: application/json;odata.metadata=minimal
Accept-Charset: UTF-8
Content-Type: application/json;odata.metadata=minimal
User-Agent: Microsoft ADO.NET Data Services

{"@odata.id":"$1"}
--changeset_ff84f2ad-0f3b-4bdd-adfa-eb54f7c101b6--
--batch_a48943c6-ee47-46f4-91cb-6e4335a3b6a6--

**Comment by RemcoBlok** [comment]
There is an additional method of referencing Content-Id's in batches that always worked with WCF Data Services. For example, this is a batch which inserts a new Workflow and then updates a SampleContainer that references the new Workflow

--batch_8a8a-0fc5-8d99
 Content-Type: multipart/mixed; boundary=changeset_4da5-38d3-bae1

--changeset_4da5-38d3-bae1
 Content-Type: application/http
 Content-Transfer-Encoding: binary

POST Workflows HTTP/1.1
 DataServiceVersion: 3.0
 Accept: application/json;odata=verbose
 Content-ID: 1
 Content-Type: application/json;odata=verbose
 MaxDataServiceVersion: 3.0

{json representation of a new workflow}
 --changeset_4da5-38d3-bae1
 Content-Type: application/http
 Content-Transfer-Encoding: binary

MERGE SampleContainers(1) HTTP/1.1
 Prefer: return-content
 DataServiceVersion: 3.0
 Accept: application/json;odata=verbose
 Content-Type: application/json;odata=verbose
 MaxDataServiceVersion: 3.0

{"Archived":false,"LastCertified":null,"Notes":null,"OffHire":null,"OnHire":null,"Owner":"Remco","Rented":false,"SerialNumber":"123","StatusValue":"OK","CurrentWorkflow":{"__metadata":{"uri":"$1"}},"DefaultLocationId":1,"TypeId":1}
 --changeset_4da5-38d3-bae1--

--batch_8a8a-0fc5-8d99--

It would be good if RESTier could support this method as well. As I said, this currently works with WCF Data Services. Unfortunately it does not currently work with WebApi OData v3 either. See 
https://github.com/OData/WebApi/issues/512

**Comment by mirsking** [comment]
1. Server won't return when any of requests in ChangeSet failed.
This issue have already fixed by PR #514 .

2. $ContentId & custom $ref in ChangeSet are not supported by Restier right now.
This will be described in Issue #83 .
