### ISSUE TITLE
Batch doesn't support updating reference link in custom controllers, and $ContentId is not supported right now, either.

### ISSUE THREAD

**Issue by karataliu** [OData/RESTier#83]
The server won't give response when batch request contains update to reference.

It will stop responding and stay at following waiting logic.
at ODataDomainChangeSetRequestItem::SendRequestAsync

 await Task.WhenAll(responseTasks);

If a user function uses WebAPI's approach to use a custom handles $ref, but deal with DBContext directly, would cause the following code not working:

ODataDomainChangeSetProperty::OnChangeSetCompleted
As user code doesn't look at subRequestCount, so it won't reach zero.

**Comment by karataliu** [comment]
Also, when any code throws exception, the batch request won't return.

**Comment by mirsking** [comment]
1. When any code throws exception, the batch request won't return.
This is now fixed by PR #514 .
2. Batch doesn't support updating reference link in custom controllers.
3. $ContentId is not support in a changeset of batch request right now.

**Comment by robertmclaws** [comment]
Closing this for now. A lot has changed since this issue was opened. If you still experience this issue in the nightly or upcoming 1.0 Beta 2 bits, please re-open this issue and we will address it. Thanks!
