### ISSUE TITLE
Odata server cannot work with function return collection

### ISSUE THREAD

**Issue by hungdluit** [OData/RESTier#88]
Hi,

I'm new. I'm trying create odata domain controller. It has a searcher function with text input. I tried many options but cannot make it work. Hope someone can help :)

 protected EdmModel OnModelExtending(EdmModel model)
        {
            var ns = model.DeclaredNamespaces.First();
            var word = model.FindDeclaredType(ns + "." + "Word");
            var search = new EdmFunction(
                ns,
                "Search",
                new EdmCollectionTypeReference(new EdmCollectionType(word.GetEdmTypeReference(true))),
                true,
                null,
                false);
            search.AddParameter("text", EdmCoreModel.Instance.GetString(false));
            model.AddElement(search);
            return model;
        }

// startwith text searching
[HttpGet]
[ODataRoute("Words/WordNet.Models.Search")]
 public IHttpActionResult Search(ODataActionParameters parameters)
        {               
            IQueryable<Word> words = DbContext.Words.Where(x => x.Lemma.ToLower().StartsWith(parameters["text"].ToString().ToLower())).Take(10);
            return Json(words);
        }

I got an exception: "The path template 'Words/WordNet.Models.Search' on the action 'Search' in controller 'WordNet' is not a valid OData path template. The request URI is not valid. Since the segment 'Words' refers to a collection, this must be the last segment in the request URI or it must be followed by an function or action that can be bound to it otherwise all intermediate segments must refer to a single resource."

   at System.Web.OData.Routing.Conventions.AttributeRoutingConvention.GetODataPathTemplate(String prefix, String pathTemplate, HttpActionDescriptor action)
   at System.Web.OData.Routing.Conventions.AttributeRoutingConvention.<>c__DisplayClassa.<GetODataPathTemplates>b__7(ODataRouteAttribute route)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Web.OData.Routing.Conventions.AttributeRoutingConvention.BuildAttributeMappings(IEnumerable`1 controllers)
   at System.Web.OData.Routing.Conventions.AttributeRoutingConvention.<>c__DisplayClass1.<.ctor>b__0(HttpConfiguration config)
   at System.Web.Http.HttpConfiguration.EnsureInitialized()
   at WordNetHost.Startup.Configuration(IAppBuilder appBuilder) in e:\Projects\Desktop\WordNetHost\Program.cs:line 35

Thank you.

**Comment by karataliu** [comment]
@hungdluit 

There're several things need to be changed here:

1. Add the binding parameter as the first parameter of your function.
  *search.AddParameter("source", new EdmCollectionTypeReference(new EdmCollectionType(word.GetEdmTypeReference(true))));*
  search.AddParameter("text", EdmCoreModel.Instance.GetString(false));

2. Change the function to something like:
  ```
  [ODataRoute("Words/WordNet.Models.Search(text={searchText})")]
  public IHttpActionResult Search([FromODataUri]string searchText)
  ```

3. In web.config update the following line
  ```
  <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
  ```
  and change it to
  ```
  <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*" verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
  ```

Then you can request your function with:
```
http://host/root/Words/WordNet.Models.Search(text='var1')
```

**Comment by hungdluit** [comment]
Thanks for your support

**Comment by karataliu** [comment]
@hungdluit Looks like this should work, and we're to close this issue. Your further feedbacks are warmly welcomed.
