### ISSUE TITLE
RESTier nuget package's "Project Site" url is missing

### ISSUE THREAD

**Issue by congysu** [OData/RESTier#92]
Link: https://www.nuget.org/packages/Microsoft.RESTier

**Comment by congysu** [comment]
Also need a release note link: https://www.nuget.org/packages/Microsoft.Restier/0.3.0-beta1

**Comment by lewischeng-ms** [comment]
Fixed in https://github.com/OData/RESTier/commit/99f078b81afeacd5a52ccfb11c2ee62f8a28a419
