### ISSUE TITLE
Design proposal: Use Microsoft.Framework.DependencyInjection as backbone of DomainConfiguration hook points

### ISSUE THREAD

**Issue by rayao** [OData/RESTier#98]
MVC 5 is built upon this dependency framework, so I believe next major version of OData API would be built upon it also, then it's natural to use it on RESTier.

**Comment by karataliu** [comment]
good point, we're also considering update some existing APIs to use DI.https://github.com/OData/RESTier/issues/150

**Comment by lewischeng-ms** [comment]
Now we are using a middleware processing style like request delegate in ASP.NET 5.
